from __future__ import annotations

from enum import StrEnum
from hashlib import sha256
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, model_validator

from .common import FROZEN_MODEL_CONFIG, Sha256Hex, VersionString, canonical_sha256
from .enums import AGENT_RESOURCE_MATRIX, ResourceType, SourceAgent


class BlockType(StrEnum):
    MARKDOWN = "MARKDOWN"
    MERMAID = "MERMAID"
    QUIZ = "QUIZ"
    CODE = "CODE"
    EXTENSION = "EXTENSION"
    METADATA = "METADATA"


class BlockStatus(StrEnum):
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class CandidateStatus(StrEnum):
    GENERATING = "GENERATING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class BlockV1(BaseModel):
    model_config = FROZEN_MODEL_CONFIG

    schema_version: Literal["topic3.block.v1"] = Field(
        description="Frozen wrapper version shared by all Topic 3 block types.",
    )
    block_id: str = Field(
        min_length=1,
        max_length=128,
        description="Stable block identity generated by the owning agent.",
    )
    block_type: BlockType = Field(
        description="Rendering and validation family for the opaque block content.",
    )
    ordinal: int = Field(
        ge=0,
        description="Zero-based order inside the candidate; ordinals must be contiguous.",
    )
    title: str | None = Field(
        default=None,
        max_length=256,
        description="Optional student-visible title supplied by the owning agent.",
    )
    content_schema_version: VersionString = Field(
        description="Owning agent payload schema version for the content object.",
    )
    content: dict[str, Any] = Field(
        description="Frozen agent-specific content. Infrastructure must not rewrite it.",
    )
    content_sha256: Sha256Hex = Field(
        description="SHA-256 of canonical content JSON, excluding wrapper metadata.",
    )
    dependency_block_ids: list[str] = Field(
        default_factory=list,
        max_length=128,
        description="Candidate-local block dependencies used for ordering and validation.",
    )
    status: BlockStatus = Field(
        description="Generation status of this exact block version.",
    )
    created_at: AwareDatetime = Field(
        description="UTC block completion time from the owning agent.",
    )

    @model_validator(mode="after")
    def validate_block_dependencies(self) -> BlockV1:
        if canonical_sha256(self.content) != self.content_sha256:
            raise ValueError("content_sha256 does not match canonical content JSON")
        if self.block_id in self.dependency_block_ids:
            raise ValueError("block cannot depend on itself")
        if len(self.dependency_block_ids) != len(set(self.dependency_block_ids)):
            raise ValueError("duplicate dependency_block_ids")
        return self


class CandidateProvenanceV1(BaseModel):
    model_config = FROZEN_MODEL_CONFIG

    agent: SourceAgent = Field(description="Owning Topic 3 generation agent.")
    agent_build_version: VersionString = Field(
        description="Owning agent build version used to generate the candidate.",
    )
    prompt_bundle_version: VersionString = Field(
        description="Frozen prompt bundle selected by the blueprint.",
    )
    provider_alias: Literal["spark_text", "xfyun_code", "seedance", "local"] = Field(
        description="Approved provider alias or local deterministic producer.",
    )
    provider_request_ids: list[str] = Field(
        default_factory=list,
        max_length=256,
        description="Provider request identities retained for audit without credentials.",
    )


class CandidateV1(BaseModel):
    model_config = FROZEN_MODEL_CONFIG

    schema_version: Literal["topic3.candidate.v1"] = Field(
        description="Frozen candidate wrapper version.",
    )
    candidate_id: UUID = Field(
        description="Logical candidate identity preserved across revision versions.",
    )
    candidate_version: int = Field(
        ge=1,
        description="Monotonically increasing candidate version.",
    )
    parent_candidate_version: int | None = Field(
        default=None,
        ge=1,
        description="Previous version when produced by a revision; null for version one.",
    )
    blueprint_id: UUID = Field(
        description="Immutable Blueprint identity that authorized generation.",
    )
    blueprint_version: VersionString = Field(
        description="Exact Blueprint version bound to this candidate.",
    )
    blueprint_sha256: Sha256Hex = Field(
        description="Canonical Blueprint hash used to detect drift.",
    )
    resource_type: ResourceType = Field(
        description="Resource family owned by the generating agent.",
    )
    status: CandidateStatus = Field(
        description="Lifecycle status of this exact candidate version.",
    )
    blocks: list[BlockV1] = Field(
        min_length=1,
        max_length=2048,
        description="Ordered immutable blocks produced by the agent.",
    )
    provenance: CandidateProvenanceV1 = Field(
        description="Agent, prompt, provider, and request provenance.",
    )
    personalization_policy_digest: Sha256Hex = Field(
        description="Hash of the frozen Topic 2 personalization input used by generation.",
    )
    candidate_sha256: Sha256Hex = Field(
        description="SHA-256 of the canonical candidate excluding this field.",
    )
    created_at: AwareDatetime = Field(
        description="UTC completion time of this candidate version.",
    )

    @model_validator(mode="after")
    def validate_candidate(self) -> CandidateV1:
        if self.candidate_version == 1 and self.parent_candidate_version is not None:
            raise ValueError("candidate version one cannot have a parent version")
        if (
            self.candidate_version > 1
            and self.parent_candidate_version != self.candidate_version - 1
        ):
            raise ValueError("parent_candidate_version must be the previous version")

        block_ids = [block.block_id for block in self.blocks]
        if len(block_ids) != len(set(block_ids)):
            raise ValueError("candidate contains duplicate block_id values")

        ordinals = sorted(block.ordinal for block in self.blocks)
        if ordinals != list(range(len(self.blocks))):
            raise ValueError("block ordinals must be contiguous and zero-based")

        block_id_set = set(block_ids)
        for block in self.blocks:
            if not set(block.dependency_block_ids) <= block_id_set:
                raise ValueError("block dependency references an unknown block")
        if self.resource_type not in AGENT_RESOURCE_MATRIX[self.provenance.agent]:
            raise ValueError("resource_type is not owned by the provenance agent")
        candidate_document = self.model_dump(mode="json", exclude={"candidate_sha256"})
        if canonical_sha256(candidate_document) != self.candidate_sha256:
            raise ValueError("candidate_sha256 does not match the canonical candidate")
        return self


class StreamFragmentType(StrEnum):
    START = "START"
    DELTA = "DELTA"
    END = "END"
    SNAPSHOT = "SNAPSHOT"


class SSEChunkV1(BaseModel):
    model_config = FROZEN_MODEL_CONFIG

    schema_version: Literal["topic3.sse-chunk.v1"] = Field(
        description="Topic 3 internal streaming fragment version.",
    )
    stream_id: UUID = Field(description="Generation stream identity.")
    fragment_id: UUID = Field(description="Unique fragment identity for idempotency.")
    candidate_id: UUID = Field(description="Logical candidate identity.")
    candidate_version: int = Field(ge=1, description="Exact candidate version.")
    block_id: str | None = Field(
        default=None,
        max_length=128,
        description="Block identity for block-scoped fragments.",
    )
    fragment_type: StreamFragmentType = Field(
        description="Start, delta, end, or complete snapshot fragment.",
    )
    chunk_index: int = Field(
        ge=0,
        description="Zero-based fragment order within candidate/block partition.",
    )
    is_final: bool = Field(
        description="True only for the final fragment in the current partition.",
    )
    data_encoding: Literal["utf-8-json", "utf-8-text"] = Field(
        description="Encoding of the fragment data field.",
    )
    data: str = Field(
        max_length=65536,
        description="Fragment body; unverified content remains staged.",
    )
    data_sha256: Sha256Hex = Field(
        description="SHA-256 of the exact UTF-8 fragment bytes.",
    )

    @model_validator(mode="after")
    def validate_fragment(self) -> SSEChunkV1:
        digest = sha256(self.data.encode("utf-8")).hexdigest()
        if digest != self.data_sha256:
            raise ValueError("data_sha256 does not match the exact UTF-8 data bytes")
        if self.fragment_type == StreamFragmentType.START and self.chunk_index != 0:
            raise ValueError("START fragments must use chunk_index zero")
        if self.fragment_type == StreamFragmentType.END and not self.is_final:
            raise ValueError("END fragments must be final")
        if self.is_final and self.fragment_type not in {
            StreamFragmentType.END,
            StreamFragmentType.SNAPSHOT,
        }:
            raise ValueError("final fragments must be END or SNAPSHOT")
        return self

    emitted_at: AwareDatetime = Field(
        description="UTC fragment creation time from the SSE collection layer.",
    )
