from __future__ import annotations

from pydantic import BaseModel

from .topic4_c1 import (
    AggregationResultV1,
    AuditEventV1,
    ClaimRiskV1,
    ClaimV1,
    ClaimVerdictV1,
    EvidenceChainManifestV1,
    HumanReviewDecisionV1,
    HumanReviewTaskV1,
    ModuleDispatchPlanV1,
    ModuleRunResultV1,
    ModuleRunV1,
    PublicationBatchV1,
    PublicStreamEventV1,
    RevisionRequestV1,
    RevisionResponseV1,
    VerificationProgressV1,
    VerificationReportV1,
)
from .topic4_c2 import (
    DocumentIRV1,
    EmbeddingProfileV1,
    EvidenceBundleV1,
    EvidenceRefV1,
    FormulaSignatureV1,
    IndexBuildManifestV1,
    KnowledgeBaseVersionV1,
    KnowledgeChunkV1,
    QueryPlanV1,
    RetrievalRequestV1,
    RetrievalResponseV1,
    SourceDocumentV1,
    SourceDocumentVersionV1,
)
from .topic4_c3 import (
    DerivationCheckResultV1,
    FactSynthesisRequestV1,
    FactSynthesisResultV1,
    FormulaEquivalenceResultV1,
    FormulaIRV1,
    StabilityCheckResultV1,
    StabilityModelV1,
    TheoremCheckResultV1,
    TheoremRegistryEntryV1,
)
from .topic4_c4 import GraphVerificationResultV1, VerifierGraphIRV1
from .topic4_c5 import QuizItemVerifierIRV1, QuizVerificationResultV1
from .topic4_c6 import CodeArtifactV1, CodeVerificationResultV1, SandboxPolicyV1
from .topic4_c7 import ExtensionVerificationResultV1, VerifierExtensionResourceV1
from .topic4_c8 import RevisionCycleV1, RevisionPatchV1, RevisionPlanV1
from .topic4_c9 import SecurityFindingV1
from .topic4_c10 import PIIFindingV1, PrivacyTenantResultV1, TokenizedValueV1
from .topic4_c11 import BuildProvenanceV1, SBOMManifestV1, VulnerabilityRecordV1
from .topic4_c12 import SystemAcceptanceReportV1

ContractSpec = tuple[str, str, str, str, type[BaseModel]]

TOPIC4_CONTRACT_SPECS: tuple[ContractSpec, ...] = (
    ("verification.progress.v1", "c1-verification", "shared", "strict-v1", VerificationProgressV1),
    ("claim.v1", "c1-verification", "internal", "strict-v1", ClaimV1),
    ("claim.risk.v1", "c1-verification", "internal", "strict-v1", ClaimRiskV1),
    (
        "module-dispatch-plan.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        ModuleDispatchPlanV1,
    ),
    ("module-run.v1", "c1-verification", "internal", "strict-v1", ModuleRunV1),
    (
        "module-run.result.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        ModuleRunResultV1,
    ),
    ("claim.verdict.v1", "c1-verification", "internal", "strict-v1", ClaimVerdictV1),
    (
        "aggregation.result.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        AggregationResultV1,
    ),
    ("revision.request.v1", "c1-verification", "internal", "strict-v1", RevisionRequestV1),
    (
        "revision.response.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        RevisionResponseV1,
    ),
    (
        "verification.report.v1",
        "c1-verification",
        "shared",
        "strict-v1",
        VerificationReportV1,
    ),
    (
        "publication-batch.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        PublicationBatchV1,
    ),
    (
        "public.stream.event.v1",
        "c1-verification",
        "shared",
        "strict-v1",
        PublicStreamEventV1,
    ),
    ("audit-event.v1", "c1-verification", "internal", "strict-v1", AuditEventV1),
    (
        "evidence-chain-manifest.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        EvidenceChainManifestV1,
    ),
    (
        "human-review.task.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        HumanReviewTaskV1,
    ),
    (
        "human-review.decision.v1",
        "c1-verification",
        "internal",
        "strict-v1",
        HumanReviewDecisionV1,
    ),
    ("source.document.v1", "c2-knowledge", "internal", "strict-v1", SourceDocumentV1),
    (
        "source.document.version.v1",
        "c2-knowledge",
        "internal",
        "strict-v1",
        SourceDocumentVersionV1,
    ),
    ("document-ir.v1", "c2-knowledge", "internal", "strict-v1", DocumentIRV1),
    ("knowledge-chunk.v1", "c2-knowledge", "internal", "strict-v1", KnowledgeChunkV1),
    ("formula-signature.v1", "c2-knowledge", "internal", "strict-v1", FormulaSignatureV1),
    ("embedding-profile.v1", "c2-knowledge", "internal", "strict-v1", EmbeddingProfileV1),
    (
        "index-build-manifest.v1",
        "c2-knowledge",
        "internal",
        "strict-v1",
        IndexBuildManifestV1,
    ),
    (
        "knowledge-base.version.v1",
        "c2-knowledge",
        "internal",
        "strict-v1",
        KnowledgeBaseVersionV1,
    ),
    ("query-plan.v1", "c2-knowledge", "internal", "strict-v1", QueryPlanV1),
    ("evidence.ref.v1", "c2-knowledge", "internal", "strict-v1", EvidenceRefV1),
    ("evidence.bundle.v1", "c2-knowledge", "internal", "strict-v1", EvidenceBundleV1),
    ("retrieval.request.v1", "c2-knowledge", "internal", "strict-v1", RetrievalRequestV1),
    (
        "retrieval.response.v1",
        "c2-knowledge",
        "internal",
        "strict-v1",
        RetrievalResponseV1,
    ),
    ("formula-ir.v1", "c3-academic", "internal", "strict-v1", FormulaIRV1),
    (
        "formula-equivalence.result.v1",
        "c3-academic",
        "internal",
        "strict-v1",
        FormulaEquivalenceResultV1,
    ),
    (
        "derivation-check.result.v1",
        "c3-academic",
        "internal",
        "strict-v1",
        DerivationCheckResultV1,
    ),
    ("stability-model.v1", "c3-academic", "internal", "strict-v1", StabilityModelV1),
    (
        "stability-check.result.v1",
        "c3-academic",
        "internal",
        "strict-v1",
        StabilityCheckResultV1,
    ),
    (
        "theorem-registry.entry.v1",
        "c3-academic",
        "internal",
        "strict-v1",
        TheoremRegistryEntryV1,
    ),
    (
        "theorem-check.result.v1",
        "c3-academic",
        "internal",
        "strict-v1",
        TheoremCheckResultV1,
    ),
    (
        "fact-synthesis.request.v1",
        "c3-academic",
        "internal",
        "strict-v1",
        FactSynthesisRequestV1,
    ),
    (
        "fact-synthesis.result.v1",
        "c3-academic",
        "internal",
        "strict-v1",
        FactSynthesisResultV1,
    ),
    ("verifier.graph-ir.v1", "c4-graph", "internal", "strict-v1", VerifierGraphIRV1),
    (
        "graph-verification.result.v1",
        "c4-graph",
        "internal",
        "strict-v1",
        GraphVerificationResultV1,
    ),
    (
        "quiz-item.verifier-ir.v1",
        "c5-quiz",
        "internal",
        "strict-v1",
        QuizItemVerifierIRV1,
    ),
    (
        "quiz-verification.result.v1",
        "c5-quiz",
        "internal",
        "strict-v1",
        QuizVerificationResultV1,
    ),
    ("code-artifact.v1", "c6-code", "internal", "strict-v1", CodeArtifactV1),
    ("sandbox-policy.v1", "c6-code", "internal", "strict-v1", SandboxPolicyV1),
    (
        "code-verification.result.v1",
        "c6-code",
        "internal",
        "strict-v1",
        CodeVerificationResultV1,
    ),
    (
        "extension-resource.v1",
        "c7-extension",
        "internal",
        "strict-v1",
        VerifierExtensionResourceV1,
    ),
    (
        "extension-verification.result.v1",
        "c7-extension",
        "internal",
        "strict-v1",
        ExtensionVerificationResultV1,
    ),
    ("revision-cycle.v1", "c8-revision", "internal", "strict-v1", RevisionCycleV1),
    ("revision-plan.v1", "c8-revision", "internal", "strict-v1", RevisionPlanV1),
    ("revision-patch.v1", "c8-revision", "internal", "strict-v1", RevisionPatchV1),
    ("security-finding.v1", "c9-security", "internal", "strict-v1", SecurityFindingV1),
    ("pii-finding.v1", "c10-privacy", "internal", "strict-v1", PIIFindingV1),
    ("tokenized-value.v1", "c10-privacy", "internal", "strict-v1", TokenizedValueV1),
    (
        "privacy-tenant.result.v1",
        "c10-privacy",
        "internal",
        "strict-v1",
        PrivacyTenantResultV1,
    ),
    ("sbom-manifest.v1", "c11-compliance", "internal", "strict-v1", SBOMManifestV1),
    (
        "vulnerability-record.v1",
        "c11-compliance",
        "internal",
        "strict-v1",
        VulnerabilityRecordV1,
    ),
    (
        "build-provenance.v1",
        "c11-compliance",
        "internal",
        "strict-v1",
        BuildProvenanceV1,
    ),
    (
        "system-acceptance-report.v1",
        "c12-qa",
        "internal",
        "strict-v1",
        SystemAcceptanceReportV1,
    ),
)
