// Code generated by tools/export_contracts.py. DO NOT EDIT.

package contracts

type UUID string

type DateTime string

type ArtifactObjectRefV1 struct {
	SchemaVersion    string   `json:"schema_version"`
	StorageNamespace string   `json:"storage_namespace"`
	ObjectKey        string   `json:"object_key"`
	MediaType        string   `json:"media_type"`
	ContentEncoding  string   `json:"content_encoding"`
	ByteSize         int64    `json:"byte_size"`
	Sha256           string   `json:"sha256"`
	CreatedAt        DateTime `json:"created_at"`
}

type AuthoritySourceRefV1 struct {
	SourceId      string  `json:"source_id"`
	SourceVersion string  `json:"source_version"`
	Locator       string  `json:"locator"`
	ContentSha256 *string `json:"content_sha256,omitempty"`
}

type BlockSnapshotManifestItemV1 struct {
	BlockId     string `json:"block_id"`
	BlockType   string `json:"block_type"`
	Ordinal     int64  `json:"ordinal"`
	JsonPointer string `json:"json_pointer"`
	Sha256      string `json:"sha256"`
	ByteSize    int64  `json:"byte_size"`
}

type BlockStatus string

const (
	BlockStatusCOMPLETE   BlockStatus = "COMPLETE"
	BlockStatusFAILED     BlockStatus = "FAILED"
	BlockStatusSUPERSEDED BlockStatus = "SUPERSEDED"
)

type BlockType string

const (
	BlockTypeMARKDOWN  BlockType = "MARKDOWN"
	BlockTypeMERMAID   BlockType = "MERMAID"
	BlockTypeQUIZ      BlockType = "QUIZ"
	BlockTypeCODE      BlockType = "CODE"
	BlockTypeEXTENSION BlockType = "EXTENSION"
	BlockTypeMETADATA  BlockType = "METADATA"
)

type BlockV1 struct {
	// Frozen wrapper version shared by all Topic 3 block types.
	SchemaVersion string `json:"schema_version"`
	// Stable block identity generated by the owning agent.
	BlockId string `json:"block_id"`
	// Rendering and validation family for the opaque block content.
	BlockType BlockType `json:"block_type"`
	// Zero-based order inside the candidate; ordinals must be contiguous.
	Ordinal int64 `json:"ordinal"`
	// Optional student-visible title supplied by the owning agent.
	Title *string `json:"title,omitempty"`
	// Owning agent payload schema version for the content object.
	ContentSchemaVersion string `json:"content_schema_version"`
	// Frozen agent-specific content. Infrastructure must not rewrite it.
	Content map[string]any `json:"content"`
	// SHA-256 of canonical content JSON, excluding wrapper metadata.
	ContentSha256 string `json:"content_sha256"`
	// Candidate-local block dependencies used for ordering and validation.
	DependencyBlockIds []string `json:"dependency_block_ids,omitempty"`
	// Generation status of this exact block version.
	Status BlockStatus `json:"status"`
	// UTC block completion time from the owning agent.
	CreatedAt DateTime `json:"created_at"`
}

type CandidateProvenanceV1 struct {
	// Owning Topic 3 generation agent.
	Agent SourceAgent `json:"agent"`
	// Owning agent build version used to generate the candidate.
	AgentBuildVersion string `json:"agent_build_version"`
	// Frozen prompt bundle selected by the blueprint.
	PromptBundleVersion string `json:"prompt_bundle_version"`
	// Approved provider alias or local deterministic producer.
	ProviderAlias string `json:"provider_alias"`
	// Provider request identities retained for audit without credentials.
	ProviderRequestIds []string `json:"provider_request_ids,omitempty"`
}

type CandidateStatus string

const (
	CandidateStatusGENERATING CandidateStatus = "GENERATING"
	CandidateStatusCOMPLETE   CandidateStatus = "COMPLETE"
	CandidateStatusFAILED     CandidateStatus = "FAILED"
	CandidateStatusSUPERSEDED CandidateStatus = "SUPERSEDED"
)

type CandidateV1 struct {
	// Frozen candidate wrapper version.
	SchemaVersion string `json:"schema_version"`
	// Logical candidate identity preserved across revision versions.
	CandidateId UUID `json:"candidate_id"`
	// Monotonically increasing candidate version.
	CandidateVersion int64 `json:"candidate_version"`
	// Previous version when produced by a revision; null for version one.
	ParentCandidateVersion *int64 `json:"parent_candidate_version,omitempty"`
	// Immutable Blueprint identity that authorized generation.
	BlueprintId UUID `json:"blueprint_id"`
	// Exact Blueprint version bound to this candidate.
	BlueprintVersion string `json:"blueprint_version"`
	// Canonical Blueprint hash used to detect drift.
	BlueprintSha256 string `json:"blueprint_sha256"`
	// Resource family owned by the generating agent.
	ResourceType ResourceType `json:"resource_type"`
	// Lifecycle status of this exact candidate version.
	Status CandidateStatus `json:"status"`
	// Ordered immutable blocks produced by the agent.
	Blocks []BlockV1 `json:"blocks"`
	// Agent, prompt, provider, and request provenance.
	Provenance CandidateProvenanceV1 `json:"provenance"`
	// Hash of the frozen Topic 2 personalization input used by generation.
	PersonalizationPolicyDigest string `json:"personalization_policy_digest"`
	// SHA-256 of the canonical candidate excluding this field.
	CandidateSha256 string `json:"candidate_sha256"`
	// UTC completion time of this candidate version.
	CreatedAt DateTime `json:"created_at"`
}

type CourseStatus string

const (
	CourseStatusDRAFT    CourseStatus = "DRAFT"
	CourseStatusACTIVE   CourseStatus = "ACTIVE"
	CourseStatusARCHIVED CourseStatus = "ARCHIVED"
)

type DeliveryMetadataV1 struct {
	// Delivery guarantee. Consumers must be idempotent.
	Mode *string `json:"mode,omitempty"`
	// Stable deduplication key produced by the message originator.
	IdempotencyKey string `json:"idempotency_key"`
	// Current delivery attempt, starting from one.
	Attempt *int64 `json:"attempt,omitempty"`
	// Maximum delivery attempts allowed by the routing policy.
	MaxAttempts *int64 `json:"max_attempts,omitempty"`
	// Queue priority assigned by the deterministic routing policy.
	Priority *MessagePriority `json:"priority,omitempty"`
	// Earliest UTC time at which the message may be dispatched.
	AvailableAt DateTime `json:"available_at"`
	// UTC expiry after which the message must not be executed.
	ExpiresAt *DateTime `json:"expires_at,omitempty"`
}

type ErrorReceiptV1 struct {
	// Wire version for the standard Topic 3 error receipt.
	SchemaVersion string `json:"schema_version"`
	// Stable machine-readable error code from the shared error catalog.
	ErrorCode string `json:"error_code"`
	// Error ownership category such as CONTRACT, PROVIDER, or TIMEOUT.
	Category string `json:"category"`
	// Operational severity; it does not encode academic correctness.
	Severity ErrorSeverity `json:"severity"`
	// Whether infrastructure policy permits another delivery attempt.
	Retriable bool `json:"retriable"`
	// Redacted message safe for logs and authorized clients.
	SafeMessage string `json:"safe_message"`
	// Restricted artifact reference for diagnostics; never raw secrets.
	DetailsRef map[string]any `json:"details_ref,omitempty"`
	// UTC time at which the error occurred.
	OccurredAt DateTime `json:"occurred_at"`
}

type ErrorSeverity string

const (
	ErrorSeverityWARNING  ErrorSeverity = "WARNING"
	ErrorSeverityERROR    ErrorSeverity = "ERROR"
	ErrorSeverityCRITICAL ErrorSeverity = "CRITICAL"
)

type GoldenQuestionType string

const (
	GoldenQuestionTypeSINGLECHOICE   GoldenQuestionType = "SINGLE_CHOICE"
	GoldenQuestionTypeMULTIPLECHOICE GoldenQuestionType = "MULTIPLE_CHOICE"
	GoldenQuestionTypeCALCULATION    GoldenQuestionType = "CALCULATION"
	GoldenQuestionTypePROOF          GoldenQuestionType = "PROOF"
	GoldenQuestionTypeDESIGN         GoldenQuestionType = "DESIGN"
	GoldenQuestionTypeSIMULATION     GoldenQuestionType = "SIMULATION"
)

type KnowledgePointStatus string

const (
	KnowledgePointStatusDRAFT      KnowledgePointStatus = "DRAFT"
	KnowledgePointStatusACTIVE     KnowledgePointStatus = "ACTIVE"
	KnowledgePointStatusDEPRECATED KnowledgePointStatus = "DEPRECATED"
)

type LiteToolDefinitionV1 struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	InputSchema map[string]any `json:"input_schema"`
}

type MessageKind string

const (
	MessageKindCOMMAND MessageKind = "COMMAND"
	MessageKindEVENT   MessageKind = "EVENT"
	MessageKindRESULT  MessageKind = "RESULT"
	MessageKindERROR   MessageKind = "ERROR"
)

type MessagePriority string

const (
	MessagePriorityCRITICAL MessagePriority = "CRITICAL"
	MessagePriorityHIGH     MessagePriority = "HIGH"
	MessagePriorityNORMAL   MessagePriority = "NORMAL"
	MessagePriorityLOW      MessagePriority = "LOW"
)

type MisconceptionSeverity string

const (
	MisconceptionSeverityLOW      MisconceptionSeverity = "LOW"
	MisconceptionSeverityMEDIUM   MisconceptionSeverity = "MEDIUM"
	MisconceptionSeverityHIGH     MisconceptionSeverity = "HIGH"
	MisconceptionSeverityCRITICAL MisconceptionSeverity = "CRITICAL"
)

type PrerequisiteType string

const (
	PrerequisiteTypeREQUIRED    PrerequisiteType = "REQUIRED"
	PrerequisiteTypeRECOMMENDED PrerequisiteType = "RECOMMENDED"
	PrerequisiteTypeSUPPORTING  PrerequisiteType = "SUPPORTING"
)

type ProducerMetadataV1 struct {
	// Producing Topic 3 agent; null for platform infrastructure events.
	Agent *SourceAgent `json:"agent,omitempty"`
	// Stable producing service name from deployment metadata.
	Service string `json:"service"`
	// Ephemeral process or worker instance identity.
	InstanceId string `json:"instance_id"`
	// Immutable producer build version used for provenance.
	BuildVersion string `json:"build_version"`
}

type ReleaseAuthorizationPayloadV1 struct {
	SchemaVersion    string   `json:"schema_version"`
	AuthorizationId  UUID     `json:"authorization_id"`
	VerificationId   UUID     `json:"verification_id"`
	ReportId         UUID     `json:"report_id"`
	CandidateId      UUID     `json:"candidate_id"`
	CandidateVersion int64    `json:"candidate_version"`
	CandidateSha256  string   `json:"candidate_sha256"`
	ReleaseMode      string   `json:"release_mode"`
	AllowedBlockIds  []string `json:"allowed_block_ids"`
	DisclosureCodes  []string `json:"disclosure_codes,omitempty"`
	ReportSha256     string   `json:"report_sha256"`
	IssuedAt         DateTime `json:"issued_at"`
	ExpiresAt        DateTime `json:"expires_at"`
	OneTimeUse       bool     `json:"one_time_use"`
}

type ResourceMetadataV1 struct {
	// Frozen Topic 3 resource family owning the payload.
	ResourceType ResourceType `json:"resource_type"`
	// Immutable blueprint identity from Topic 3 orchestration.
	BlueprintId UUID `json:"blueprint_id"`
	// Blueprint version bound when generation started.
	BlueprintVersion string `json:"blueprint_version"`
	// Logical candidate identity when the message concerns a candidate.
	CandidateId *UUID `json:"candidate_id,omitempty"`
	// Exact candidate version; latest aliases are prohibited.
	CandidateVersion *int64 `json:"candidate_version,omitempty"`
	// Exact block identity for block-scoped messages.
	BlockId *string `json:"block_id,omitempty"`
}

type ResourceType string

const (
	ResourceTypeLecturerDoc       ResourceType = "Lecturer_Doc"
	ResourceTypeMindMap           ResourceType = "MindMap"
	ResourceTypeGradientQuiz      ResourceType = "Gradient_Quiz"
	ResourceTypeSimulationCode    ResourceType = "Simulation_Code"
	ResourceTypeExtensionMaterial ResourceType = "Extension_Material"
)

// ResponsesLiteRequestV1 Internal provider-neutral request, translated by approved adapters.
type ResponsesLiteRequestV1 struct {
	SchemaVersion   string                 `json:"schema_version"`
	RequestId       UUID                   `json:"request_id"`
	ProviderAlias   string                 `json:"provider_alias"`
	ModelAlias      string                 `json:"model_alias"`
	Instructions    []map[string]any       `json:"instructions"`
	Tools           []LiteToolDefinitionV1 `json:"tools"`
	InputSegments   []map[string]any       `json:"input_segments"`
	ResponseSchema  map[string]any         `json:"response_schema"`
	Temperature     float64                `json:"temperature"`
	MaxOutputTokens int64                  `json:"max_output_tokens"`
	TimeoutMs       int64                  `json:"timeout_ms"`
}

type SSEChunkV1 struct {
	// Topic 3 internal streaming fragment version.
	SchemaVersion string `json:"schema_version"`
	// Generation stream identity.
	StreamId UUID `json:"stream_id"`
	// Unique fragment identity for idempotency.
	FragmentId UUID `json:"fragment_id"`
	// Logical candidate identity.
	CandidateId UUID `json:"candidate_id"`
	// Exact candidate version.
	CandidateVersion int64 `json:"candidate_version"`
	// Block identity for block-scoped fragments.
	BlockId *string `json:"block_id,omitempty"`
	// Start, delta, end, or complete snapshot fragment.
	FragmentType StreamFragmentType `json:"fragment_type"`
	// Zero-based fragment order within candidate/block partition.
	ChunkIndex int64 `json:"chunk_index"`
	// True only for the final fragment in the current partition.
	IsFinal bool `json:"is_final"`
	// Encoding of the fragment data field.
	DataEncoding string `json:"data_encoding"`
	// Fragment body; unverified content remains staged.
	Data string `json:"data"`
	// SHA-256 of the exact UTF-8 fragment bytes.
	DataSha256 string `json:"data_sha256"`
	// UTC fragment creation time from the SSE collection layer.
	EmittedAt DateTime `json:"emitted_at"`
}

type SourceAgent string

const (
	SourceAgentLecturer    SourceAgent = "Lecturer"
	SourceAgentMindMap     SourceAgent = "MindMap"
	SourceAgentTester      SourceAgent = "Tester"
	SourceAgentCodeSandbox SourceAgent = "CodeSandbox"
	SourceAgentExtension   SourceAgent = "Extension"
)

type SourceSnapshotRefV1 struct {
	SchemaVersion         string                        `json:"schema_version"`
	SourceEnvelopeId      UUID                          `json:"source_envelope_id"`
	SourceEnvelopeVersion string                        `json:"source_envelope_version"`
	SourceEnvelopeSha256  string                        `json:"source_envelope_sha256"`
	BlueprintId           UUID                          `json:"blueprint_id"`
	BlueprintVersion      string                        `json:"blueprint_version"`
	BlueprintSha256       string                        `json:"blueprint_sha256"`
	CandidateId           UUID                          `json:"candidate_id"`
	CandidateVersion      int64                         `json:"candidate_version"`
	CandidateSha256       string                        `json:"candidate_sha256"`
	SourceAgent           SourceAgent                   `json:"source_agent"`
	ResourceType          ResourceType                  `json:"resource_type"`
	FullSnapshot          ArtifactObjectRefV1           `json:"full_snapshot"`
	BlockManifest         []BlockSnapshotManifestItemV1 `json:"block_manifest"`
}

type StreamFragmentType string

const (
	StreamFragmentTypeSTART    StreamFragmentType = "START"
	StreamFragmentTypeDELTA    StreamFragmentType = "DELTA"
	StreamFragmentTypeEND      StreamFragmentType = "END"
	StreamFragmentTypeSNAPSHOT StreamFragmentType = "SNAPSHOT"
)

type TextbookMappingType string

const (
	TextbookMappingTypePRIMARY    TextbookMappingType = "PRIMARY"
	TextbookMappingTypeSUPPORTING TextbookMappingType = "SUPPORTING"
	TextbookMappingTypeEXAMPLE    TextbookMappingType = "EXAMPLE"
	TextbookMappingTypeEXERCISE   TextbookMappingType = "EXERCISE"
)

type Topic1ApiEnvelopeV1 struct {
	SchemaVersion *string        `json:"schema_version,omitempty"`
	RequestId     UUID           `json:"request_id"`
	TraceId       string         `json:"trace_id"`
	Data          map[string]any `json:"data"`
}

type Topic1CourseV1 struct {
	SchemaVersion    *string                `json:"schema_version,omitempty"`
	CourseId         string                 `json:"course_id"`
	Revision         int64                  `json:"revision"`
	CourseCode       string                 `json:"course_code"`
	Title            string                 `json:"title"`
	Description      string                 `json:"description"`
	Locale           *string                `json:"locale,omitempty"`
	AcademicLevel    *string                `json:"academic_level,omitempty"`
	CreditHours      float64                `json:"credit_hours"`
	Status           CourseStatus           `json:"status"`
	AuthoritySources []AuthoritySourceRefV1 `json:"authority_sources,omitempty"`
	CreatedAt        DateTime               `json:"created_at"`
	UpdatedAt        DateTime               `json:"updated_at"`
}

type Topic1GoldenQuestionV1 struct {
	SchemaVersion    *string                `json:"schema_version,omitempty"`
	QuestionId       string                 `json:"question_id"`
	PrimaryKpId      string                 `json:"primary_kp_id"`
	RelatedKpIds     []string               `json:"related_kp_ids,omitempty"`
	QuestionType     GoldenQuestionType     `json:"question_type"`
	StemMarkdown     string                 `json:"stem_markdown"`
	AnswerDocument   map[string]any         `json:"answer_document"`
	SolutionMarkdown string                 `json:"solution_markdown"`
	DifficultyLevel  int64                  `json:"difficulty_level"`
	Discrimination   float64                `json:"discrimination"`
	DiagnosticTags   []string               `json:"diagnostic_tags"`
	MisconceptionIds []string               `json:"misconception_ids,omitempty"`
	AuthoritySources []AuthoritySourceRefV1 `json:"authority_sources"`
	Revision         int64                  `json:"revision"`
	CreatedAt        DateTime               `json:"created_at"`
	UpdatedAt        DateTime               `json:"updated_at"`
}

type Topic1GraphContentV1 struct {
	Course           Topic1CourseV1            `json:"course"`
	KnowledgePoints  []Topic1KnowledgePointV1  `json:"knowledge_points"`
	Prerequisites    []Topic1PrerequisiteV1    `json:"prerequisites"`
	Misconceptions   []Topic1MisconceptionV1   `json:"misconceptions,omitempty"`
	Textbooks        []Topic1TextbookV1        `json:"textbooks,omitempty"`
	TextbookSections []Topic1TextbookSectionV1 `json:"textbook_sections,omitempty"`
	TextbookMappings []Topic1TextbookMappingV1 `json:"textbook_mappings,omitempty"`
	GoldenQuestions  []Topic1GoldenQuestionV1  `json:"golden_questions,omitempty"`
}

type Topic1GraphSnapshotV1 struct {
	SchemaVersion          *string              `json:"schema_version,omitempty"`
	SnapshotId             UUID                 `json:"snapshot_id"`
	CourseId               string               `json:"course_id"`
	GraphVersion           int64                `json:"graph_version"`
	ParentSnapshotId       *UUID                `json:"parent_snapshot_id,omitempty"`
	RestoredFromSnapshotId *UUID                `json:"restored_from_snapshot_id,omitempty"`
	Content                Topic1GraphContentV1 `json:"content"`
	ContentSha256          string               `json:"content_sha256"`
	NodeCount              int64                `json:"node_count"`
	EdgeCount              int64                `json:"edge_count"`
	CreatedBySubject       string               `json:"created_by_subject"`
	FrozenAt               DateTime             `json:"frozen_at"`
}

type Topic1ImportBundleV1 struct {
	SchemaVersion         *string              `json:"schema_version,omitempty"`
	ImportId              UUID                 `json:"import_id"`
	ExpectedParentVersion *int64               `json:"expected_parent_version,omitempty"`
	Content               Topic1GraphContentV1 `json:"content"`
	RequestedAt           DateTime             `json:"requested_at"`
}

type Topic1KnowledgePointV1 struct {
	SchemaVersion      *string                `json:"schema_version,omitempty"`
	KpId               string                 `json:"kp_id"`
	CourseId           string                 `json:"course_id"`
	Revision           int64                  `json:"revision"`
	Title              string                 `json:"title"`
	Aliases            []string               `json:"aliases,omitempty"`
	Summary            string                 `json:"summary"`
	LearningObjectives []string               `json:"learning_objectives"`
	Category           string                 `json:"category"`
	DifficultyLevel    int64                  `json:"difficulty_level"`
	DifficultyScore    float64                `json:"difficulty_score"`
	TopologyLevel      int64                  `json:"topology_level"`
	TopologyWeight     float64                `json:"topology_weight"`
	EstimatedMinutes   int64                  `json:"estimated_minutes"`
	FormulaSignatures  []string               `json:"formula_signatures,omitempty"`
	Tags               []string               `json:"tags,omitempty"`
	Status             KnowledgePointStatus   `json:"status"`
	AuthoritySources   []AuthoritySourceRefV1 `json:"authority_sources,omitempty"`
	CreatedAt          DateTime               `json:"created_at"`
	UpdatedAt          DateTime               `json:"updated_at"`
}

type Topic1MisconceptionV1 struct {
	SchemaVersion   *string               `json:"schema_version,omitempty"`
	MisconceptionId string                `json:"misconception_id"`
	KpId            string                `json:"kp_id"`
	Title           string                `json:"title"`
	Description     string                `json:"description"`
	TriggerPattern  string                `json:"trigger_pattern"`
	DiagnosisTags   []string              `json:"diagnosis_tags"`
	RemediationHint string                `json:"remediation_hint"`
	Severity        MisconceptionSeverity `json:"severity"`
	Revision        int64                 `json:"revision"`
	CreatedAt       DateTime              `json:"created_at"`
	UpdatedAt       DateTime              `json:"updated_at"`
}

type Topic1PrerequisiteV1 struct {
	SchemaVersion    *string          `json:"schema_version,omitempty"`
	EdgeId           string           `json:"edge_id"`
	CourseId         string           `json:"course_id"`
	PrerequisiteKpId string           `json:"prerequisite_kp_id"`
	DependentKpId    string           `json:"dependent_kp_id"`
	RelationType     PrerequisiteType `json:"relation_type"`
	Strength         float64          `json:"strength"`
	Rationale        string           `json:"rationale"`
	Revision         int64            `json:"revision"`
	CreatedAt        DateTime         `json:"created_at"`
	UpdatedAt        DateTime         `json:"updated_at"`
}

type Topic1TextbookMappingV1 struct {
	SchemaVersion *string             `json:"schema_version,omitempty"`
	MappingId     string              `json:"mapping_id"`
	KpId          string              `json:"kp_id"`
	SectionId     string              `json:"section_id"`
	MappingType   TextbookMappingType `json:"mapping_type"`
	Coverage      float64             `json:"coverage"`
	Note          *string             `json:"note,omitempty"`
	Revision      int64               `json:"revision"`
	CreatedAt     DateTime            `json:"created_at"`
	UpdatedAt     DateTime            `json:"updated_at"`
}

type Topic1TextbookSectionV1 struct {
	SchemaVersion   *string  `json:"schema_version,omitempty"`
	SectionId       string   `json:"section_id"`
	TextbookId      string   `json:"textbook_id"`
	ParentSectionId *string  `json:"parent_section_id,omitempty"`
	ChapterNumber   string   `json:"chapter_number"`
	Title           string   `json:"title"`
	StartPage       *int64   `json:"start_page,omitempty"`
	EndPage         *int64   `json:"end_page,omitempty"`
	Revision        int64    `json:"revision"`
	CreatedAt       DateTime `json:"created_at"`
	UpdatedAt       DateTime `json:"updated_at"`
}

type Topic1TextbookV1 struct {
	SchemaVersion   *string  `json:"schema_version,omitempty"`
	TextbookId      string   `json:"textbook_id"`
	Title           string   `json:"title"`
	Authors         []string `json:"authors"`
	Publisher       string   `json:"publisher"`
	Edition         string   `json:"edition"`
	Isbn            *string  `json:"isbn,omitempty"`
	PublicationYear int64    `json:"publication_year"`
	AuthorityLevel  int64    `json:"authority_level"`
	Revision        int64    `json:"revision"`
	CreatedAt       DateTime `json:"created_at"`
	UpdatedAt       DateTime `json:"updated_at"`
}

// Topic2AgentContextV1 Single personalization input consumed by Lecturer and Tester agents.
type Topic2AgentContextV1 struct {
	SchemaVersion               *string                    `json:"schema_version,omitempty"`
	LearnerRef                  string                     `json:"learner_ref"`
	CourseId                    string                     `json:"course_id"`
	Profile                     Topic2StudentProfileV1     `json:"profile"`
	MemoryStates                []Topic2MemoryStateV1      `json:"memory_states"`
	LearningPath                Topic2LearningPathRecordV1 `json:"learning_path"`
	PersonalizationPolicyDigest string                     `json:"personalization_policy_digest"`
}

// Topic2BehaviorEventCommandV1 Tokenized learner behavior accepted by the silent profiling pipeline.
type Topic2BehaviorEventCommandV1 struct {
	SchemaVersion     *string                  `json:"schema_version,omitempty"`
	EventId           UUID                     `json:"event_id"`
	SourceEventId     string                   `json:"source_event_id"`
	EventVersion      *int64                   `json:"event_version,omitempty"`
	LearnerRef        string                   `json:"learner_ref"`
	CourseId          string                   `json:"course_id"`
	KpId              *string                  `json:"kp_id,omitempty"`
	SessionId         *UUID                    `json:"session_id,omitempty"`
	EventType         Topic2BehaviorEventType  `json:"event_type"`
	SourceType        Topic2BehaviorSourceType `json:"source_type"`
	DurationSeconds   *float64                 `json:"duration_seconds,omitempty"`
	ResponseLatencyMs *int64                   `json:"response_latency_ms,omitempty"`
	Correctness       *float64                 `json:"correctness,omitempty"`
	Score             *float64                 `json:"score,omitempty"`
	AttemptCount      *int64                   `json:"attempt_count,omitempty"`
	InteractionCount  *int64                   `json:"interaction_count,omitempty"`
	AttentionRatio    *float64                 `json:"attention_ratio,omitempty"`
	MisconceptionIds  []string                 `json:"misconception_ids,omitempty"`
	GoalTags          []string                 `json:"goal_tags,omitempty"`
	Payload           map[string]any           `json:"payload"`
	PayloadSha256     string                   `json:"payload_sha256"`
	OccurredAt        DateTime                 `json:"occurred_at"`
}

type Topic2BehaviorEventType string

const (
	Topic2BehaviorEventTypeANSWERSUBMITTED Topic2BehaviorEventType = "ANSWER_SUBMITTED"
	Topic2BehaviorEventTypeRESOURCEVIEWED  Topic2BehaviorEventType = "RESOURCE_VIEWED"
	Topic2BehaviorEventTypeSIMULATIONRUN   Topic2BehaviorEventType = "SIMULATION_RUN"
	Topic2BehaviorEventTypeREVIEWCOMPLETED Topic2BehaviorEventType = "REVIEW_COMPLETED"
	Topic2BehaviorEventTypeCODEEXECUTED    Topic2BehaviorEventType = "CODE_EXECUTED"
	Topic2BehaviorEventTypeSESSIONFOCUSED  Topic2BehaviorEventType = "SESSION_FOCUSED"
	Topic2BehaviorEventTypeGOALSELECTED    Topic2BehaviorEventType = "GOAL_SELECTED"
)

type Topic2BehaviorSourceType string

const (
	Topic2BehaviorSourceTypeLEARNERUI   Topic2BehaviorSourceType = "LEARNER_UI"
	Topic2BehaviorSourceTypeLECTURER    Topic2BehaviorSourceType = "LECTURER"
	Topic2BehaviorSourceTypeMINDMAP     Topic2BehaviorSourceType = "MINDMAP"
	Topic2BehaviorSourceTypeTESTER      Topic2BehaviorSourceType = "TESTER"
	Topic2BehaviorSourceTypeCODESANDBOX Topic2BehaviorSourceType = "CODE_SANDBOX"
	Topic2BehaviorSourceTypeEXTENSION   Topic2BehaviorSourceType = "EXTENSION"
	Topic2BehaviorSourceTypeSYSTEM      Topic2BehaviorSourceType = "SYSTEM"
)

// Topic2LearningBehaviorEventV1 Immutable persisted behavior event with audit provenance.
type Topic2LearningBehaviorEventV1 struct {
	SchemaVersion     *string                  `json:"schema_version,omitempty"`
	EventId           UUID                     `json:"event_id"`
	SourceEventId     string                   `json:"source_event_id"`
	EventVersion      *int64                   `json:"event_version,omitempty"`
	LearnerRef        string                   `json:"learner_ref"`
	CourseId          string                   `json:"course_id"`
	KpId              *string                  `json:"kp_id,omitempty"`
	SessionId         *UUID                    `json:"session_id,omitempty"`
	EventType         Topic2BehaviorEventType  `json:"event_type"`
	SourceType        Topic2BehaviorSourceType `json:"source_type"`
	DurationSeconds   *float64                 `json:"duration_seconds,omitempty"`
	ResponseLatencyMs *int64                   `json:"response_latency_ms,omitempty"`
	Correctness       *float64                 `json:"correctness,omitempty"`
	Score             *float64                 `json:"score,omitempty"`
	AttemptCount      *int64                   `json:"attempt_count,omitempty"`
	InteractionCount  *int64                   `json:"interaction_count,omitempty"`
	AttentionRatio    *float64                 `json:"attention_ratio,omitempty"`
	MisconceptionIds  []string                 `json:"misconception_ids,omitempty"`
	GoalTags          []string                 `json:"goal_tags,omitempty"`
	Payload           map[string]any           `json:"payload"`
	PayloadSha256     string                   `json:"payload_sha256"`
	OccurredAt        DateTime                 `json:"occurred_at"`
	ReceivedAt        DateTime                 `json:"received_at"`
	AuditEventId      UUID                     `json:"audit_event_id"`
	CreatedAt         DateTime                 `json:"created_at"`
}

// Topic2LearningPathRecordV1 Persisted path snapshot, its change explanation, and audit provenance.
type Topic2LearningPathRecordV1 struct {
	SchemaVersion    *string                      `json:"schema_version,omitempty"`
	Snapshot         Topic2LearningPathSnapshotV1 `json:"snapshot"`
	Change           Topic2PathChangeV1           `json:"change"`
	AuditEventId     UUID                         `json:"audit_event_id"`
	CreatedBySubject string                       `json:"created_by_subject"`
	CreatedAt        DateTime                     `json:"created_at"`
}

// Topic2LearningPathSnapshotV1 Immutable path snapshot bound to exact Topic 1 graph and profile versions.
type Topic2LearningPathSnapshotV1 struct {
	SchemaVersion         *string            `json:"schema_version,omitempty"`
	PathSnapshotId        UUID               `json:"path_snapshot_id"`
	LearnerRef            string             `json:"learner_ref"`
	CourseId              string             `json:"course_id"`
	PathVersion           int64              `json:"path_version"`
	ParentPathSnapshotId  *UUID              `json:"parent_path_snapshot_id,omitempty"`
	Topic1GraphSnapshotId UUID               `json:"topic1_graph_snapshot_id"`
	Topic1GraphVersion    int64              `json:"topic1_graph_version"`
	ProfileId             UUID               `json:"profile_id"`
	PlanType              Topic2PathPlanType `json:"plan_type"`
	TriggerReason         string             `json:"trigger_reason"`
	TargetGoal            string             `json:"target_goal"`
	PolicyVersion         string             `json:"policy_version"`
	PathDocument          map[string]any     `json:"path_document"`
	DecisionDocument      map[string]any     `json:"decision_document"`
	NodeCount             int64              `json:"node_count"`
	EstimatedMinutes      int64              `json:"estimated_minutes"`
	ManualOverride        bool               `json:"manual_override"`
	ContentSha256         string             `json:"content_sha256"`
	FrozenAt              DateTime           `json:"frozen_at"`
}

type Topic2LearningTier string

const (
	Topic2LearningTierFOUNDATION    Topic2LearningTier = "FOUNDATION"
	Topic2LearningTierREINFORCEMENT Topic2LearningTier = "REINFORCEMENT"
	Topic2LearningTierEXTENSION     Topic2LearningTier = "EXTENSION"
)

type Topic2MemoryRiskLevel string

const (
	Topic2MemoryRiskLevelLOW      Topic2MemoryRiskLevel = "LOW"
	Topic2MemoryRiskLevelMEDIUM   Topic2MemoryRiskLevel = "MEDIUM"
	Topic2MemoryRiskLevelHIGH     Topic2MemoryRiskLevel = "HIGH"
	Topic2MemoryRiskLevelCRITICAL Topic2MemoryRiskLevel = "CRITICAL"
)

// Topic2MemoryStateV1 Versioned exponential-forgetting state for one Topic 1 knowledge point.
type Topic2MemoryStateV1 struct {
	SchemaVersion          *string               `json:"schema_version,omitempty"`
	MemoryStateId          UUID                  `json:"memory_state_id"`
	LearnerRef             string                `json:"learner_ref"`
	CourseId               string                `json:"course_id"`
	KpId                   string                `json:"kp_id"`
	StateVersion           int64                 `json:"state_version"`
	ParentMemoryStateId    *UUID                 `json:"parent_memory_state_id,omitempty"`
	ModelVersion           string                `json:"model_version"`
	StabilityDays          float64               `json:"stability_days"`
	EffectiveStabilityDays float64               `json:"effective_stability_days"`
	ElapsedDays            float64               `json:"elapsed_days"`
	Retrievability         float64               `json:"retrievability"`
	ForgettingRate         float64               `json:"forgetting_rate"`
	DifficultyFactor       float64               `json:"difficulty_factor"`
	ReviewGain             float64               `json:"review_gain"`
	ReviewCount            int64                 `json:"review_count"`
	LapseCount             int64                 `json:"lapse_count"`
	LastReviewedAt         *DateTime             `json:"last_reviewed_at,omitempty"`
	LastActivityAt         DateTime              `json:"last_activity_at"`
	NextReviewAt           DateTime              `json:"next_review_at"`
	RiskLevel              Topic2MemoryRiskLevel `json:"risk_level"`
	ModelParameters        map[string]any        `json:"model_parameters"`
	ContentSha256          string                `json:"content_sha256"`
	ComputedAt             DateTime              `json:"computed_at"`
	AuditEventId           UUID                  `json:"audit_event_id"`
	CreatedAt              DateTime              `json:"created_at"`
}

// Topic2OperationCommandV1 Replay-stable command identity for profile, memory, or path generation.
type Topic2OperationCommandV1 struct {
	SchemaVersion *string  `json:"schema_version,omitempty"`
	OperationId   UUID     `json:"operation_id"`
	RequestedAt   DateTime `json:"requested_at"`
}

type Topic2PathChangeType string

const (
	Topic2PathChangeTypeINITIALIZED      Topic2PathChangeType = "INITIALIZED"
	Topic2PathChangeTypeMEMORYRISK       Topic2PathChangeType = "MEMORY_RISK"
	Topic2PathChangeTypeMASTERYDEFICIT   Topic2PathChangeType = "MASTERY_DEFICIT"
	Topic2PathChangeTypeMISCONCEPTION    Topic2PathChangeType = "MISCONCEPTION"
	Topic2PathChangeTypeGOALCHANGED      Topic2PathChangeType = "GOAL_CHANGED"
	Topic2PathChangeTypeMANUALOVERRIDE   Topic2PathChangeType = "MANUAL_OVERRIDE"
	Topic2PathChangeTypeTOPOLOGYREPAIRED Topic2PathChangeType = "TOPOLOGY_REPAIRED"
	Topic2PathChangeTypeRESTORED         Topic2PathChangeType = "RESTORED"
)

// Topic2PathChangeV1 Immutable delta explaining why a new learning path version was created.
type Topic2PathChangeV1 struct {
	SchemaVersion      *string              `json:"schema_version,omitempty"`
	ChangeId           UUID                 `json:"change_id"`
	LearnerRef         string               `json:"learner_ref"`
	CourseId           string               `json:"course_id"`
	FromPathSnapshotId *UUID                `json:"from_path_snapshot_id,omitempty"`
	ToPathSnapshotId   UUID                 `json:"to_path_snapshot_id"`
	ChangeType         Topic2PathChangeType `json:"change_type"`
	Reason             string               `json:"reason"`
	PolicyVersion      string               `json:"policy_version"`
	ChangeDocument     map[string]any       `json:"change_document"`
	OccurredAt         DateTime             `json:"occurred_at"`
}

// Topic2PathGenerateCommandV1 Replay-stable initial or replanned learning-path command.
type Topic2PathGenerateCommandV1 struct {
	SchemaVersion *string               `json:"schema_version,omitempty"`
	OperationId   UUID                  `json:"operation_id"`
	RequestedAt   DateTime              `json:"requested_at"`
	TargetGoal    string                `json:"target_goal"`
	TargetKpIds   []string              `json:"target_kp_ids,omitempty"`
	ManualOrder   []string              `json:"manual_order,omitempty"`
	ChangeType    *Topic2PathChangeType `json:"change_type,omitempty"`
	TriggerReason *string               `json:"trigger_reason,omitempty"`
}

// Topic2PathNodeV1 One stable ordered learning node with explanation and tier assignment.
type Topic2PathNodeV1 struct {
	SchemaVersion     *string                     `json:"schema_version,omitempty"`
	Order             int64                       `json:"order"`
	KpId              string                      `json:"kp_id"`
	Title             string                      `json:"title"`
	Tier              Topic2LearningTier          `json:"tier"`
	PriorityScore     float64                     `json:"priority_score"`
	ScoreComponents   Topic2PathScoreComponentsV1 `json:"score_components"`
	PrerequisiteKpIds []string                    `json:"prerequisite_kp_ids,omitempty"`
	EstimatedMinutes  int64                       `json:"estimated_minutes"`
	RationaleCodes    []string                    `json:"rationale_codes"`
}

type Topic2PathPlanType string

const (
	Topic2PathPlanTypeINITIAL        Topic2PathPlanType = "INITIAL"
	Topic2PathPlanTypeREPLANNED      Topic2PathPlanType = "REPLANNED"
	Topic2PathPlanTypeMANUALOVERRIDE Topic2PathPlanType = "MANUAL_OVERRIDE"
	Topic2PathPlanTypeRESTORED       Topic2PathPlanType = "RESTORED"
)

// Topic2PathScoreComponentsV1 Auditable weighted components used for one path-node decision.
type Topic2PathScoreComponentsV1 struct {
	MasteryDeficit        float64 `json:"mastery_deficit"`
	MemoryRisk            float64 `json:"memory_risk"`
	MisconceptionSeverity float64 `json:"misconception_severity"`
	GoalAlignment         float64 `json:"goal_alignment"`
	TopologyWeight        float64 `json:"topology_weight"`
	DifficultyPaceFit     float64 `json:"difficulty_pace_fit"`
	PrerequisiteReadiness float64 `json:"prerequisite_readiness"`
	Total                 float64 `json:"total"`
}

type Topic2ProfileDimension string

const (
	Topic2ProfileDimensionKNOWLEDGEMASTERY          Topic2ProfileDimension = "KNOWLEDGE_MASTERY"
	Topic2ProfileDimensionPROBLEMSOLVINGPROFICIENCY Topic2ProfileDimension = "PROBLEM_SOLVING_PROFICIENCY"
	Topic2ProfileDimensionMISCONCEPTIONPREFERENCE   Topic2ProfileDimension = "MISCONCEPTION_PREFERENCE"
	Topic2ProfileDimensionLEARNINGPACE              Topic2ProfileDimension = "LEARNING_PACE"
	Topic2ProfileDimensionFORGETTINGRATE            Topic2ProfileDimension = "FORGETTING_RATE"
	Topic2ProfileDimensionLEARNINGGOALTENDENCY      Topic2ProfileDimension = "LEARNING_GOAL_TENDENCY"
)

// Topic2ProfileFeatureV1 Evidence-backed feature supporting one six-dimensional profile snapshot.
type Topic2ProfileFeatureV1 struct {
	SchemaVersion   *string                `json:"schema_version,omitempty"`
	FeatureId       UUID                   `json:"feature_id"`
	Dimension       Topic2ProfileDimension `json:"dimension"`
	FeatureKey      string                 `json:"feature_key"`
	ValueDocument   map[string]any         `json:"value_document"`
	NormalizedScore float64                `json:"normalized_score"`
	Confidence      float64                `json:"confidence"`
	EvidenceCount   int64                  `json:"evidence_count"`
	SourceEventIds  []string               `json:"source_event_ids,omitempty"`
	ComputedAt      DateTime               `json:"computed_at"`
}

// Topic2StudentProfileV1 Immutable profile aggregate, full evidence features, and audit binding.
type Topic2StudentProfileV1 struct {
	SchemaVersion             *string                  `json:"schema_version,omitempty"`
	ProfileId                 UUID                     `json:"profile_id"`
	LearnerRef                string                   `json:"learner_ref"`
	CourseId                  string                   `json:"course_id"`
	ProfileVersion            int64                    `json:"profile_version"`
	ParentProfileId           *UUID                    `json:"parent_profile_id,omitempty"`
	PolicyVersion             string                   `json:"policy_version"`
	KnowledgeMastery          float64                  `json:"knowledge_mastery"`
	ProblemSolvingProficiency float64                  `json:"problem_solving_proficiency"`
	MisconceptionPreference   float64                  `json:"misconception_preference"`
	LearningPace              float64                  `json:"learning_pace"`
	ForgettingRate            float64                  `json:"forgetting_rate"`
	LearningGoalTendency      float64                  `json:"learning_goal_tendency"`
	ConfidenceScore           float64                  `json:"confidence_score"`
	ActivityCount             int64                    `json:"activity_count"`
	LastEventAt               *DateTime                `json:"last_event_at,omitempty"`
	SourceWindowStart         *DateTime                `json:"source_window_start,omitempty"`
	SourceWindowEnd           *DateTime                `json:"source_window_end,omitempty"`
	ProfileDocument           map[string]any           `json:"profile_document"`
	ContentSha256             string                   `json:"content_sha256"`
	FrozenAt                  DateTime                 `json:"frozen_at"`
	Features                  []Topic2ProfileFeatureV1 `json:"features"`
	AuditEventId              UUID                     `json:"audit_event_id"`
	CreatedBySubject          string                   `json:"created_by_subject"`
	CreatedAt                 DateTime                 `json:"created_at"`
}

type Topic3EnvelopeV1 struct {
	// Frozen public Envelope wire version.
	SchemaVersion *string `json:"schema_version,omitempty"`
	// Globally unique envelope identity generated at message creation.
	EnvelopeId UUID `json:"envelope_id"`
	// Stable event name from the Topic 3 event catalog.
	EventType string `json:"event_type"`
	// Command, event, result, or standardized error receipt.
	MessageKind MessageKind `json:"message_kind"`
	// Tenant boundary sourced only from authenticated server context.
	TenantId string `json:"tenant_id"`
	// Learning-session identity from the frozen Topic 1/2 session model.
	SessionId UUID `json:"session_id"`
	// Tokenized user or service subject reference; never raw PII.
	SubjectRef string `json:"subject_ref"`
	// Root workflow correlation identity preserved across agents.
	CorrelationId UUID `json:"correlation_id"`
	// Envelope identity that directly caused this message.
	CausationId *UUID `json:"causation_id,omitempty"`
	// Monotonic sequence inside the partition key, assigned by the producer.
	Sequence int64 `json:"sequence"`
	// Ordering partition, normally tenant/session/candidate identity.
	PartitionKey string `json:"partition_key"`
	// Producing agent/service provenance supplied by runtime infrastructure.
	Producer ProducerMetadataV1 `json:"producer"`
	// At-least-once delivery, retry, priority, and expiry metadata.
	Delivery DeliveryMetadataV1 `json:"delivery"`
	// Optional blueprint/candidate/block identity for resource messages.
	Resource *ResourceMetadataV1 `json:"resource,omitempty"`
	// Distributed trace identity generated or propagated by infrastructure.
	TraceId string `json:"trace_id"`
	// Current trace span identity when tracing is enabled.
	SpanId *string `json:"span_id,omitempty"`
	// UTC message creation time from the producing service clock.
	CreatedAt DateTime `json:"created_at"`
	// Standard error receipt, required only when message_kind is ERROR.
	Error *ErrorReceiptV1 `json:"error,omitempty"`
	// Agent-specific versioned payload; validated by the owning payload schema.
	Payload map[string]any `json:"payload,omitempty"`
}

type VerificationAcceptedPayloadV1 struct {
	SchemaVersion          string                `json:"schema_version"`
	VerificationId         UUID                  `json:"verification_id"`
	IdempotencyKey         string                `json:"idempotency_key"`
	State                  string                `json:"state"`
	StateVersion           int64                 `json:"state_version"`
	Binding                VerificationBindingV1 `json:"binding"`
	AcceptedAt             DateTime              `json:"accepted_at"`
	DeadlineAt             DateTime              `json:"deadline_at"`
	SourceCandidateId      UUID                  `json:"source_candidate_id"`
	SourceCandidateVersion int64                 `json:"source_candidate_version"`
	SourceCandidateSha256  string                `json:"source_candidate_sha256"`
	EstimatedProfile       VerificationProfile   `json:"estimated_profile"`
}

type VerificationBindingV1 struct {
	SchemaVersion                string `json:"schema_version"`
	StateMachineVersion          string `json:"state_machine_version"`
	VerifierBuildVersion         string `json:"verifier_build_version"`
	PolicyVersion                string `json:"policy_version"`
	PromptBundleVersion          string `json:"prompt_bundle_version"`
	ClaimSchemaVersion           string `json:"claim_schema_version"`
	RetrievalPipelineVersion     string `json:"retrieval_pipeline_version"`
	KnowledgeBaseVersion         string `json:"knowledge_base_version"`
	ToolchainManifestVersion     string `json:"toolchain_manifest_version"`
	ContentSecurityPolicyVersion string `json:"content_security_policy_version"`
	LicensePolicyVersion         string `json:"license_policy_version"`
}

type VerificationContextV1 struct {
	SchemaVersion               string               `json:"schema_version"`
	CourseId                    string               `json:"course_id"`
	CourseVersion               string               `json:"course_version"`
	TargetKpId                  string               `json:"target_kp_id"`
	Locale                      string               `json:"locale"`
	SubjectDomain               string               `json:"subject_domain"`
	ProfileSnapshotRef          *ArtifactObjectRefV1 `json:"profile_snapshot_ref,omitempty"`
	PathDecisionRef             *ArtifactObjectRefV1 `json:"path_decision_ref,omitempty"`
	PersonalizationPolicyDigest string               `json:"personalization_policy_digest"`
}

type VerificationProfile string

const (
	VerificationProfileSTANDARD   VerificationProfile = "STANDARD"
	VerificationProfileSTRICT     VerificationProfile = "STRICT"
	VerificationProfileCODESTRICT VerificationProfile = "CODE_STRICT"
)

type VerificationRequestPayloadV1 struct {
	SchemaVersion            string                `json:"schema_version"`
	VerificationId           UUID                  `json:"verification_id"`
	IdempotencyKey           string                `json:"idempotency_key"`
	Trigger                  VerificationTrigger   `json:"trigger"`
	ParentVerificationId     *UUID                 `json:"parent_verification_id,omitempty"`
	SourceSnapshotRef        SourceSnapshotRefV1   `json:"source_snapshot_ref"`
	Context                  VerificationContextV1 `json:"context"`
	RequestedProfile         VerificationProfile   `json:"requested_profile"`
	RequestedOptionalModules []string              `json:"requested_optional_modules,omitempty"`
	DeadlineAt               DateTime              `json:"deadline_at"`
	RequestedAt              DateTime              `json:"requested_at"`
}

type VerificationState string

const (
	VerificationStateACCEPTED           VerificationState = "ACCEPTED"
	VerificationStateSNAPSHOTVALIDATING VerificationState = "SNAPSHOT_VALIDATING"
	VerificationStateCLAIMEXTRACTING    VerificationState = "CLAIM_EXTRACTING"
	VerificationStateCLAIMSREADY        VerificationState = "CLAIMS_READY"
	VerificationStateMODULEDISPATCHING  VerificationState = "MODULE_DISPATCHING"
	VerificationStateVERIFYING          VerificationState = "VERIFYING"
	VerificationStateAGGREGATING        VerificationState = "AGGREGATING"
	VerificationStateREVISIONPLANNING   VerificationState = "REVISION_PLANNING"
	VerificationStateREVISIONWAITING    VerificationState = "REVISION_WAITING"
	VerificationStateREVERIFYING        VerificationState = "REVERIFYING"
	VerificationStateRELEASEPENDING     VerificationState = "RELEASE_PENDING"
	VerificationStateRELEASED           VerificationState = "RELEASED"
	VerificationStateBLOCKED            VerificationState = "BLOCKED"
	VerificationStateREVIEWREQUIRED     VerificationState = "REVIEW_REQUIRED"
	VerificationStateFAILED             VerificationState = "FAILED"
	VerificationStateEXPIRED            VerificationState = "EXPIRED"
	VerificationStateCANCELLED          VerificationState = "CANCELLED"
)

type VerificationStateChangedPayloadV1 struct {
	SchemaVersion  string             `json:"schema_version"`
	VerificationId UUID               `json:"verification_id"`
	PreviousState  *VerificationState `json:"previous_state"`
	CurrentState   VerificationState  `json:"current_state"`
	StateVersion   int64              `json:"state_version"`
	ReasonCode     string             `json:"reason_code"`
	RevisionRound  int64              `json:"revision_round"`
	ChangedAt      DateTime           `json:"changed_at"`
}

type VerificationTrigger string

const (
	VerificationTriggerINITIALGENERATION         VerificationTrigger = "INITIAL_GENERATION"
	VerificationTriggerREVISIONREVERIFY          VerificationTrigger = "REVISION_REVERIFY"
	VerificationTriggerMANUALREVERIFY            VerificationTrigger = "MANUAL_REVERIFY"
	VerificationTriggerKNOWLEDGEBASEREVALIDATION VerificationTrigger = "KNOWLEDGE_BASE_REVALIDATION"
	VerificationTriggerPOLICYREVALIDATION        VerificationTrigger = "POLICY_REVALIDATION"
)
