// Code generated by tools/export_contracts.py. DO NOT EDIT.

package contracts

type UUID string

type DateTime string

type ArtifactObjectRefV1 struct {
	SchemaVersion    string   `json:"schema_version"`
	StorageNamespace string   `json:"storage_namespace"`
	ObjectKey        string   `json:"object_key"`
	MediaType        string   `json:"media_type"`
	ContentEncoding  string   `json:"content_encoding"`
	ByteSize         int64    `json:"byte_size"`
	Sha256           string   `json:"sha256"`
	CreatedAt        DateTime `json:"created_at"`
}

type BlockSnapshotManifestItemV1 struct {
	BlockId     string `json:"block_id"`
	BlockType   string `json:"block_type"`
	Ordinal     int64  `json:"ordinal"`
	JsonPointer string `json:"json_pointer"`
	Sha256      string `json:"sha256"`
	ByteSize    int64  `json:"byte_size"`
}

type BlockStatus string

const (
	BlockStatusCOMPLETE   BlockStatus = "COMPLETE"
	BlockStatusFAILED     BlockStatus = "FAILED"
	BlockStatusSUPERSEDED BlockStatus = "SUPERSEDED"
)

type BlockType string

const (
	BlockTypeMARKDOWN  BlockType = "MARKDOWN"
	BlockTypeMERMAID   BlockType = "MERMAID"
	BlockTypeQUIZ      BlockType = "QUIZ"
	BlockTypeCODE      BlockType = "CODE"
	BlockTypeEXTENSION BlockType = "EXTENSION"
	BlockTypeMETADATA  BlockType = "METADATA"
)

type BlockV1 struct {
	// Frozen wrapper version shared by all Topic 3 block types.
	SchemaVersion string `json:"schema_version"`
	// Stable block identity generated by the owning agent.
	BlockId string `json:"block_id"`
	// Rendering and validation family for the opaque block content.
	BlockType BlockType `json:"block_type"`
	// Zero-based order inside the candidate; ordinals must be contiguous.
	Ordinal int64 `json:"ordinal"`
	// Optional student-visible title supplied by the owning agent.
	Title *string `json:"title,omitempty"`
	// Owning agent payload schema version for the content object.
	ContentSchemaVersion string `json:"content_schema_version"`
	// Frozen agent-specific content. Infrastructure must not rewrite it.
	Content map[string]any `json:"content"`
	// SHA-256 of canonical content JSON, excluding wrapper metadata.
	ContentSha256 string `json:"content_sha256"`
	// Candidate-local block dependencies used for ordering and validation.
	DependencyBlockIds []string `json:"dependency_block_ids,omitempty"`
	// Generation status of this exact block version.
	Status BlockStatus `json:"status"`
	// UTC block completion time from the owning agent.
	CreatedAt DateTime `json:"created_at"`
}

type CandidateProvenanceV1 struct {
	// Owning Topic 3 generation agent.
	Agent SourceAgent `json:"agent"`
	// Owning agent build version used to generate the candidate.
	AgentBuildVersion string `json:"agent_build_version"`
	// Frozen prompt bundle selected by the blueprint.
	PromptBundleVersion string `json:"prompt_bundle_version"`
	// Approved provider alias or local deterministic producer.
	ProviderAlias string `json:"provider_alias"`
	// Provider request identities retained for audit without credentials.
	ProviderRequestIds []string `json:"provider_request_ids,omitempty"`
}

type CandidateStatus string

const (
	CandidateStatusGENERATING CandidateStatus = "GENERATING"
	CandidateStatusCOMPLETE   CandidateStatus = "COMPLETE"
	CandidateStatusFAILED     CandidateStatus = "FAILED"
	CandidateStatusSUPERSEDED CandidateStatus = "SUPERSEDED"
)

type CandidateV1 struct {
	// Frozen candidate wrapper version.
	SchemaVersion string `json:"schema_version"`
	// Logical candidate identity preserved across revision versions.
	CandidateId UUID `json:"candidate_id"`
	// Monotonically increasing candidate version.
	CandidateVersion int64 `json:"candidate_version"`
	// Previous version when produced by a revision; null for version one.
	ParentCandidateVersion *int64 `json:"parent_candidate_version,omitempty"`
	// Immutable Blueprint identity that authorized generation.
	BlueprintId UUID `json:"blueprint_id"`
	// Exact Blueprint version bound to this candidate.
	BlueprintVersion string `json:"blueprint_version"`
	// Canonical Blueprint hash used to detect drift.
	BlueprintSha256 string `json:"blueprint_sha256"`
	// Resource family owned by the generating agent.
	ResourceType ResourceType `json:"resource_type"`
	// Lifecycle status of this exact candidate version.
	Status CandidateStatus `json:"status"`
	// Ordered immutable blocks produced by the agent.
	Blocks []BlockV1 `json:"blocks"`
	// Agent, prompt, provider, and request provenance.
	Provenance CandidateProvenanceV1 `json:"provenance"`
	// Hash of the frozen Topic 2 personalization input used by generation.
	PersonalizationPolicyDigest string `json:"personalization_policy_digest"`
	// SHA-256 of the canonical candidate excluding this field.
	CandidateSha256 string `json:"candidate_sha256"`
	// UTC completion time of this candidate version.
	CreatedAt DateTime `json:"created_at"`
}

type DeliveryMetadataV1 struct {
	// Delivery guarantee. Consumers must be idempotent.
	Mode *string `json:"mode,omitempty"`
	// Stable deduplication key produced by the message originator.
	IdempotencyKey string `json:"idempotency_key"`
	// Current delivery attempt, starting from one.
	Attempt *int64 `json:"attempt,omitempty"`
	// Maximum delivery attempts allowed by the routing policy.
	MaxAttempts *int64 `json:"max_attempts,omitempty"`
	// Queue priority assigned by the deterministic routing policy.
	Priority *MessagePriority `json:"priority,omitempty"`
	// Earliest UTC time at which the message may be dispatched.
	AvailableAt DateTime `json:"available_at"`
	// UTC expiry after which the message must not be executed.
	ExpiresAt *DateTime `json:"expires_at,omitempty"`
}

type ErrorReceiptV1 struct {
	// Wire version for the standard Topic 3 error receipt.
	SchemaVersion string `json:"schema_version"`
	// Stable machine-readable error code from the shared error catalog.
	ErrorCode string `json:"error_code"`
	// Error ownership category such as CONTRACT, PROVIDER, or TIMEOUT.
	Category string `json:"category"`
	// Operational severity; it does not encode academic correctness.
	Severity ErrorSeverity `json:"severity"`
	// Whether infrastructure policy permits another delivery attempt.
	Retriable bool `json:"retriable"`
	// Redacted message safe for logs and authorized clients.
	SafeMessage string `json:"safe_message"`
	// Restricted artifact reference for diagnostics; never raw secrets.
	DetailsRef map[string]any `json:"details_ref,omitempty"`
	// UTC time at which the error occurred.
	OccurredAt DateTime `json:"occurred_at"`
}

type ErrorSeverity string

const (
	ErrorSeverityWARNING  ErrorSeverity = "WARNING"
	ErrorSeverityERROR    ErrorSeverity = "ERROR"
	ErrorSeverityCRITICAL ErrorSeverity = "CRITICAL"
)

type LiteToolDefinitionV1 struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	InputSchema map[string]any `json:"input_schema"`
}

type MessageKind string

const (
	MessageKindCOMMAND MessageKind = "COMMAND"
	MessageKindEVENT   MessageKind = "EVENT"
	MessageKindRESULT  MessageKind = "RESULT"
	MessageKindERROR   MessageKind = "ERROR"
)

type MessagePriority string

const (
	MessagePriorityCRITICAL MessagePriority = "CRITICAL"
	MessagePriorityHIGH     MessagePriority = "HIGH"
	MessagePriorityNORMAL   MessagePriority = "NORMAL"
	MessagePriorityLOW      MessagePriority = "LOW"
)

type ProducerMetadataV1 struct {
	// Producing Topic 3 agent; null for platform infrastructure events.
	Agent *SourceAgent `json:"agent,omitempty"`
	// Stable producing service name from deployment metadata.
	Service string `json:"service"`
	// Ephemeral process or worker instance identity.
	InstanceId string `json:"instance_id"`
	// Immutable producer build version used for provenance.
	BuildVersion string `json:"build_version"`
}

type ReleaseAuthorizationPayloadV1 struct {
	SchemaVersion    string   `json:"schema_version"`
	AuthorizationId  UUID     `json:"authorization_id"`
	VerificationId   UUID     `json:"verification_id"`
	ReportId         UUID     `json:"report_id"`
	CandidateId      UUID     `json:"candidate_id"`
	CandidateVersion int64    `json:"candidate_version"`
	CandidateSha256  string   `json:"candidate_sha256"`
	ReleaseMode      string   `json:"release_mode"`
	AllowedBlockIds  []string `json:"allowed_block_ids"`
	DisclosureCodes  []string `json:"disclosure_codes,omitempty"`
	ReportSha256     string   `json:"report_sha256"`
	IssuedAt         DateTime `json:"issued_at"`
	ExpiresAt        DateTime `json:"expires_at"`
	OneTimeUse       bool     `json:"one_time_use"`
}

type ResourceMetadataV1 struct {
	// Frozen Topic 3 resource family owning the payload.
	ResourceType ResourceType `json:"resource_type"`
	// Immutable blueprint identity from Topic 3 orchestration.
	BlueprintId UUID `json:"blueprint_id"`
	// Blueprint version bound when generation started.
	BlueprintVersion string `json:"blueprint_version"`
	// Logical candidate identity when the message concerns a candidate.
	CandidateId *UUID `json:"candidate_id,omitempty"`
	// Exact candidate version; latest aliases are prohibited.
	CandidateVersion *int64 `json:"candidate_version,omitempty"`
	// Exact block identity for block-scoped messages.
	BlockId *string `json:"block_id,omitempty"`
}

type ResourceType string

const (
	ResourceTypeLecturerDoc       ResourceType = "Lecturer_Doc"
	ResourceTypeMindMap           ResourceType = "MindMap"
	ResourceTypeGradientQuiz      ResourceType = "Gradient_Quiz"
	ResourceTypeSimulationCode    ResourceType = "Simulation_Code"
	ResourceTypeExtensionMaterial ResourceType = "Extension_Material"
)

// ResponsesLiteRequestV1 Internal provider-neutral request, translated by approved adapters.
type ResponsesLiteRequestV1 struct {
	SchemaVersion   string                 `json:"schema_version"`
	RequestId       UUID                   `json:"request_id"`
	ProviderAlias   string                 `json:"provider_alias"`
	ModelAlias      string                 `json:"model_alias"`
	Instructions    []map[string]any       `json:"instructions"`
	Tools           []LiteToolDefinitionV1 `json:"tools"`
	InputSegments   []map[string]any       `json:"input_segments"`
	ResponseSchema  map[string]any         `json:"response_schema"`
	Temperature     float64                `json:"temperature"`
	MaxOutputTokens int64                  `json:"max_output_tokens"`
	TimeoutMs       int64                  `json:"timeout_ms"`
}

type SSEChunkV1 struct {
	// Topic 3 internal streaming fragment version.
	SchemaVersion string `json:"schema_version"`
	// Generation stream identity.
	StreamId UUID `json:"stream_id"`
	// Unique fragment identity for idempotency.
	FragmentId UUID `json:"fragment_id"`
	// Logical candidate identity.
	CandidateId UUID `json:"candidate_id"`
	// Exact candidate version.
	CandidateVersion int64 `json:"candidate_version"`
	// Block identity for block-scoped fragments.
	BlockId *string `json:"block_id,omitempty"`
	// Start, delta, end, or complete snapshot fragment.
	FragmentType StreamFragmentType `json:"fragment_type"`
	// Zero-based fragment order within candidate/block partition.
	ChunkIndex int64 `json:"chunk_index"`
	// True only for the final fragment in the current partition.
	IsFinal bool `json:"is_final"`
	// Encoding of the fragment data field.
	DataEncoding string `json:"data_encoding"`
	// Fragment body; unverified content remains staged.
	Data string `json:"data"`
	// SHA-256 of the exact UTF-8 fragment bytes.
	DataSha256 string `json:"data_sha256"`
	// UTC fragment creation time from the SSE collection layer.
	EmittedAt DateTime `json:"emitted_at"`
}

type SourceAgent string

const (
	SourceAgentLecturer    SourceAgent = "Lecturer"
	SourceAgentMindMap     SourceAgent = "MindMap"
	SourceAgentTester      SourceAgent = "Tester"
	SourceAgentCodeSandbox SourceAgent = "CodeSandbox"
	SourceAgentExtension   SourceAgent = "Extension"
)

type SourceSnapshotRefV1 struct {
	SchemaVersion         string                        `json:"schema_version"`
	SourceEnvelopeId      UUID                          `json:"source_envelope_id"`
	SourceEnvelopeVersion string                        `json:"source_envelope_version"`
	SourceEnvelopeSha256  string                        `json:"source_envelope_sha256"`
	BlueprintId           UUID                          `json:"blueprint_id"`
	BlueprintVersion      string                        `json:"blueprint_version"`
	BlueprintSha256       string                        `json:"blueprint_sha256"`
	CandidateId           UUID                          `json:"candidate_id"`
	CandidateVersion      int64                         `json:"candidate_version"`
	CandidateSha256       string                        `json:"candidate_sha256"`
	SourceAgent           SourceAgent                   `json:"source_agent"`
	ResourceType          ResourceType                  `json:"resource_type"`
	FullSnapshot          ArtifactObjectRefV1           `json:"full_snapshot"`
	BlockManifest         []BlockSnapshotManifestItemV1 `json:"block_manifest"`
}

type StreamFragmentType string

const (
	StreamFragmentTypeSTART    StreamFragmentType = "START"
	StreamFragmentTypeDELTA    StreamFragmentType = "DELTA"
	StreamFragmentTypeEND      StreamFragmentType = "END"
	StreamFragmentTypeSNAPSHOT StreamFragmentType = "SNAPSHOT"
)

type Topic3EnvelopeV1 struct {
	// Frozen public Envelope wire version.
	SchemaVersion *string `json:"schema_version,omitempty"`
	// Globally unique envelope identity generated at message creation.
	EnvelopeId UUID `json:"envelope_id"`
	// Stable event name from the Topic 3 event catalog.
	EventType string `json:"event_type"`
	// Command, event, result, or standardized error receipt.
	MessageKind MessageKind `json:"message_kind"`
	// Tenant boundary sourced only from authenticated server context.
	TenantId string `json:"tenant_id"`
	// Learning-session identity from the frozen Topic 1/2 session model.
	SessionId UUID `json:"session_id"`
	// Tokenized user or service subject reference; never raw PII.
	SubjectRef string `json:"subject_ref"`
	// Root workflow correlation identity preserved across agents.
	CorrelationId UUID `json:"correlation_id"`
	// Envelope identity that directly caused this message.
	CausationId *UUID `json:"causation_id,omitempty"`
	// Monotonic sequence inside the partition key, assigned by the producer.
	Sequence int64 `json:"sequence"`
	// Ordering partition, normally tenant/session/candidate identity.
	PartitionKey string `json:"partition_key"`
	// Producing agent/service provenance supplied by runtime infrastructure.
	Producer ProducerMetadataV1 `json:"producer"`
	// At-least-once delivery, retry, priority, and expiry metadata.
	Delivery DeliveryMetadataV1 `json:"delivery"`
	// Optional blueprint/candidate/block identity for resource messages.
	Resource *ResourceMetadataV1 `json:"resource,omitempty"`
	// Distributed trace identity generated or propagated by infrastructure.
	TraceId string `json:"trace_id"`
	// Current trace span identity when tracing is enabled.
	SpanId *string `json:"span_id,omitempty"`
	// UTC message creation time from the producing service clock.
	CreatedAt DateTime `json:"created_at"`
	// Standard error receipt, required only when message_kind is ERROR.
	Error *ErrorReceiptV1 `json:"error,omitempty"`
	// Agent-specific versioned payload; validated by the owning payload schema.
	Payload map[string]any `json:"payload,omitempty"`
}

type VerificationAcceptedPayloadV1 struct {
	SchemaVersion          string                `json:"schema_version"`
	VerificationId         UUID                  `json:"verification_id"`
	IdempotencyKey         string                `json:"idempotency_key"`
	State                  string                `json:"state"`
	StateVersion           int64                 `json:"state_version"`
	Binding                VerificationBindingV1 `json:"binding"`
	AcceptedAt             DateTime              `json:"accepted_at"`
	DeadlineAt             DateTime              `json:"deadline_at"`
	SourceCandidateId      UUID                  `json:"source_candidate_id"`
	SourceCandidateVersion int64                 `json:"source_candidate_version"`
	SourceCandidateSha256  string                `json:"source_candidate_sha256"`
	EstimatedProfile       VerificationProfile   `json:"estimated_profile"`
}

type VerificationBindingV1 struct {
	SchemaVersion                string `json:"schema_version"`
	StateMachineVersion          string `json:"state_machine_version"`
	VerifierBuildVersion         string `json:"verifier_build_version"`
	PolicyVersion                string `json:"policy_version"`
	PromptBundleVersion          string `json:"prompt_bundle_version"`
	ClaimSchemaVersion           string `json:"claim_schema_version"`
	RetrievalPipelineVersion     string `json:"retrieval_pipeline_version"`
	KnowledgeBaseVersion         string `json:"knowledge_base_version"`
	ToolchainManifestVersion     string `json:"toolchain_manifest_version"`
	ContentSecurityPolicyVersion string `json:"content_security_policy_version"`
	LicensePolicyVersion         string `json:"license_policy_version"`
}

type VerificationContextV1 struct {
	SchemaVersion               string               `json:"schema_version"`
	CourseId                    string               `json:"course_id"`
	CourseVersion               string               `json:"course_version"`
	TargetKpId                  string               `json:"target_kp_id"`
	Locale                      string               `json:"locale"`
	SubjectDomain               string               `json:"subject_domain"`
	ProfileSnapshotRef          *ArtifactObjectRefV1 `json:"profile_snapshot_ref,omitempty"`
	PathDecisionRef             *ArtifactObjectRefV1 `json:"path_decision_ref,omitempty"`
	PersonalizationPolicyDigest string               `json:"personalization_policy_digest"`
}

type VerificationProfile string

const (
	VerificationProfileSTANDARD   VerificationProfile = "STANDARD"
	VerificationProfileSTRICT     VerificationProfile = "STRICT"
	VerificationProfileCODESTRICT VerificationProfile = "CODE_STRICT"
)

type VerificationRequestPayloadV1 struct {
	SchemaVersion            string                `json:"schema_version"`
	VerificationId           UUID                  `json:"verification_id"`
	IdempotencyKey           string                `json:"idempotency_key"`
	Trigger                  VerificationTrigger   `json:"trigger"`
	ParentVerificationId     *UUID                 `json:"parent_verification_id,omitempty"`
	SourceSnapshotRef        SourceSnapshotRefV1   `json:"source_snapshot_ref"`
	Context                  VerificationContextV1 `json:"context"`
	RequestedProfile         VerificationProfile   `json:"requested_profile"`
	RequestedOptionalModules []string              `json:"requested_optional_modules,omitempty"`
	DeadlineAt               DateTime              `json:"deadline_at"`
	RequestedAt              DateTime              `json:"requested_at"`
}

type VerificationState string

const (
	VerificationStateACCEPTED           VerificationState = "ACCEPTED"
	VerificationStateSNAPSHOTVALIDATING VerificationState = "SNAPSHOT_VALIDATING"
	VerificationStateCLAIMEXTRACTING    VerificationState = "CLAIM_EXTRACTING"
	VerificationStateCLAIMSREADY        VerificationState = "CLAIMS_READY"
	VerificationStateMODULEDISPATCHING  VerificationState = "MODULE_DISPATCHING"
	VerificationStateVERIFYING          VerificationState = "VERIFYING"
	VerificationStateAGGREGATING        VerificationState = "AGGREGATING"
	VerificationStateREVISIONPLANNING   VerificationState = "REVISION_PLANNING"
	VerificationStateREVISIONWAITING    VerificationState = "REVISION_WAITING"
	VerificationStateREVERIFYING        VerificationState = "REVERIFYING"
	VerificationStateRELEASEPENDING     VerificationState = "RELEASE_PENDING"
	VerificationStateRELEASED           VerificationState = "RELEASED"
	VerificationStateBLOCKED            VerificationState = "BLOCKED"
	VerificationStateREVIEWREQUIRED     VerificationState = "REVIEW_REQUIRED"
	VerificationStateFAILED             VerificationState = "FAILED"
	VerificationStateEXPIRED            VerificationState = "EXPIRED"
	VerificationStateCANCELLED          VerificationState = "CANCELLED"
)

type VerificationStateChangedPayloadV1 struct {
	SchemaVersion  string             `json:"schema_version"`
	VerificationId UUID               `json:"verification_id"`
	PreviousState  *VerificationState `json:"previous_state"`
	CurrentState   VerificationState  `json:"current_state"`
	StateVersion   int64              `json:"state_version"`
	ReasonCode     string             `json:"reason_code"`
	RevisionRound  int64              `json:"revision_round"`
	ChangedAt      DateTime           `json:"changed_at"`
}

type VerificationTrigger string

const (
	VerificationTriggerINITIALGENERATION         VerificationTrigger = "INITIAL_GENERATION"
	VerificationTriggerREVISIONREVERIFY          VerificationTrigger = "REVISION_REVERIFY"
	VerificationTriggerMANUALREVERIFY            VerificationTrigger = "MANUAL_REVERIFY"
	VerificationTriggerKNOWLEDGEBASEREVALIDATION VerificationTrigger = "KNOWLEDGE_BASE_REVALIDATION"
	VerificationTriggerPOLICYREVALIDATION        VerificationTrigger = "POLICY_REVALIDATION"
)
