"""create topic 4 verifier control plane

Revision ID: 20260716_0007
Revises: 20260716_0006
Create Date: 2026-07-16 11:04:40.019791
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260716_0007"
down_revision: str | Sequence[str] | None = "20260716_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOPIC4_CONTROL_TABLES = (
    "topic4_verifications",
    "topic4_verification_states",
    "topic4_claims",
    "topic4_claim_risks",
    "topic4_dispatch_plans",
    "topic4_module_runs",
    "topic4_module_results",
    "topic4_claim_verdicts",
    "topic4_aggregation_results",
    "topic4_verification_reports",
    "topic4_human_review_tasks",
    "topic4_human_review_decisions",
)


def _install_tenant_policy(table_name: str) -> None:
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')"
    op.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    )


def _install_append_only_trigger(table_name: str) -> None:
    op.execute(
        sa.text(
            f"CREATE TRIGGER trg_{table_name}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION reject_topic4_history_mutation()"
        )
    )


def _grant_runtime_privileges() -> None:
    all_tables = ", ".join(TOPIC4_CONTROL_TABLES)
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM PUBLIC';
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liyans_app') THEN
                    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM liyans_app';
                    EXECUTE 'GRANT SELECT, INSERT ON TABLE {all_tables} TO liyans_app';
                END IF;
            END
            $$
            """
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic4_verifications",
        sa.Column("verification_record_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("parent_verification_id", sa.UUID(), nullable=True),
        sa.Column("source_candidate_id", sa.UUID(), nullable=False),
        sa.Column("source_candidate_version", sa.Integer(), nullable=False),
        sa.Column("source_candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("requested_profile", sa.String(length=24), nullable=False),
        sa.Column("binding_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("accepted_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(accepted_document) = 'object'",
            name=op.f("ck_topic4_verifications_accepted_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(binding_document) = 'object'",
            name=op.f("ck_topic4_verifications_binding_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(request_document) = 'object'",
            name=op.f("ck_topic4_verifications_request_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_verifications_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "requested_profile IN ('STANDARD', 'STRICT', 'CODE_STRICT')",
            name=op.f("ck_topic4_verifications_requested_profile"),
        ),
        sa.CheckConstraint(
            "source_candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_verifications_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_verifications_trace_id_format"),
        ),
        sa.CheckConstraint(
            "trigger IN ('INITIAL_GENERATION', 'REVISION_REVERIFY', 'MANUAL_REVERIFY', "
            "'KNOWLEDGE_BASE_REVALIDATION', 'POLICY_REVALIDATION')",
            name=op.f("ck_topic4_verifications_trigger"),
        ),
        sa.CheckConstraint(
            "deadline_at > accepted_at",
            name=op.f("ck_topic4_verifications_deadline_after_acceptance"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_verifications_immutable_record")),
        sa.CheckConstraint(
            "source_candidate_version >= 1",
            name=op.f("ck_topic4_verifications_positive_candidate_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_verifications_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_verifications_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f(
                "fk_topic4_verifications_tenant_id_parent_verification_id_topic4_verifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_candidate_id", "source_candidate_version"],
            [
                "topic3_generated_candidates.tenant_id",
                "topic3_generated_candidates.candidate_id",
                "topic3_generated_candidates.candidate_version",
            ],
            name=op.f(
                "fk_topic4_verifications_tenant_id_source_candidate_id_source_candidate_version_topic3_generated_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_verifications_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("verification_record_id", name=op.f("pk_topic4_verifications")),
        sa.UniqueConstraint(
            "tenant_id",
            "idempotency_key",
            name=op.f("uq_topic4_verifications_tenant_id_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            name=op.f("uq_topic4_verifications_tenant_id_verification_id"),
        ),
    )
    op.create_index(
        "ix_topic4_verifications_candidate",
        "topic4_verifications",
        ["tenant_id", "source_candidate_id", "source_candidate_version"],
        unique=False,
    )
    op.create_index(
        "ix_topic4_verifications_deadline",
        "topic4_verifications",
        ["tenant_id", "deadline_at"],
        unique=False,
    )
    op.create_table(
        "topic4_aggregation_results",
        sa.Column("aggregation_record_id", sa.UUID(), nullable=False),
        sa.Column("aggregation_result_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("overall_confidence", sa.Float(), nullable=False),
        sa.Column("unsafe_count", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("result_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('RELEASE', 'RELEASE_WITH_DISCLOSURE', 'REVISE', "
            "'REVIEW_REQUIRED', 'BLOCK')",
            name=op.f("ck_topic4_aggregation_results_decision"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(result_document) = 'object'",
            name=op.f("ck_topic4_aggregation_results_result_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_aggregation_results_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_aggregation_results_trace_id_format"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_aggregation_results_immutable_record")
        ),
        sa.CheckConstraint(
            "overall_confidence BETWEEN 0 AND 1",
            name=op.f("ck_topic4_aggregation_results_confidence_range"),
        ),
        sa.CheckConstraint(
            "unsafe_count >= 0", name=op.f("ck_topic4_aggregation_results_nonnegative_unsafe_count")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_aggregation_results_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_aggregation_results_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f(
                "fk_topic4_aggregation_results_tenant_id_verification_id_topic4_verifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_aggregation_results_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "aggregation_record_id", name=op.f("pk_topic4_aggregation_results")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "aggregation_result_id",
            name=op.f("uq_topic4_aggregation_results_tenant_id_aggregation_result_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "version_cas",
            name=op.f("uq_topic4_aggregation_results_tenant_id_verification_id_version_cas"),
        ),
    )
    op.create_index(
        "ix_topic4_aggregation_verification",
        "topic4_aggregation_results",
        ["tenant_id", "verification_id", "version_cas"],
        unique=False,
    )
    op.create_table(
        "topic4_claims",
        sa.Column("claim_record_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.String(length=128), nullable=False),
        sa.Column("claim_kind", sa.String(length=24), nullable=False),
        sa.Column("claim_subtype", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("claim_sha256", sa.String(length=64), nullable=False),
        sa.Column("claim_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "claim_kind IN ('TEXT', 'FORMULA', 'GRAPH', 'QUIZ', 'CODE', 'EXTENSION')",
            name=op.f("ck_topic4_claims_claim_kind"),
        ),
        sa.CheckConstraint(
            "claim_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_topic4_claims_claim_sha256_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(claim_document) = 'object'", name=op.f("ck_topic4_claims_claim_object")
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_topic4_claims_record_sha256_format")
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'", name=op.f("ck_topic4_claims_trace_id_format")
        ),
        sa.CheckConstraint(
            "candidate_version >= 1", name=op.f("ck_topic4_claims_positive_candidate_version")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_claims_immutable_record")),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_topic4_claims_nonnegative_ordinal")),
        sa.CheckConstraint("version_cas >= 1", name=op.f("ck_topic4_claims_positive_version_cas")),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_claims_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "candidate_id", "candidate_version"],
            [
                "topic3_generated_candidates.tenant_id",
                "topic3_generated_candidates.candidate_id",
                "topic3_generated_candidates.candidate_version",
            ],
            name=op.f(
                "fk_topic4_claims_tenant_id_candidate_id_candidate_version_topic3_generated_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f("fk_topic4_claims_tenant_id_verification_id_topic4_verifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_claims_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("claim_record_id", name=op.f("pk_topic4_claims")),
        sa.UniqueConstraint(
            "tenant_id", "claim_id", name=op.f("uq_topic4_claims_tenant_id_claim_id")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "block_id",
            "ordinal",
            name=op.f("uq_topic4_claims_tenant_id_verification_id_block_id_ordinal"),
        ),
    )
    op.create_index(
        "ix_topic4_claims_verification_kind",
        "topic4_claims",
        ["tenant_id", "verification_id", "claim_kind"],
        unique=False,
    )
    op.create_table(
        "topic4_dispatch_plans",
        sa.Column("dispatch_plan_record_id", sa.UUID(), nullable=False),
        sa.Column("dispatch_plan_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("max_parallelism", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("plan_sha256", sa.String(length=64), nullable=False),
        sa.Column("plan_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(plan_document) = 'object'",
            name=op.f("ck_topic4_dispatch_plans_plan_object"),
        ),
        sa.CheckConstraint(
            "plan_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_dispatch_plans_plan_sha256_format"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_dispatch_plans_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_dispatch_plans_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_dispatch_plans_immutable_record")),
        sa.CheckConstraint(
            "max_parallelism BETWEEN 1 AND 32",
            name=op.f("ck_topic4_dispatch_plans_parallelism_range"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_dispatch_plans_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_dispatch_plans_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f("fk_topic4_dispatch_plans_tenant_id_verification_id_topic4_verifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_dispatch_plans_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("dispatch_plan_record_id", name=op.f("pk_topic4_dispatch_plans")),
        sa.UniqueConstraint(
            "tenant_id",
            "dispatch_plan_id",
            name=op.f("uq_topic4_dispatch_plans_tenant_id_dispatch_plan_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "version_cas",
            name=op.f("uq_topic4_dispatch_plans_tenant_id_verification_id_version_cas"),
        ),
    )
    op.create_index(
        "ix_topic4_dispatch_plans_verification",
        "topic4_dispatch_plans",
        ["tenant_id", "verification_id", "version_cas"],
        unique=False,
    )
    op.create_table(
        "topic4_human_review_tasks",
        sa.Column("review_task_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("review_task_id", sa.UUID(), nullable=False),
        sa.Column("task_version", sa.BigInteger(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("assigned_role", sa.String(length=128), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("task_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(task_document) = 'object'",
            name=op.f("ck_topic4_human_review_tasks_task_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_human_review_tasks_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_topic4_human_review_tasks_risk_level"),
        ),
        sa.CheckConstraint(
            "state IN ('OPEN', 'CLAIMED', 'DECIDED', 'EXPIRED', 'CANCELLED')",
            name=op.f("ck_topic4_human_review_tasks_state"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_human_review_tasks_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_human_review_tasks_immutable_record")),
        sa.CheckConstraint(
            "task_version >= 1", name=op.f("ck_topic4_human_review_tasks_positive_task_version")
        ),
        sa.CheckConstraint(
            "version_cas = task_version",
            name=op.f("ck_topic4_human_review_tasks_cas_matches_task_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_human_review_tasks_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_human_review_tasks_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f(
                "fk_topic4_human_review_tasks_tenant_id_verification_id_topic4_verifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_human_review_tasks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "review_task_snapshot_id", name=op.f("pk_topic4_human_review_tasks")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "review_task_id",
            "task_version",
            name=op.f("uq_topic4_human_review_tasks_tenant_id_review_task_id_task_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "review_task_snapshot_id",
            name=op.f("uq_topic4_human_review_tasks_tenant_id_review_task_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic4_review_tasks_state_due",
        "topic4_human_review_tasks",
        ["tenant_id", "state", "due_at"],
        unique=False,
    )
    op.create_table(
        "topic4_verification_states",
        sa.Column("state_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("previous_state", sa.String(length=32), nullable=True),
        sa.Column("current_state", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("revision_round", sa.Integer(), nullable=False),
        sa.Column("state_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_state IN ('ACCEPTED', 'SNAPSHOT_VALIDATING', 'CLAIM_EXTRACTING', "
            "'CLAIMS_READY', 'MODULE_DISPATCHING', 'VERIFYING', 'AGGREGATING', "
            "'REVISION_PLANNING', 'REVISION_WAITING', 'REVERIFYING', 'RELEASE_PENDING', "
            "'RELEASED', 'BLOCKED', 'REVIEW_REQUIRED', 'FAILED', 'EXPIRED', 'CANCELLED')",
            name=op.f("ck_topic4_verification_states_current_state"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(state_document) = 'object'",
            name=op.f("ck_topic4_verification_states_state_object"),
        ),
        sa.CheckConstraint(
            "previous_state IS NULL OR previous_state IN ('ACCEPTED', "
            "'SNAPSHOT_VALIDATING', 'CLAIM_EXTRACTING', 'CLAIMS_READY', "
            "'MODULE_DISPATCHING', 'VERIFYING', 'AGGREGATING', 'REVISION_PLANNING', "
            "'REVISION_WAITING', 'REVERIFYING', 'RELEASE_PENDING', 'RELEASED', "
            "'BLOCKED', 'REVIEW_REQUIRED', 'FAILED', 'EXPIRED', 'CANCELLED')",
            name=op.f("ck_topic4_verification_states_previous_state"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_verification_states_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_verification_states_trace_id_format"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_verification_states_immutable_record")
        ),
        sa.CheckConstraint(
            "revision_round BETWEEN 0 AND 2",
            name=op.f("ck_topic4_verification_states_revision_round"),
        ),
        sa.CheckConstraint(
            "state_version >= 1", name=op.f("ck_topic4_verification_states_positive_state_version")
        ),
        sa.CheckConstraint(
            "version_cas = state_version",
            name=op.f("ck_topic4_verification_states_cas_matches_state_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_verification_states_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_verification_states_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f(
                "fk_topic4_verification_states_tenant_id_verification_id_topic4_verifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_verification_states_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("state_snapshot_id", name=op.f("pk_topic4_verification_states")),
        sa.UniqueConstraint(
            "tenant_id",
            "state_snapshot_id",
            name=op.f("uq_topic4_verification_states_tenant_id_state_snapshot_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "state_version",
            name=op.f("uq_topic4_verification_states_tenant_id_verification_id_state_version"),
        ),
    )
    op.create_index(
        "ix_topic4_states_current",
        "topic4_verification_states",
        ["tenant_id", "verification_id", "state_version"],
        unique=False,
    )
    op.create_index(
        "ix_topic4_states_state_changed",
        "topic4_verification_states",
        ["tenant_id", "current_state", "changed_at"],
        unique=False,
    )
    op.create_table(
        "topic4_claim_risks",
        sa.Column("risk_record_id", sa.UUID(), nullable=False),
        sa.Column("risk_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("risk_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(risk_document) = 'object'", name=op.f("ck_topic4_claim_risks_risk_object")
        ),
        sa.CheckConstraint(
            "level <> 'CRITICAL' OR score >= 0.75",
            name=op.f("ck_topic4_claim_risks_critical_score"),
        ),
        sa.CheckConstraint(
            "level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_topic4_claim_risks_level"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_claim_risks_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'", name=op.f("ck_topic4_claim_risks_trace_id_format")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_claim_risks_immutable_record")),
        sa.CheckConstraint("score BETWEEN 0 AND 1", name=op.f("ck_topic4_claim_risks_score_range")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_claim_risks_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_claim_risks_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "claim_id"],
            ["topic4_claims.tenant_id", "topic4_claims.claim_id"],
            name=op.f("fk_topic4_claim_risks_tenant_id_claim_id_topic4_claims"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_claim_risks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("risk_record_id", name=op.f("pk_topic4_claim_risks")),
        sa.UniqueConstraint(
            "tenant_id",
            "claim_id",
            "policy_version",
            name=op.f("uq_topic4_claim_risks_tenant_id_claim_id_policy_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id", "risk_id", name=op.f("uq_topic4_claim_risks_tenant_id_risk_id")
        ),
    )
    op.create_index(
        "ix_topic4_claim_risks_level",
        "topic4_claim_risks",
        ["tenant_id", "level", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_claim_verdicts",
        sa.Column("claim_verdict_record_id", sa.UUID(), nullable=False),
        sa.Column("claim_verdict_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("non_waivable", sa.Boolean(), nullable=False),
        sa.Column("verdict_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(verdict_document) = 'object'",
            name=op.f("ck_topic4_claim_verdicts_verdict_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_claim_verdicts_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_claim_verdicts_trace_id_format"),
        ),
        sa.CheckConstraint(
            "verdict IN ('SUPPORTED', 'PARTIALLY_SUPPORTED', 'CONTRADICTED', "
            "'INSUFFICIENT_EVIDENCE', 'UNSAFE', 'NOT_APPLICABLE', 'ERROR')",
            name=op.f("ck_topic4_claim_verdicts_verdict"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_topic4_claim_verdicts_confidence_range")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_claim_verdicts_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_claim_verdicts_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_claim_verdicts_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "claim_id"],
            ["topic4_claims.tenant_id", "topic4_claims.claim_id"],
            name=op.f("fk_topic4_claim_verdicts_tenant_id_claim_id_topic4_claims"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_claim_verdicts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("claim_verdict_record_id", name=op.f("pk_topic4_claim_verdicts")),
        sa.UniqueConstraint(
            "tenant_id",
            "claim_verdict_id",
            name=op.f("uq_topic4_claim_verdicts_tenant_id_claim_verdict_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "claim_id",
            "version_cas",
            name=op.f("uq_topic4_claim_verdicts_tenant_id_verification_id_claim_id_version_cas"),
        ),
    )
    op.create_index(
        "ix_topic4_claim_verdicts_verification",
        "topic4_claim_verdicts",
        ["tenant_id", "verification_id", "verdict"],
        unique=False,
    )
    op.create_table(
        "topic4_human_review_decisions",
        sa.Column("review_decision_record_id", sa.UUID(), nullable=False),
        sa.Column("review_decision_id", sa.UUID(), nullable=False),
        sa.Column("review_task_id", sa.UUID(), nullable=False),
        sa.Column("review_task_version", sa.BigInteger(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reviewer_subject_ref", sa.String(length=256), nullable=False),
        sa.Column("decision_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('APPROVE', 'APPROVE_WITH_DISCLOSURE', 'REVISE', 'BLOCK')",
            name=op.f("ck_topic4_human_review_decisions_decision"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(decision_document) = 'object'",
            name=op.f("ck_topic4_human_review_decisions_decision_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_human_review_decisions_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_human_review_decisions_trace_id_format"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_human_review_decisions_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_human_review_decisions_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_human_review_decisions_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "review_task_id", "review_task_version"],
            [
                "topic4_human_review_tasks.tenant_id",
                "topic4_human_review_tasks.review_task_id",
                "topic4_human_review_tasks.task_version",
            ],
            name=op.f(
                "fk_topic4_human_review_decisions_tenant_id_review_task_id_review_task_version_topic4_human_review_tasks"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_human_review_decisions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "review_decision_record_id", name=op.f("pk_topic4_human_review_decisions")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "review_decision_id",
            name=op.f("uq_topic4_human_review_decisions_tenant_id_review_decision_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "review_task_id",
            "review_task_version",
            name=op.f(
                "uq_topic4_human_review_decisions_tenant_id_review_task_id_review_task_version"
            ),
        ),
    )
    op.create_table(
        "topic4_module_runs",
        sa.Column("module_run_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("module_run_id", sa.UUID(), nullable=False),
        sa.Column("run_version", sa.BigInteger(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("dispatch_plan_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("run_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_module_runs_input_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(run_document) = 'object'", name=op.f("ck_topic4_module_runs_run_object")
        ),
        sa.CheckConstraint(
            "module IN ('C2_RAG', 'C3_ACADEMIC', 'C4_GRAPH', 'C5_QUIZ', 'C6_CODE', "
            "'C7_EXTENSION', 'C9_SECURITY', 'C10_PRIVACY', 'C11_COMPLIANCE')",
            name=op.f("ck_topic4_module_runs_module"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_module_runs_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', "
            "'SKIPPED', 'CANCELLED')",
            name=op.f("ck_topic4_module_runs_state"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'", name=op.f("ck_topic4_module_runs_trace_id_format")
        ),
        sa.CheckConstraint(
            "attempt BETWEEN 0 AND max_attempts", name=op.f("ck_topic4_module_runs_attempt_budget")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_module_runs_immutable_record")),
        sa.CheckConstraint(
            "max_attempts BETWEEN 1 AND 5", name=op.f("ck_topic4_module_runs_max_attempts")
        ),
        sa.CheckConstraint(
            "run_version >= 1", name=op.f("ck_topic4_module_runs_positive_run_version")
        ),
        sa.CheckConstraint(
            "version_cas = run_version", name=op.f("ck_topic4_module_runs_cas_matches_run_version")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_module_runs_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_module_runs_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "claim_id"],
            ["topic4_claims.tenant_id", "topic4_claims.claim_id"],
            name=op.f("fk_topic4_module_runs_tenant_id_claim_id_topic4_claims"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "dispatch_plan_id"],
            ["topic4_dispatch_plans.tenant_id", "topic4_dispatch_plans.dispatch_plan_id"],
            name=op.f("fk_topic4_module_runs_tenant_id_dispatch_plan_id_topic4_dispatch_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_module_runs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("module_run_snapshot_id", name=op.f("pk_topic4_module_runs")),
        sa.UniqueConstraint(
            "tenant_id",
            "module_run_id",
            "run_version",
            name=op.f("uq_topic4_module_runs_tenant_id_module_run_id_run_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "module_run_snapshot_id",
            name=op.f("uq_topic4_module_runs_tenant_id_module_run_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic4_module_runs_claim",
        "topic4_module_runs",
        ["tenant_id", "claim_id", "module", "run_version"],
        unique=False,
    )
    op.create_index(
        "ix_topic4_module_runs_state",
        "topic4_module_runs",
        ["tenant_id", "state", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_verification_reports",
        sa.Column("report_record_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("aggregation_result_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_version", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("report_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("report_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_verification_reports_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "decision IN ('RELEASE', 'RELEASE_WITH_DISCLOSURE', 'REVISE', "
            "'REVIEW_REQUIRED', 'BLOCK')",
            name=op.f("ck_topic4_verification_reports_decision"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(report_document) = 'object'",
            name=op.f("ck_topic4_verification_reports_report_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_verification_reports_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "report_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_verification_reports_report_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_verification_reports_trace_id_format"),
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name=op.f("ck_topic4_verification_reports_positive_candidate_version"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_verification_reports_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_verification_reports_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_verification_reports_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "aggregation_result_id"],
            [
                "topic4_aggregation_results.tenant_id",
                "topic4_aggregation_results.aggregation_result_id",
            ],
            name=op.f(
                "fk_topic4_verification_reports_tenant_id_aggregation_result_id_topic4_aggregation_results"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f(
                "fk_topic4_verification_reports_tenant_id_verification_id_topic4_verifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_verification_reports_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("report_record_id", name=op.f("pk_topic4_verification_reports")),
        sa.UniqueConstraint(
            "tenant_id",
            "report_id",
            name=op.f("uq_topic4_verification_reports_tenant_id_report_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "version_cas",
            name=op.f("uq_topic4_verification_reports_tenant_id_verification_id_version_cas"),
        ),
    )
    op.create_index(
        "ix_topic4_reports_verification",
        "topic4_verification_reports",
        ["tenant_id", "verification_id", "version_cas"],
        unique=False,
    )
    op.create_table(
        "topic4_module_results",
        sa.Column("module_result_record_id", sa.UUID(), nullable=False),
        sa.Column("module_result_id", sa.UUID(), nullable=False),
        sa.Column("module_run_id", sa.UUID(), nullable=False),
        sa.Column("module_run_version", sa.BigInteger(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("result_sha256", sa.String(length=64), nullable=False),
        sa.Column("deterministic", sa.Boolean(), nullable=False),
        sa.Column("result_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(result_document) = 'object'",
            name=op.f("ck_topic4_module_results_result_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_module_results_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "result_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_module_results_result_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_module_results_trace_id_format"),
        ),
        sa.CheckConstraint(
            "verdict IN ('SUPPORTED', 'PARTIALLY_SUPPORTED', 'CONTRADICTED', "
            "'INSUFFICIENT_EVIDENCE', 'UNSAFE', 'NOT_APPLICABLE', 'ERROR')",
            name=op.f("ck_topic4_module_results_verdict"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_topic4_module_results_confidence_range")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_module_results_immutable_record")),
        sa.CheckConstraint(
            "module_run_version >= 1", name=op.f("ck_topic4_module_results_positive_run_version")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_module_results_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_module_results_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "module_run_id", "module_run_version"],
            [
                "topic4_module_runs.tenant_id",
                "topic4_module_runs.module_run_id",
                "topic4_module_runs.run_version",
            ],
            name=op.f(
                "fk_topic4_module_results_tenant_id_module_run_id_module_run_version_topic4_module_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_module_results_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("module_result_record_id", name=op.f("pk_topic4_module_results")),
        sa.UniqueConstraint(
            "tenant_id",
            "module_result_id",
            name=op.f("uq_topic4_module_results_tenant_id_module_result_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "module_run_id",
            "module_run_version",
            name=op.f("uq_topic4_module_results_tenant_id_module_run_id_module_run_version"),
        ),
    )
    op.create_index(
        "ix_topic4_module_results_claim",
        "topic4_module_results",
        ["tenant_id", "claim_id", "created_at"],
        unique=False,
    )
    op.execute(
        sa.text(
            """
            CREATE FUNCTION reject_topic4_history_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION 'Topic 4 immutable history cannot be updated or deleted'
                    USING ERRCODE = '55000';
            END;
            $$
            """
        )
    )
    for table_name in TOPIC4_CONTROL_TABLES:
        _install_tenant_policy(table_name)
        _install_append_only_trigger(table_name)
    _grant_runtime_privileges()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in TOPIC4_CONTROL_TABLES:
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{table_name}_append_only ON {table_name}"))
    op.drop_index("ix_topic4_module_results_claim", table_name="topic4_module_results")
    op.drop_table("topic4_module_results")
    op.drop_index("ix_topic4_reports_verification", table_name="topic4_verification_reports")
    op.drop_table("topic4_verification_reports")
    op.drop_index("ix_topic4_module_runs_state", table_name="topic4_module_runs")
    op.drop_index("ix_topic4_module_runs_claim", table_name="topic4_module_runs")
    op.drop_table("topic4_module_runs")
    op.drop_table("topic4_human_review_decisions")
    op.drop_index("ix_topic4_claim_verdicts_verification", table_name="topic4_claim_verdicts")
    op.drop_table("topic4_claim_verdicts")
    op.drop_index("ix_topic4_claim_risks_level", table_name="topic4_claim_risks")
    op.drop_table("topic4_claim_risks")
    op.drop_index("ix_topic4_states_state_changed", table_name="topic4_verification_states")
    op.drop_index("ix_topic4_states_current", table_name="topic4_verification_states")
    op.drop_table("topic4_verification_states")
    op.drop_index("ix_topic4_review_tasks_state_due", table_name="topic4_human_review_tasks")
    op.drop_table("topic4_human_review_tasks")
    op.drop_index("ix_topic4_dispatch_plans_verification", table_name="topic4_dispatch_plans")
    op.drop_table("topic4_dispatch_plans")
    op.drop_index("ix_topic4_claims_verification_kind", table_name="topic4_claims")
    op.drop_table("topic4_claims")
    op.drop_index("ix_topic4_aggregation_verification", table_name="topic4_aggregation_results")
    op.drop_table("topic4_aggregation_results")
    op.drop_index("ix_topic4_verifications_deadline", table_name="topic4_verifications")
    op.drop_index("ix_topic4_verifications_candidate", table_name="topic4_verifications")
    op.drop_table("topic4_verifications")
    op.execute(sa.text("DROP FUNCTION IF EXISTS reject_topic4_history_mutation"))
    # ### end Alembic commands ###
