"""Create Topic 1 knowledge topology

Revision ID: 20260715_0004
Revises: 20260715_0003
Create Date: 2026-07-15 20:22:34.080729
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260715_0004"
down_revision: str | Sequence[str] | None = "20260715_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOPIC1_TENANT_TABLES = (
    "topic1_courses",
    "topic1_knowledge_points",
    "topic1_prerequisites",
    "topic1_misconceptions",
    "topic1_textbooks",
    "topic1_textbook_sections",
    "topic1_textbook_mappings",
    "topic1_golden_questions",
    "topic1_graph_snapshots",
)


def _install_tenant_policy(table_name: str) -> None:
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')"
    op.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    )


def _grant_runtime_privileges() -> None:
    mutable_tables = ", ".join(TOPIC1_TENANT_TABLES[:-1])
    all_tables = ", ".join(TOPIC1_TENANT_TABLES)
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM PUBLIC';
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liyans_app') THEN
                    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM liyans_app';
                    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE '
                        || 'ON TABLE {mutable_tables} TO liyans_app';
                    EXECUTE 'GRANT SELECT, INSERT ON TABLE topic1_graph_snapshots '
                        || 'TO liyans_app';
                END IF;
            END
            $$
            """
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic1_courses",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("course_code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column(
            "locale", sa.String(length=16), server_default=sa.text("'zh-CN'"), nullable=False
        ),
        sa.Column(
            "academic_level",
            sa.String(length=32),
            server_default=sa.text("'UNDERGRADUATE'"),
            nullable=False,
        ),
        sa.Column("credit_hours", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "authority_sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(authority_sources) = 'array'",
            name=op.f("ck_topic1_courses_authority_sources_array"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')", name=op.f("ck_topic1_courses_status")
        ),
        sa.CheckConstraint(
            "credit_hours >= 0 AND credit_hours <= 256", name=op.f("ck_topic1_courses_credit_hours")
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_topic1_courses_positive_revision")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic1_courses_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "course_id", name=op.f("pk_topic1_courses")),
        sa.UniqueConstraint(
            "tenant_id", "course_code", name=op.f("uq_topic1_courses_tenant_id_course_code")
        ),
    )
    op.create_index(
        "ix_topic1_courses_tenant_status", "topic1_courses", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "topic1_textbooks",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("textbook_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=False),
        sa.Column("edition", sa.String(length=64), nullable=False),
        sa.Column("isbn", sa.String(length=32), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=False),
        sa.Column("authority_level", sa.Integer(), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(authors) = 'array'", name=op.f("ck_topic1_textbooks_authors_array")
        ),
        sa.CheckConstraint(
            "authority_level BETWEEN 1 AND 5", name=op.f("ck_topic1_textbooks_authority_level")
        ),
        sa.CheckConstraint(
            "publication_year BETWEEN 1900 AND 2200",
            name=op.f("ck_topic1_textbooks_publication_year"),
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_topic1_textbooks_positive_revision")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic1_textbooks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "textbook_id", name=op.f("pk_topic1_textbooks")),
        sa.UniqueConstraint("tenant_id", "isbn", name=op.f("uq_topic1_textbooks_tenant_id_isbn")),
    )
    op.create_table(
        "topic1_graph_snapshots",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("graph_version", sa.BigInteger(), nullable=False),
        sa.Column("parent_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("restored_from_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic1_graph_snapshots_content_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(snapshot_document) = 'object'",
            name=op.f("ck_topic1_graph_snapshots_snapshot_document_object"),
        ),
        sa.CheckConstraint(
            "edge_count >= 0", name=op.f("ck_topic1_graph_snapshots_nonnegative_edge_count")
        ),
        sa.CheckConstraint(
            "graph_version >= 1", name=op.f("ck_topic1_graph_snapshots_positive_graph_version")
        ),
        sa.CheckConstraint(
            "node_count >= 0", name=op.f("ck_topic1_graph_snapshots_nonnegative_node_count")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic1_graph_snapshots_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id"],
            ["topic1_courses.tenant_id", "topic1_courses.course_id"],
            name=op.f("fk_topic1_graph_snapshots_tenant_id_course_id_topic1_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_snapshot_id"],
            ["topic1_graph_snapshots.tenant_id", "topic1_graph_snapshots.snapshot_id"],
            name=op.f(
                "fk_topic1_graph_snapshots_tenant_id_parent_snapshot_id_topic1_graph_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "restored_from_snapshot_id"],
            ["topic1_graph_snapshots.tenant_id", "topic1_graph_snapshots.snapshot_id"],
            name=op.f(
                "fk_topic1_graph_snapshots_tenant_id_restored_from_snapshot_id_topic1_graph_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic1_graph_snapshots_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_topic1_graph_snapshots")),
        sa.UniqueConstraint(
            "tenant_id",
            "course_id",
            "graph_version",
            name=op.f("uq_topic1_graph_snapshots_tenant_id_course_id_graph_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id", "snapshot_id", name=op.f("uq_topic1_graph_snapshots_tenant_id_snapshot_id")
        ),
    )
    op.create_index(
        "ix_topic1_graph_snapshots_course_version",
        "topic1_graph_snapshots",
        ["tenant_id", "course_id", "graph_version"],
        unique=False,
    )
    op.create_table(
        "topic1_knowledge_points",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("kp_id", sa.String(length=120), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=4000), nullable=False),
        sa.Column("learning_objectives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("difficulty_level", sa.Integer(), nullable=False),
        sa.Column("difficulty_score", sa.Float(), nullable=False),
        sa.Column("topology_level", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("topology_weight", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "formula_signatures",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "authority_sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(aliases) = 'array'", name=op.f("ck_topic1_knowledge_points_aliases_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(authority_sources) = 'array'",
            name=op.f("ck_topic1_knowledge_points_authority_sources_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(formula_signatures) = 'array'",
            name=op.f("ck_topic1_knowledge_points_formula_signatures_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(learning_objectives) = 'array'",
            name=op.f("ck_topic1_knowledge_points_learning_objectives_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(tags) = 'array'", name=op.f("ck_topic1_knowledge_points_tags_array")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'DEPRECATED')",
            name=op.f("ck_topic1_knowledge_points_status"),
        ),
        sa.CheckConstraint(
            "difficulty_level BETWEEN 1 AND 5",
            name=op.f("ck_topic1_knowledge_points_difficulty_level"),
        ),
        sa.CheckConstraint(
            "difficulty_score BETWEEN 0 AND 1",
            name=op.f("ck_topic1_knowledge_points_difficulty_score"),
        ),
        sa.CheckConstraint(
            "estimated_minutes BETWEEN 1 AND 2400",
            name=op.f("ck_topic1_knowledge_points_estimated_minutes"),
        ),
        sa.CheckConstraint(
            "revision >= 1", name=op.f("ck_topic1_knowledge_points_positive_revision")
        ),
        sa.CheckConstraint(
            "topology_level >= 0", name=op.f("ck_topic1_knowledge_points_topology_level")
        ),
        sa.CheckConstraint(
            "topology_weight BETWEEN 0 AND 1",
            name=op.f("ck_topic1_knowledge_points_topology_weight"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id"],
            ["topic1_courses.tenant_id", "topic1_courses.course_id"],
            name=op.f("fk_topic1_knowledge_points_tenant_id_course_id_topic1_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "kp_id", name=op.f("pk_topic1_knowledge_points")),
        sa.UniqueConstraint(
            "tenant_id",
            "course_id",
            "kp_id",
            name=op.f("uq_topic1_knowledge_points_tenant_id_course_id_kp_id"),
        ),
    )
    op.create_index(
        "ix_topic1_knowledge_points_course_difficulty",
        "topic1_knowledge_points",
        ["tenant_id", "course_id", "difficulty_level"],
        unique=False,
    )
    op.create_index(
        "ix_topic1_knowledge_points_course_level",
        "topic1_knowledge_points",
        ["tenant_id", "course_id", "topology_level"],
        unique=False,
    )
    op.create_table(
        "topic1_textbook_sections",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("section_id", sa.String(length=128), nullable=False),
        sa.Column("textbook_id", sa.String(length=128), nullable=False),
        sa.Column("parent_section_id", sa.String(length=128), nullable=True),
        sa.Column("chapter_number", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("start_page", sa.Integer(), nullable=True),
        sa.Column("end_page", sa.Integer(), nullable=True),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parent_section_id IS NULL OR parent_section_id <> section_id",
            name=op.f("ck_topic1_textbook_sections_no_self_parent"),
        ),
        sa.CheckConstraint(
            "revision >= 1", name=op.f("ck_topic1_textbook_sections_positive_revision")
        ),
        sa.CheckConstraint(
            "start_page IS NULL OR end_page IS NULL OR end_page >= start_page",
            name=op.f("ck_topic1_textbook_sections_page_range"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_section_id"],
            ["topic1_textbook_sections.tenant_id", "topic1_textbook_sections.section_id"],
            name=op.f(
                "fk_topic1_textbook_sections_tenant_id_parent_section_id_topic1_textbook_sections"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "textbook_id"],
            ["topic1_textbooks.tenant_id", "topic1_textbooks.textbook_id"],
            name=op.f("fk_topic1_textbook_sections_tenant_id_textbook_id_topic1_textbooks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "section_id", name=op.f("pk_topic1_textbook_sections")
        ),
    )
    op.create_index(
        "ix_topic1_textbook_sections_textbook",
        "topic1_textbook_sections",
        ["tenant_id", "textbook_id", "chapter_number"],
        unique=False,
    )
    op.create_table(
        "topic1_golden_questions",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("question_id", sa.String(length=128), nullable=False),
        sa.Column("primary_kp_id", sa.String(length=120), nullable=False),
        sa.Column(
            "related_kp_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("question_type", sa.String(length=32), nullable=False),
        sa.Column("stem_markdown", sa.String(length=20000), nullable=False),
        sa.Column("answer_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("solution_markdown", sa.String(length=30000), nullable=False),
        sa.Column("difficulty_level", sa.Integer(), nullable=False),
        sa.Column("discrimination", sa.Float(), nullable=False),
        sa.Column("diagnostic_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "misconception_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("authority_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(answer_document) = 'object'",
            name=op.f("ck_topic1_golden_questions_answer_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(authority_sources) = 'array'",
            name=op.f("ck_topic1_golden_questions_authority_sources_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(diagnostic_tags) = 'array'",
            name=op.f("ck_topic1_golden_questions_diagnostic_tags_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(misconception_ids) = 'array'",
            name=op.f("ck_topic1_golden_questions_misconception_ids_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(related_kp_ids) = 'array'",
            name=op.f("ck_topic1_golden_questions_related_kp_ids_array"),
        ),
        sa.CheckConstraint(
            "question_type IN ('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'CALCULATION', "
            "'PROOF', 'DESIGN', 'SIMULATION')",
            name=op.f("ck_topic1_golden_questions_question_type"),
        ),
        sa.CheckConstraint(
            "difficulty_level BETWEEN 1 AND 5",
            name=op.f("ck_topic1_golden_questions_difficulty_level"),
        ),
        sa.CheckConstraint(
            "discrimination BETWEEN 0 AND 1", name=op.f("ck_topic1_golden_questions_discrimination")
        ),
        sa.CheckConstraint(
            "revision >= 1", name=op.f("ck_topic1_golden_questions_positive_revision")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "primary_kp_id"],
            ["topic1_knowledge_points.tenant_id", "topic1_knowledge_points.kp_id"],
            name=op.f("fk_topic1_golden_questions_tenant_id_primary_kp_id_topic1_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "question_id", name=op.f("pk_topic1_golden_questions")
        ),
    )
    op.create_index(
        "ix_topic1_golden_questions_kp_difficulty",
        "topic1_golden_questions",
        ["tenant_id", "primary_kp_id", "difficulty_level"],
        unique=False,
    )
    op.create_table(
        "topic1_misconceptions",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("misconception_id", sa.String(length=128), nullable=False),
        sa.Column("kp_id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column("trigger_pattern", sa.String(length=2000), nullable=False),
        sa.Column("diagnosis_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("remediation_hint", sa.String(length=4000), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(diagnosis_tags) = 'array'",
            name=op.f("ck_topic1_misconceptions_diagnosis_tags_array"),
        ),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_topic1_misconceptions_severity"),
        ),
        sa.CheckConstraint(
            "revision >= 1", name=op.f("ck_topic1_misconceptions_positive_revision")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "kp_id"],
            ["topic1_knowledge_points.tenant_id", "topic1_knowledge_points.kp_id"],
            name=op.f("fk_topic1_misconceptions_tenant_id_kp_id_topic1_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "misconception_id", name=op.f("pk_topic1_misconceptions")
        ),
    )
    op.create_index(
        "ix_topic1_misconceptions_kp", "topic1_misconceptions", ["tenant_id", "kp_id"], unique=False
    )
    op.create_table(
        "topic1_prerequisites",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("edge_id", sa.String(length=128), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("prerequisite_kp_id", sa.String(length=120), nullable=False),
        sa.Column("dependent_kp_id", sa.String(length=120), nullable=False),
        sa.Column("relation_type", sa.String(length=16), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("rationale", sa.String(length=2000), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation_type IN ('REQUIRED', 'RECOMMENDED', 'SUPPORTING')",
            name=op.f("ck_topic1_prerequisites_relation_type"),
        ),
        sa.CheckConstraint(
            "prerequisite_kp_id <> dependent_kp_id",
            name=op.f("ck_topic1_prerequisites_no_self_edge"),
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_topic1_prerequisites_positive_revision")),
        sa.CheckConstraint(
            "strength BETWEEN 0 AND 1", name=op.f("ck_topic1_prerequisites_strength")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id", "dependent_kp_id"],
            [
                "topic1_knowledge_points.tenant_id",
                "topic1_knowledge_points.course_id",
                "topic1_knowledge_points.kp_id",
            ],
            name=op.f(
                "fk_topic1_prerequisites_tenant_id_course_id_dependent_kp_id_topic1_knowledge_points"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id", "prerequisite_kp_id"],
            [
                "topic1_knowledge_points.tenant_id",
                "topic1_knowledge_points.course_id",
                "topic1_knowledge_points.kp_id",
            ],
            name=op.f(
                "fk_topic1_prerequisites_tenant_id_course_id_prerequisite_kp_id_topic1_knowledge_points"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "edge_id", name=op.f("pk_topic1_prerequisites")),
        sa.UniqueConstraint(
            "tenant_id",
            "course_id",
            "prerequisite_kp_id",
            "dependent_kp_id",
            "relation_type",
            name=op.f(
                "uq_topic1_prerequisites_tenant_id_course_id_prerequisite_kp_id_dependent_kp_id_relation_type"
            ),
        ),
    )
    op.create_index(
        "ix_topic1_prerequisites_course_dependent",
        "topic1_prerequisites",
        ["tenant_id", "course_id", "dependent_kp_id"],
        unique=False,
    )
    op.create_table(
        "topic1_textbook_mappings",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("mapping_id", sa.String(length=128), nullable=False),
        sa.Column("kp_id", sa.String(length=120), nullable=False),
        sa.Column("section_id", sa.String(length=128), nullable=False),
        sa.Column("mapping_type", sa.String(length=16), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=True),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mapping_type IN ('PRIMARY', 'SUPPORTING', 'EXAMPLE', 'EXERCISE')",
            name=op.f("ck_topic1_textbook_mappings_mapping_type"),
        ),
        sa.CheckConstraint(
            "coverage BETWEEN 0 AND 1", name=op.f("ck_topic1_textbook_mappings_coverage")
        ),
        sa.CheckConstraint(
            "revision >= 1", name=op.f("ck_topic1_textbook_mappings_positive_revision")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "kp_id"],
            ["topic1_knowledge_points.tenant_id", "topic1_knowledge_points.kp_id"],
            name=op.f("fk_topic1_textbook_mappings_tenant_id_kp_id_topic1_knowledge_points"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "section_id"],
            ["topic1_textbook_sections.tenant_id", "topic1_textbook_sections.section_id"],
            name=op.f("fk_topic1_textbook_mappings_tenant_id_section_id_topic1_textbook_sections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "mapping_id", name=op.f("pk_topic1_textbook_mappings")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "kp_id",
            "section_id",
            "mapping_type",
            name=op.f("uq_topic1_textbook_mappings_tenant_id_kp_id_section_id_mapping_type"),
        ),
    )
    op.create_index(
        "ix_topic1_textbook_mappings_kp",
        "topic1_textbook_mappings",
        ["tenant_id", "kp_id"],
        unique=False,
    )
    for table_name in TOPIC1_TENANT_TABLES:
        _install_tenant_policy(table_name)
    op.execute(
        sa.text(
            """
            CREATE FUNCTION reject_topic1_graph_snapshot_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION USING
                    ERRCODE = '55000',
                    MESSAGE = 'topic1_graph_snapshots is append-only';
            END
            $$
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TRIGGER trg_topic1_graph_snapshots_append_only
            BEFORE UPDATE OR DELETE ON topic1_graph_snapshots
            FOR EACH ROW EXECUTE FUNCTION reject_topic1_graph_snapshot_mutation()
            """
        )
    )
    _grant_runtime_privileges()


def downgrade() -> None:
    op.execute(
        sa.text(
            "DROP TRIGGER IF EXISTS trg_topic1_graph_snapshots_append_only "
            "ON topic1_graph_snapshots"
        )
    )
    op.execute(sa.text("DROP FUNCTION IF EXISTS reject_topic1_graph_snapshot_mutation()"))
    op.drop_index("ix_topic1_textbook_mappings_kp", table_name="topic1_textbook_mappings")
    op.drop_table("topic1_textbook_mappings")
    op.drop_index("ix_topic1_prerequisites_course_dependent", table_name="topic1_prerequisites")
    op.drop_table("topic1_prerequisites")
    op.drop_index("ix_topic1_misconceptions_kp", table_name="topic1_misconceptions")
    op.drop_table("topic1_misconceptions")
    op.drop_index("ix_topic1_golden_questions_kp_difficulty", table_name="topic1_golden_questions")
    op.drop_table("topic1_golden_questions")
    op.drop_index("ix_topic1_textbook_sections_textbook", table_name="topic1_textbook_sections")
    op.drop_table("topic1_textbook_sections")
    op.drop_index("ix_topic1_knowledge_points_course_level", table_name="topic1_knowledge_points")
    op.drop_index(
        "ix_topic1_knowledge_points_course_difficulty", table_name="topic1_knowledge_points"
    )
    op.drop_table("topic1_knowledge_points")
    op.drop_index("ix_topic1_graph_snapshots_course_version", table_name="topic1_graph_snapshots")
    op.drop_table("topic1_graph_snapshots")
    op.drop_table("topic1_textbooks")
    op.drop_index("ix_topic1_courses_tenant_status", table_name="topic1_courses")
    op.drop_table("topic1_courses")
