"""create topic 4 knowledge evidence runtime

Revision ID: 20260716_0008
Revises: 20260716_0007
Create Date: 2026-07-16 11:21:38.471254
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260716_0008"
down_revision: str | Sequence[str] | None = "20260716_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOPIC4_KNOWLEDGE_TABLES = (
    "topic4_source_documents",
    "topic4_source_document_versions",
    "topic4_embedding_profiles",
    "topic4_knowledge_base_versions",
    "topic4_knowledge_chunks",
    "topic4_formula_signatures",
    "topic4_index_build_manifests",
    "topic4_knowledge_base_activations",
    "topic4_query_plans",
    "topic4_retrieval_runs",
    "topic4_evidence_refs",
    "topic4_evidence_bundles",
)


def _install_tenant_policy(table_name: str) -> None:
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')"
    op.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    )


def _install_append_only_trigger(table_name: str) -> None:
    op.execute(
        sa.text(
            f"CREATE TRIGGER trg_{table_name}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION reject_topic4_history_mutation()"
        )
    )


def _grant_runtime_privileges() -> None:
    all_tables = ", ".join(TOPIC4_KNOWLEDGE_TABLES)
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM PUBLIC';
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liyans_app') THEN
                    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM liyans_app';
                    EXECUTE 'GRANT SELECT, INSERT ON TABLE {all_tables} TO liyans_app';
                END IF;
            END
            $$
            """
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic4_embedding_profiles",
        sa.Column("embedding_profile_record_id", sa.UUID(), nullable=False),
        sa.Column("embedding_profile_id", sa.UUID(), nullable=False),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("tokenizer_version", sa.String(length=128), nullable=False),
        sa.Column("hash_seed_version", sa.String(length=128), nullable=False),
        sa.Column("signed_hashing", sa.Boolean(), nullable=False),
        sa.Column("network_access", sa.Boolean(), nullable=False),
        sa.Column("profile_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "algorithm = 'HASHED_LEXICAL_2048'",
            name=op.f("ck_topic4_embedding_profiles_local_algorithm"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(profile_document) = 'object'",
            name=op.f("ck_topic4_embedding_profiles_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_embedding_profiles_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_embedding_profiles_trace_id_format"),
        ),
        sa.CheckConstraint(
            "dimension = 2048", name=op.f("ck_topic4_embedding_profiles_fixed_dimension")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_embedding_profiles_immutable_record")),
        sa.CheckConstraint(
            "network_access = false", name=op.f("ck_topic4_embedding_profiles_network_disabled")
        ),
        sa.CheckConstraint(
            "signed_hashing", name=op.f("ck_topic4_embedding_profiles_signed_hashing_required")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_embedding_profiles_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_embedding_profiles_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_embedding_profiles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "embedding_profile_record_id", name=op.f("pk_topic4_embedding_profiles")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "algorithm",
            "tokenizer_version",
            "hash_seed_version",
            name=op.f(
                "uq_topic4_embedding_profiles_tenant_id_algorithm_tokenizer_version_hash_seed_version"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "embedding_profile_id",
            name=op.f("uq_topic4_embedding_profiles_tenant_id_embedding_profile_id"),
        ),
    )
    op.create_table(
        "topic4_source_documents",
        sa.Column("source_document_record_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=2048), nullable=False),
        sa.Column("publisher", sa.String(length=512), nullable=False),
        sa.Column("authority_tier", sa.String(length=32), nullable=False),
        sa.Column("lifecycle", sa.String(length=24), nullable=False),
        sa.Column("license_expression", sa.String(length=256), nullable=False),
        sa.Column("canonical_citation_sha256", sa.String(length=64), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "authority_tier IN ('PRIMARY_STANDARD', 'AUTHORITATIVE_TEXTBOOK', "
            "'PEER_REVIEWED', 'OFFICIAL_DOCUMENTATION', 'CURATED_INTERNAL')",
            name=op.f("ck_topic4_source_documents_authority_tier"),
        ),
        sa.CheckConstraint(
            "canonical_citation_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_source_documents_citation_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(document) = 'object'",
            name=op.f("ck_topic4_source_documents_document_object"),
        ),
        sa.CheckConstraint(
            "lifecycle IN ('DRAFT', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'REVOKED')",
            name=op.f("ck_topic4_source_documents_lifecycle"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_source_documents_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_source_documents_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_source_documents_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_source_documents_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_source_documents_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_source_documents_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "source_document_record_id", name=op.f("pk_topic4_source_documents")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "course_id",
            "canonical_citation_sha256",
            name=op.f("uq_topic4_source_documents_tenant_id_course_id_canonical_citation_sha256"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "source_document_id",
            name=op.f("uq_topic4_source_documents_tenant_id_source_document_id"),
        ),
    )
    op.create_index(
        "ix_topic4_source_documents_course_authority",
        "topic4_source_documents",
        ["tenant_id", "course_id", "authority_tier"],
        unique=False,
    )
    op.create_table(
        "topic4_knowledge_base_versions",
        sa.Column("knowledge_base_version_record_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_version_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("lifecycle", sa.String(length=24), nullable=False),
        sa.Column(
            "source_document_version_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("graph_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("graph_snapshot_version", sa.BigInteger(), nullable=False),
        sa.Column("embedding_profile_id", sa.UUID(), nullable=False),
        sa.Column("version_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(source_document_version_ids) = 'array'",
            name=op.f("ck_topic4_knowledge_base_versions_source_versions_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(version_document) = 'object'",
            name=op.f("ck_topic4_knowledge_base_versions_document_object"),
        ),
        sa.CheckConstraint(
            "lifecycle IN ('DRAFT', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'REVOKED')",
            name=op.f("ck_topic4_knowledge_base_versions_lifecycle"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_knowledge_base_versions_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_knowledge_base_versions_trace_id_format"),
        ),
        sa.CheckConstraint(
            "graph_snapshot_version >= 1",
            name=op.f("ck_topic4_knowledge_base_versions_positive_graph_version"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_knowledge_base_versions_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_knowledge_base_versions_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_knowledge_base_versions_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "embedding_profile_id"],
            [
                "topic4_embedding_profiles.tenant_id",
                "topic4_embedding_profiles.embedding_profile_id",
            ],
            name=op.f(
                "fk_topic4_knowledge_base_versions_tenant_id_embedding_profile_id_topic4_embedding_profiles"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "graph_snapshot_id"],
            ["topic1_graph_snapshots.tenant_id", "topic1_graph_snapshots.snapshot_id"],
            name=op.f(
                "fk_topic4_knowledge_base_versions_tenant_id_graph_snapshot_id_topic1_graph_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_knowledge_base_versions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "knowledge_base_version_record_id", name=op.f("pk_topic4_knowledge_base_versions")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "course_id",
            "version",
            name=op.f("uq_topic4_knowledge_base_versions_tenant_id_course_id_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "knowledge_base_version_id",
            name=op.f("uq_topic4_knowledge_base_versions_tenant_id_knowledge_base_version_id"),
        ),
    )
    op.create_index(
        "ix_topic4_kb_versions_course_created",
        "topic4_knowledge_base_versions",
        ["tenant_id", "course_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_source_document_versions",
        sa.Column("source_document_version_record_id", sa.UUID(), nullable=False),
        sa.Column("source_document_version_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=128), nullable=False),
        sa.Column("published_on", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifecycle", sa.String(length=24), nullable=False),
        sa.Column("version_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_source_document_versions_content_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(version_document) = 'object'",
            name=op.f("ck_topic4_source_document_versions_document_object"),
        ),
        sa.CheckConstraint(
            "lifecycle IN ('DRAFT', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'REVOKED')",
            name=op.f("ck_topic4_source_document_versions_lifecycle"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_source_document_versions_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_source_document_versions_trace_id_format"),
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_until > effective_from",
            name=op.f("ck_topic4_source_document_versions_effective_window"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_source_document_versions_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_source_document_versions_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_source_document_versions_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_document_id"],
            ["topic4_source_documents.tenant_id", "topic4_source_documents.source_document_id"],
            name=op.f(
                "fk_topic4_source_document_versions_tenant_id_source_document_id_topic4_source_documents"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_source_document_versions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "source_document_version_record_id", name=op.f("pk_topic4_source_document_versions")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "source_document_id",
            "version",
            name=op.f("uq_topic4_source_document_versions_tenant_id_source_document_id_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "source_document_version_id",
            name=op.f("uq_topic4_source_document_versions_tenant_id_source_document_version_id"),
        ),
    )
    op.create_index(
        "ix_topic4_source_versions_document_effective",
        "topic4_source_document_versions",
        ["tenant_id", "source_document_id", "effective_from"],
        unique=False,
    )
    op.create_table(
        "topic4_formula_signatures",
        sa.Column("formula_signature_record_id", sa.UUID(), nullable=False),
        sa.Column("formula_signature_id", sa.UUID(), nullable=False),
        sa.Column("source_document_version_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.String(length=256), nullable=False),
        sa.Column("canonical_expression", sa.String(length=8192), nullable=False),
        sa.Column("signature_sha256", sa.String(length=64), nullable=False),
        sa.Column("signature_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(signature_document) = 'object'",
            name=op.f("ck_topic4_formula_signatures_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_formula_signatures_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "signature_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_formula_signatures_signature_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_formula_signatures_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_formula_signatures_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_formula_signatures_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_formula_signatures_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_document_version_id"],
            [
                "topic4_source_document_versions.tenant_id",
                "topic4_source_document_versions.source_document_version_id",
            ],
            name=op.f(
                "fk_topic4_formula_signatures_tenant_id_source_document_version_id_topic4_source_document_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_formula_signatures_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "formula_signature_record_id", name=op.f("pk_topic4_formula_signatures")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "formula_signature_id",
            name=op.f("uq_topic4_formula_signatures_tenant_id_formula_signature_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "source_document_version_id",
            "signature_sha256",
            name=op.f(
                "uq_topic4_formula_signatures_tenant_id_source_document_version_id_signature_sha256"
            ),
        ),
    )
    op.create_index(
        "ix_topic4_formula_signatures_source",
        "topic4_formula_signatures",
        ["tenant_id", "source_document_version_id", "section_id"],
        unique=False,
    )
    op.create_table(
        "topic4_index_build_manifests",
        sa.Column("manifest_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("index_build_manifest_id", sa.UUID(), nullable=False),
        sa.Column("manifest_version", sa.BigInteger(), nullable=False),
        sa.Column("knowledge_base_version_id", sa.UUID(), nullable=False),
        sa.Column("embedding_profile_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("chunk_count", sa.BigInteger(), nullable=False),
        sa.Column("shard_count", sa.Integer(), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(manifest_document) = 'object'",
            name=op.f("ck_topic4_index_build_manifests_document_object"),
        ),
        sa.CheckConstraint(
            "manifest_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_index_build_manifests_manifest_sha256_format"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_index_build_manifests_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "state IN ('BUILDING', 'READY', 'FAILED', 'CORRUPTED', 'RETIRED')",
            name=op.f("ck_topic4_index_build_manifests_state"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_index_build_manifests_trace_id_format"),
        ),
        sa.CheckConstraint(
            "chunk_count >= 0", name=op.f("ck_topic4_index_build_manifests_nonnegative_chunk_count")
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_index_build_manifests_immutable_record")
        ),
        sa.CheckConstraint(
            "manifest_version >= 1",
            name=op.f("ck_topic4_index_build_manifests_positive_manifest_version"),
        ),
        sa.CheckConstraint(
            "shard_count >= 0", name=op.f("ck_topic4_index_build_manifests_nonnegative_shard_count")
        ),
        sa.CheckConstraint(
            "version_cas = manifest_version",
            name=op.f("ck_topic4_index_build_manifests_cas_matches_manifest_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_index_build_manifests_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_index_build_manifests_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "embedding_profile_id"],
            [
                "topic4_embedding_profiles.tenant_id",
                "topic4_embedding_profiles.embedding_profile_id",
            ],
            name=op.f(
                "fk_topic4_index_build_manifests_tenant_id_embedding_profile_id_topic4_embedding_profiles"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "knowledge_base_version_id"],
            [
                "topic4_knowledge_base_versions.tenant_id",
                "topic4_knowledge_base_versions.knowledge_base_version_id",
            ],
            name=op.f(
                "fk_topic4_index_build_manifests_tenant_id_knowledge_base_version_id_topic4_knowledge_base_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_index_build_manifests_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "manifest_snapshot_id", name=op.f("pk_topic4_index_build_manifests")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "index_build_manifest_id",
            "manifest_version",
            name=op.f(
                "uq_topic4_index_build_manifests_tenant_id_index_build_manifest_id_manifest_version"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "manifest_snapshot_id",
            name=op.f("uq_topic4_index_build_manifests_tenant_id_manifest_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic4_index_manifests_kb_state",
        "topic4_index_build_manifests",
        ["tenant_id", "knowledge_base_version_id", "state", "manifest_version"],
        unique=False,
    )
    op.create_table(
        "topic4_knowledge_base_activations",
        sa.Column("activation_record_id", sa.UUID(), nullable=False),
        sa.Column("activation_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.String(length=128), nullable=False),
        sa.Column("activation_version", sa.BigInteger(), nullable=False),
        sa.Column("knowledge_base_version_id", sa.UUID(), nullable=False),
        sa.Column("replaces_activation_id", sa.UUID(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activation_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(activation_document) = 'object'",
            name=op.f("ck_topic4_knowledge_base_activations_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_knowledge_base_activations_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_knowledge_base_activations_trace_id_format"),
        ),
        sa.CheckConstraint(
            "activation_version >= 1",
            name=op.f("ck_topic4_knowledge_base_activations_positive_activation_version"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_knowledge_base_activations_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas = activation_version",
            name=op.f("ck_topic4_knowledge_base_activations_cas_matches_activation_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1",
            name=op.f("ck_topic4_knowledge_base_activations_positive_version_cas"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_knowledge_base_activations_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "knowledge_base_version_id"],
            [
                "topic4_knowledge_base_versions.tenant_id",
                "topic4_knowledge_base_versions.knowledge_base_version_id",
            ],
            name=op.f(
                "fk_topic4_knowledge_base_activations_tenant_id_knowledge_base_version_id_topic4_knowledge_base_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "replaces_activation_id"],
            [
                "topic4_knowledge_base_activations.tenant_id",
                "topic4_knowledge_base_activations.activation_id",
            ],
            name=op.f(
                "fk_topic4_knowledge_base_activations_tenant_id_replaces_activation_id_topic4_knowledge_base_activations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_knowledge_base_activations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "activation_record_id", name=op.f("pk_topic4_knowledge_base_activations")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "activation_id",
            name=op.f("uq_topic4_knowledge_base_activations_tenant_id_activation_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "course_id",
            "activation_version",
            name=op.f(
                "uq_topic4_knowledge_base_activations_tenant_id_course_id_activation_version"
            ),
        ),
    )
    op.create_index(
        "ix_topic4_kb_activations_course",
        "topic4_knowledge_base_activations",
        ["tenant_id", "course_id", "activation_version"],
        unique=False,
    )
    op.create_table(
        "topic4_knowledge_chunks",
        sa.Column("knowledge_chunk_record_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_chunk_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_version_id", sa.UUID(), nullable=False),
        sa.Column("source_document_version_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.String(length=256), nullable=False),
        sa.Column("chunk_ordinal", sa.Integer(), nullable=False),
        sa.Column("normalized_text", sa.String(length=131072), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("vector_ordinal", sa.BigInteger(), nullable=False),
        sa.Column(
            "topic1_knowledge_point_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("formula_signature_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chunk_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_knowledge_chunks_content_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(chunk_document) = 'object'",
            name=op.f("ck_topic4_knowledge_chunks_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(formula_signature_ids) = 'array'",
            name=op.f("ck_topic4_knowledge_chunks_formula_signatures_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(topic1_knowledge_point_ids) = 'array'",
            name=op.f("ck_topic4_knowledge_chunks_knowledge_points_array"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_knowledge_chunks_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_knowledge_chunks_trace_id_format"),
        ),
        sa.CheckConstraint(
            "chunk_ordinal >= 0", name=op.f("ck_topic4_knowledge_chunks_nonnegative_chunk_ordinal")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_knowledge_chunks_immutable_record")),
        sa.CheckConstraint(
            "octet_length(normalized_text) <= 131072",
            name=op.f("ck_topic4_knowledge_chunks_text_size"),
        ),
        sa.CheckConstraint(
            "token_count BETWEEN 1 AND 16384",
            name=op.f("ck_topic4_knowledge_chunks_token_count_range"),
        ),
        sa.CheckConstraint(
            "vector_ordinal >= 0",
            name=op.f("ck_topic4_knowledge_chunks_nonnegative_vector_ordinal"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_knowledge_chunks_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_knowledge_chunks_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "knowledge_base_version_id"],
            [
                "topic4_knowledge_base_versions.tenant_id",
                "topic4_knowledge_base_versions.knowledge_base_version_id",
            ],
            name=op.f(
                "fk_topic4_knowledge_chunks_tenant_id_knowledge_base_version_id_topic4_knowledge_base_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_document_version_id"],
            [
                "topic4_source_document_versions.tenant_id",
                "topic4_source_document_versions.source_document_version_id",
            ],
            name=op.f(
                "fk_topic4_knowledge_chunks_tenant_id_source_document_version_id_topic4_source_document_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_knowledge_chunks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "knowledge_chunk_record_id", name=op.f("pk_topic4_knowledge_chunks")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "knowledge_base_version_id",
            "source_document_version_id",
            "section_id",
            "chunk_ordinal",
            name=op.f(
                "uq_topic4_knowledge_chunks_tenant_id_knowledge_base_version_id_source_document_version_id_section_id_chunk_ordinal"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "knowledge_base_version_id",
            "vector_ordinal",
            name=op.f(
                "uq_topic4_knowledge_chunks_tenant_id_knowledge_base_version_id_vector_ordinal"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "knowledge_chunk_id",
            name=op.f("uq_topic4_knowledge_chunks_tenant_id_knowledge_chunk_id"),
        ),
    )
    op.create_index(
        "ix_topic4_chunks_kb_source",
        "topic4_knowledge_chunks",
        ["tenant_id", "knowledge_base_version_id", "source_document_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_topic4_chunks_kb_vector",
        "topic4_knowledge_chunks",
        ["tenant_id", "knowledge_base_version_id", "vector_ordinal"],
        unique=False,
    )
    op.create_table(
        "topic4_evidence_refs",
        sa.Column("evidence_ref_record_id", sa.UUID(), nullable=False),
        sa.Column("evidence_ref_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_version_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_chunk_id", sa.UUID(), nullable=False),
        sa.Column("source_document_version_id", sa.UUID(), nullable=False),
        sa.Column("excerpt_sha256", sa.String(length=64), nullable=False),
        sa.Column("fused_score", sa.Float(), nullable=False),
        sa.Column("evidence_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "excerpt_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_evidence_refs_excerpt_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence_document) = 'object'",
            name=op.f("ck_topic4_evidence_refs_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_evidence_refs_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_evidence_refs_trace_id_format"),
        ),
        sa.CheckConstraint(
            "fused_score >= 0", name=op.f("ck_topic4_evidence_refs_nonnegative_fused_score")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_evidence_refs_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_evidence_refs_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_evidence_refs_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "claim_id"],
            ["topic4_claims.tenant_id", "topic4_claims.claim_id"],
            name=op.f("fk_topic4_evidence_refs_tenant_id_claim_id_topic4_claims"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "knowledge_chunk_id"],
            ["topic4_knowledge_chunks.tenant_id", "topic4_knowledge_chunks.knowledge_chunk_id"],
            name=op.f(
                "fk_topic4_evidence_refs_tenant_id_knowledge_chunk_id_topic4_knowledge_chunks"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_evidence_refs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("evidence_ref_record_id", name=op.f("pk_topic4_evidence_refs")),
        sa.UniqueConstraint(
            "tenant_id",
            "claim_id",
            "knowledge_chunk_id",
            "excerpt_sha256",
            name=op.f(
                "uq_topic4_evidence_refs_tenant_id_claim_id_knowledge_chunk_id_excerpt_sha256"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "evidence_ref_id",
            name=op.f("uq_topic4_evidence_refs_tenant_id_evidence_ref_id"),
        ),
    )
    op.create_index(
        "ix_topic4_evidence_claim_score",
        "topic4_evidence_refs",
        ["tenant_id", "claim_id", "fused_score"],
        unique=False,
    )
    op.create_table(
        "topic4_query_plans",
        sa.Column("query_plan_record_id", sa.UUID(), nullable=False),
        sa.Column("query_plan_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_version_id", sa.UUID(), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("plan_sha256", sa.String(length=64), nullable=False),
        sa.Column("plan_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(plan_document) = 'object'",
            name=op.f("ck_topic4_query_plans_document_object"),
        ),
        sa.CheckConstraint(
            "plan_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_topic4_query_plans_plan_sha256_format")
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_query_plans_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'", name=op.f("ck_topic4_query_plans_trace_id_format")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_query_plans_immutable_record")),
        sa.CheckConstraint(
            "timeout_ms BETWEEN 10 AND 10000", name=op.f("ck_topic4_query_plans_timeout_range")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_query_plans_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_query_plans_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "claim_id"],
            ["topic4_claims.tenant_id", "topic4_claims.claim_id"],
            name=op.f("fk_topic4_query_plans_tenant_id_claim_id_topic4_claims"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "knowledge_base_version_id"],
            [
                "topic4_knowledge_base_versions.tenant_id",
                "topic4_knowledge_base_versions.knowledge_base_version_id",
            ],
            name=op.f(
                "fk_topic4_query_plans_tenant_id_knowledge_base_version_id_topic4_knowledge_base_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_query_plans_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("query_plan_record_id", name=op.f("pk_topic4_query_plans")),
        sa.UniqueConstraint(
            "tenant_id", "query_plan_id", name=op.f("uq_topic4_query_plans_tenant_id_query_plan_id")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "claim_id",
            "version_cas",
            name=op.f("uq_topic4_query_plans_tenant_id_verification_id_claim_id_version_cas"),
        ),
    )
    op.create_index(
        "ix_topic4_query_plans_claim",
        "topic4_query_plans",
        ["tenant_id", "claim_id", "version_cas"],
        unique=False,
    )
    op.create_table(
        "topic4_evidence_bundles",
        sa.Column("evidence_bundle_record_id", sa.UUID(), nullable=False),
        sa.Column("evidence_bundle_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("query_plan_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_version_id", sa.UUID(), nullable=False),
        sa.Column("evidence_ref_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coverage_score", sa.Float(), nullable=False),
        sa.Column("conflicting_evidence", sa.Boolean(), nullable=False),
        sa.Column("total_ms", sa.Integer(), nullable=False),
        sa.Column("bundle_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(bundle_document) = 'object'",
            name=op.f("ck_topic4_evidence_bundles_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence_ref_ids) = 'array'",
            name=op.f("ck_topic4_evidence_bundles_evidence_refs_array"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_evidence_bundles_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_evidence_bundles_trace_id_format"),
        ),
        sa.CheckConstraint(
            "coverage_score BETWEEN 0 AND 1", name=op.f("ck_topic4_evidence_bundles_coverage_range")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_evidence_bundles_immutable_record")),
        sa.CheckConstraint(
            "total_ms >= 0", name=op.f("ck_topic4_evidence_bundles_nonnegative_total_ms")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_evidence_bundles_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_evidence_bundles_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "claim_id"],
            ["topic4_claims.tenant_id", "topic4_claims.claim_id"],
            name=op.f("fk_topic4_evidence_bundles_tenant_id_claim_id_topic4_claims"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "query_plan_id"],
            ["topic4_query_plans.tenant_id", "topic4_query_plans.query_plan_id"],
            name=op.f("fk_topic4_evidence_bundles_tenant_id_query_plan_id_topic4_query_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_evidence_bundles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "evidence_bundle_record_id", name=op.f("pk_topic4_evidence_bundles")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "evidence_bundle_id",
            name=op.f("uq_topic4_evidence_bundles_tenant_id_evidence_bundle_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "claim_id",
            "version_cas",
            name=op.f("uq_topic4_evidence_bundles_tenant_id_verification_id_claim_id_version_cas"),
        ),
    )
    op.create_index(
        "ix_topic4_evidence_bundles_claim",
        "topic4_evidence_bundles",
        ["tenant_id", "claim_id", "version_cas"],
        unique=False,
    )
    op.create_table(
        "topic4_retrieval_runs",
        sa.Column("retrieval_run_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("retrieval_request_id", sa.UUID(), nullable=False),
        sa.Column("run_version", sa.BigInteger(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("query_plan_id", sa.UUID(), nullable=False),
        sa.Column("index_build_manifest_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("run_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(run_document) = 'object'",
            name=op.f("ck_topic4_retrieval_runs_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_retrieval_runs_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "status IN ('SUCCEEDED', 'DEGRADED', 'FAILED')",
            name=op.f("ck_topic4_retrieval_runs_status"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_retrieval_runs_trace_id_format"),
        ),
        sa.CheckConstraint(
            "elapsed_ms >= 0", name=op.f("ck_topic4_retrieval_runs_nonnegative_elapsed_ms")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_retrieval_runs_immutable_record")),
        sa.CheckConstraint(
            "run_version >= 1", name=op.f("ck_topic4_retrieval_runs_positive_run_version")
        ),
        sa.CheckConstraint(
            "version_cas = run_version",
            name=op.f("ck_topic4_retrieval_runs_cas_matches_run_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_retrieval_runs_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_retrieval_runs_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "query_plan_id"],
            ["topic4_query_plans.tenant_id", "topic4_query_plans.query_plan_id"],
            name=op.f("fk_topic4_retrieval_runs_tenant_id_query_plan_id_topic4_query_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_retrieval_runs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("retrieval_run_snapshot_id", name=op.f("pk_topic4_retrieval_runs")),
        sa.UniqueConstraint(
            "tenant_id",
            "retrieval_request_id",
            "run_version",
            name=op.f("uq_topic4_retrieval_runs_tenant_id_retrieval_request_id_run_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "retrieval_run_snapshot_id",
            name=op.f("uq_topic4_retrieval_runs_tenant_id_retrieval_run_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic4_retrieval_runs_claim",
        "topic4_retrieval_runs",
        ["tenant_id", "claim_id", "run_version"],
        unique=False,
    )
    for table_name in TOPIC4_KNOWLEDGE_TABLES:
        _install_tenant_policy(table_name)
        _install_append_only_trigger(table_name)
    _grant_runtime_privileges()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in TOPIC4_KNOWLEDGE_TABLES:
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{table_name}_append_only ON {table_name}"))
    op.drop_index("ix_topic4_retrieval_runs_claim", table_name="topic4_retrieval_runs")
    op.drop_table("topic4_retrieval_runs")
    op.drop_index("ix_topic4_evidence_bundles_claim", table_name="topic4_evidence_bundles")
    op.drop_table("topic4_evidence_bundles")
    op.drop_index("ix_topic4_query_plans_claim", table_name="topic4_query_plans")
    op.drop_table("topic4_query_plans")
    op.drop_index("ix_topic4_evidence_claim_score", table_name="topic4_evidence_refs")
    op.drop_table("topic4_evidence_refs")
    op.drop_index("ix_topic4_chunks_kb_vector", table_name="topic4_knowledge_chunks")
    op.drop_index("ix_topic4_chunks_kb_source", table_name="topic4_knowledge_chunks")
    op.drop_table("topic4_knowledge_chunks")
    op.drop_index("ix_topic4_kb_activations_course", table_name="topic4_knowledge_base_activations")
    op.drop_table("topic4_knowledge_base_activations")
    op.drop_index("ix_topic4_index_manifests_kb_state", table_name="topic4_index_build_manifests")
    op.drop_table("topic4_index_build_manifests")
    op.drop_index("ix_topic4_formula_signatures_source", table_name="topic4_formula_signatures")
    op.drop_table("topic4_formula_signatures")
    op.drop_index(
        "ix_topic4_source_versions_document_effective", table_name="topic4_source_document_versions"
    )
    op.drop_table("topic4_source_document_versions")
    op.drop_index(
        "ix_topic4_kb_versions_course_created", table_name="topic4_knowledge_base_versions"
    )
    op.drop_table("topic4_knowledge_base_versions")
    op.drop_index(
        "ix_topic4_source_documents_course_authority", table_name="topic4_source_documents"
    )
    op.drop_table("topic4_source_documents")
    op.drop_table("topic4_embedding_profiles")
    # ### end Alembic commands ###
