"""create topic 4 revision release security runtime

Revision ID: 20260716_0009
Revises: 20260716_0008
Create Date: 2026-07-16 11:38:58.724213
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260716_0009"
down_revision: str | Sequence[str] | None = "20260716_0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOPIC4_REVISION_RELEASE_TABLES = (
    "topic4_acceptance_reports",
    "topic4_acceptance_gate_results",
    "topic4_sbom_manifests",
    "topic4_sbom_components",
    "topic4_vulnerability_records",
    "topic4_build_provenance",
    "topic4_pii_findings",
    "topic4_privacy_tenant_results",
    "topic4_tokenized_values",
    "topic4_security_findings",
    "topic4_revision_cycles",
    "topic4_revision_plans",
    "topic4_revision_patches",
    "topic4_release_authorizations",
    "topic4_publication_batches",
    "topic4_release_authorization_consumptions",
    "topic4_public_stream_events",
)


def _install_tenant_policy(table_name: str) -> None:
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')"
    op.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    )


def _install_append_only_trigger(table_name: str) -> None:
    op.execute(
        sa.text(
            f"CREATE TRIGGER trg_{table_name}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION reject_topic4_history_mutation()"
        )
    )


def _grant_runtime_privileges() -> None:
    all_tables = ", ".join(TOPIC4_REVISION_RELEASE_TABLES)
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM PUBLIC';
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liyans_app') THEN
                    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM liyans_app';
                    EXECUTE 'GRANT SELECT, INSERT ON TABLE {all_tables} TO liyans_app';
                END IF;
            END
            $$
            """
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic4_acceptance_reports",
        sa.Column("acceptance_report_record_id", sa.UUID(), nullable=False),
        sa.Column("system_acceptance_report_id", sa.UUID(), nullable=False),
        sa.Column("build_commit_sha256", sa.String(length=64), nullable=False),
        sa.Column("build_version", sa.String(length=128), nullable=False),
        sa.Column("python_coverage_percent", sa.Float(), nullable=False),
        sa.Column("concurrent_verifications", sa.Integer(), nullable=False),
        sa.Column("retrieval_p95_ms", sa.Float(), nullable=False),
        sa.Column("publication_p95_ms", sa.Float(), nullable=False),
        sa.Column("cross_tenant_leaks", sa.Integer(), nullable=False),
        sa.Column("authorization_replay_successes", sa.Integer(), nullable=False),
        sa.Column("critical_vulnerabilities", sa.Integer(), nullable=False),
        sa.Column("high_vulnerabilities", sa.Integer(), nullable=False),
        sa.Column("open_p0_defects", sa.Integer(), nullable=False),
        sa.Column("open_p1_defects", sa.Integer(), nullable=False),
        sa.Column("flaky_core_tests", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("report_artifact", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report_sha256", sa.String(length=64), nullable=False),
        sa.Column("report_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "build_commit_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_acceptance_reports_commit_sha256_format"),
        ),
        sa.CheckConstraint(
            "decision <> 'ACCEPTED' OR (python_coverage_percent >= 90 AND "
            "concurrent_verifications >= 200 AND retrieval_p95_ms <= 200 AND "
            "publication_p95_ms <= 300 AND cross_tenant_leaks = 0 AND "
            "authorization_replay_successes = 0 AND critical_vulnerabilities = 0 AND "
            "high_vulnerabilities = 0 AND open_p0_defects = 0 AND open_p1_defects = 0 AND "
            "flaky_core_tests = 0)",
            name=op.f("ck_topic4_acceptance_reports_accepted_redlines"),
        ),
        sa.CheckConstraint(
            "decision IN ('ACCEPTED', 'REJECTED')",
            name=op.f("ck_topic4_acceptance_reports_decision"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(report_artifact) = 'object'",
            name=op.f("ck_topic4_acceptance_reports_artifact_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(report_document) = 'object'",
            name=op.f("ck_topic4_acceptance_reports_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_acceptance_reports_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "report_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_acceptance_reports_report_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_acceptance_reports_trace_id_format"),
        ),
        sa.CheckConstraint(
            "concurrent_verifications >= 0",
            name=op.f("ck_topic4_acceptance_reports_nonnegative_concurrency"),
        ),
        sa.CheckConstraint(
            "cross_tenant_leaks >= 0 AND authorization_replay_successes >= 0 AND "
            "critical_vulnerabilities >= 0 AND high_vulnerabilities >= 0 AND "
            "open_p0_defects >= 0 AND open_p1_defects >= 0 AND flaky_core_tests >= 0",
            name=op.f("ck_topic4_acceptance_reports_nonnegative_redlines"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_acceptance_reports_immutable_record")),
        sa.CheckConstraint(
            "publication_p95_ms >= 0",
            name=op.f("ck_topic4_acceptance_reports_nonnegative_publication_p95"),
        ),
        sa.CheckConstraint(
            "python_coverage_percent BETWEEN 0 AND 100",
            name=op.f("ck_topic4_acceptance_reports_coverage_range"),
        ),
        sa.CheckConstraint(
            "retrieval_p95_ms >= 0",
            name=op.f("ck_topic4_acceptance_reports_nonnegative_retrieval_p95"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_acceptance_reports_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_acceptance_reports_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_acceptance_reports_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "acceptance_report_record_id", name=op.f("pk_topic4_acceptance_reports")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "build_commit_sha256",
            "build_version",
            name=op.f("uq_topic4_acceptance_reports_tenant_id_build_commit_sha256_build_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "system_acceptance_report_id",
            name=op.f("uq_topic4_acceptance_reports_tenant_id_system_acceptance_report_id"),
        ),
    )
    op.create_index(
        "ix_topic4_acceptance_reports_build",
        "topic4_acceptance_reports",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_sbom_manifests",
        sa.Column("sbom_manifest_record_id", sa.UUID(), nullable=False),
        sa.Column("sbom_manifest_id", sa.UUID(), nullable=False),
        sa.Column("code_artifact_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("spec_version", sa.String(length=128), nullable=False),
        sa.Column("serial_number", sa.String(length=256), nullable=False),
        sa.Column("sbom_artifact", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sbom_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format = 'CYCLONEDX_JSON'", name=op.f("ck_topic4_sbom_manifests_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(manifest_document) = 'object'",
            name=op.f("ck_topic4_sbom_manifests_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(sbom_artifact) = 'object'",
            name=op.f("ck_topic4_sbom_manifests_artifact_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_sbom_manifests_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "sbom_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_sbom_manifests_sbom_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_sbom_manifests_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_sbom_manifests_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_sbom_manifests_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_sbom_manifests_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_sbom_manifests_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("sbom_manifest_record_id", name=op.f("pk_topic4_sbom_manifests")),
        sa.UniqueConstraint(
            "tenant_id",
            "code_artifact_id",
            "sbom_sha256",
            name=op.f("uq_topic4_sbom_manifests_tenant_id_code_artifact_id_sbom_sha256"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "sbom_manifest_id",
            name=op.f("uq_topic4_sbom_manifests_tenant_id_sbom_manifest_id"),
        ),
    )
    op.create_index(
        "ix_topic4_sbom_manifests_code",
        "topic4_sbom_manifests",
        ["tenant_id", "code_artifact_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_acceptance_gate_results",
        sa.Column("acceptance_gate_result_record_id", sa.UUID(), nullable=False),
        sa.Column("acceptance_gate_result_id", sa.UUID(), nullable=False),
        sa.Column("system_acceptance_report_id", sa.UUID(), nullable=False),
        sa.Column("gate_code", sa.String(length=4), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("metric_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_artifact", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=False),
        sa.Column("failure_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gate_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_acceptance_gate_results_evidence_sha256_format"),
        ),
        sa.CheckConstraint(
            "gate_code ~ '^G([0-9]|1[0-2])$'",
            name=op.f("ck_topic4_acceptance_gate_results_gate_code_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence_artifact) = 'object'",
            name=op.f("ck_topic4_acceptance_gate_results_artifact_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(failure_codes) = 'array'",
            name=op.f("ck_topic4_acceptance_gate_results_failures_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(gate_document) = 'object'",
            name=op.f("ck_topic4_acceptance_gate_results_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(metric_values) = 'object'",
            name=op.f("ck_topic4_acceptance_gate_results_metrics_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_acceptance_gate_results_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "status IN ('PASSED', 'FAILED', 'SKIPPED')",
            name=op.f("ck_topic4_acceptance_gate_results_status"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_acceptance_gate_results_trace_id_format"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_acceptance_gate_results_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_acceptance_gate_results_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_acceptance_gate_results_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "system_acceptance_report_id"],
            [
                "topic4_acceptance_reports.tenant_id",
                "topic4_acceptance_reports.system_acceptance_report_id",
            ],
            name=op.f(
                "fk_topic4_acceptance_gate_results_tenant_id_system_acceptance_report_id_topic4_acceptance_reports"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_acceptance_gate_results_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "acceptance_gate_result_record_id", name=op.f("pk_topic4_acceptance_gate_results")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "acceptance_gate_result_id",
            name=op.f("uq_topic4_acceptance_gate_results_tenant_id_acceptance_gate_result_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "system_acceptance_report_id",
            "gate_code",
            name=op.f(
                "uq_topic4_acceptance_gate_results_tenant_id_system_acceptance_report_id_gate_code"
            ),
        ),
    )
    op.create_table(
        "topic4_build_provenance",
        sa.Column("build_provenance_record_id", sa.UUID(), nullable=False),
        sa.Column("build_provenance_id", sa.UUID(), nullable=False),
        sa.Column("code_artifact_id", sa.UUID(), nullable=False),
        sa.Column("builder_id", sa.String(length=256), nullable=False),
        sa.Column("builder_version", sa.String(length=128), nullable=False),
        sa.Column("toolchain_manifest_version", sa.String(length=128), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("build_output_artifact", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("build_output_sha256", sa.String(length=64), nullable=False),
        sa.Column("sbom_manifest_id", sa.UUID(), nullable=False),
        sa.Column("sandbox_policy_id", sa.UUID(), nullable=False),
        sa.Column("reproducible", sa.Boolean(), nullable=False),
        sa.Column("build_command_sha256", sa.String(length=64), nullable=False),
        sa.Column("provenance_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "build_command_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_build_provenance_build_command_sha256_format"),
        ),
        sa.CheckConstraint(
            "build_output_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_build_provenance_build_output_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(build_output_artifact) = 'object'",
            name=op.f("ck_topic4_build_provenance_artifact_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(provenance_document) = 'object'",
            name=op.f("ck_topic4_build_provenance_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_build_provenance_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "source_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_build_provenance_source_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_build_provenance_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_build_provenance_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_build_provenance_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_build_provenance_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sbom_manifest_id"],
            ["topic4_sbom_manifests.tenant_id", "topic4_sbom_manifests.sbom_manifest_id"],
            name=op.f(
                "fk_topic4_build_provenance_tenant_id_sbom_manifest_id_topic4_sbom_manifests"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_build_provenance_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "build_provenance_record_id", name=op.f("pk_topic4_build_provenance")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "build_provenance_id",
            name=op.f("uq_topic4_build_provenance_tenant_id_build_provenance_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "code_artifact_id",
            "build_output_sha256",
            name=op.f("uq_topic4_build_provenance_tenant_id_code_artifact_id_build_output_sha256"),
        ),
    )
    op.create_table(
        "topic4_sbom_components",
        sa.Column("component_record_id", sa.UUID(), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.Column("sbom_manifest_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("version", sa.String(length=256), nullable=False),
        sa.Column("package_url", sa.String(length=2048), nullable=True),
        sa.Column("licenses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("component_sha256", sa.String(length=64), nullable=True),
        sa.Column("component_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "component_sha256 IS NULL OR component_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_sbom_components_component_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(component_document) = 'object'",
            name=op.f("ck_topic4_sbom_components_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(licenses) = 'array'",
            name=op.f("ck_topic4_sbom_components_licenses_array"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_sbom_components_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_sbom_components_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_sbom_components_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_sbom_components_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_sbom_components_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sbom_manifest_id"],
            ["topic4_sbom_manifests.tenant_id", "topic4_sbom_manifests.sbom_manifest_id"],
            name=op.f("fk_topic4_sbom_components_tenant_id_sbom_manifest_id_topic4_sbom_manifests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_sbom_components_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("component_record_id", name=op.f("pk_topic4_sbom_components")),
        sa.UniqueConstraint(
            "tenant_id",
            "component_id",
            name=op.f("uq_topic4_sbom_components_tenant_id_component_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "sbom_manifest_id",
            "name",
            "version",
            "package_url",
            name=op.f(
                "uq_topic4_sbom_components_tenant_id_sbom_manifest_id_name_version_package_url"
            ),
        ),
    )
    op.create_table(
        "topic4_vulnerability_records",
        sa.Column("vulnerability_record_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_record_id", sa.UUID(), nullable=False),
        sa.Column("sbom_manifest_id", sa.UUID(), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.Column("advisory_id", sa.String(length=256), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("affected_range", sa.String(length=512), nullable=True),
        sa.Column("fixed_version", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("non_waivable", sa.Boolean(), nullable=False),
        sa.Column(
            "vulnerability_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (non_waivable AND status = 'ACCEPTED_RISK')",
            name=op.f("ck_topic4_vulnerability_records_non_waivable_not_accepted"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(vulnerability_document) = 'object'",
            name=op.f("ck_topic4_vulnerability_records_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_vulnerability_records_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_topic4_vulnerability_records_severity"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'NOT_AFFECTED', 'MITIGATED', 'FIXED', 'ACCEPTED_RISK')",
            name=op.f("ck_topic4_vulnerability_records_status"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_vulnerability_records_trace_id_format"),
        ),
        sa.CheckConstraint(
            "cvss_score IS NULL OR cvss_score BETWEEN 0 AND 10",
            name=op.f("ck_topic4_vulnerability_records_cvss_range"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_vulnerability_records_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_vulnerability_records_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_vulnerability_records_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "component_id"],
            ["topic4_sbom_components.tenant_id", "topic4_sbom_components.component_id"],
            name=op.f(
                "fk_topic4_vulnerability_records_tenant_id_component_id_topic4_sbom_components"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sbom_manifest_id"],
            ["topic4_sbom_manifests.tenant_id", "topic4_sbom_manifests.sbom_manifest_id"],
            name=op.f(
                "fk_topic4_vulnerability_records_tenant_id_sbom_manifest_id_topic4_sbom_manifests"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_vulnerability_records_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "vulnerability_record_snapshot_id", name=op.f("pk_topic4_vulnerability_records")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "sbom_manifest_id",
            "component_id",
            "advisory_id",
            name=op.f(
                "uq_topic4_vulnerability_records_tenant_id_sbom_manifest_id_component_id_advisory_id"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "vulnerability_record_id",
            name=op.f("uq_topic4_vulnerability_records_tenant_id_vulnerability_record_id"),
        ),
    )
    op.create_index(
        "ix_topic4_vulnerabilities_open",
        "topic4_vulnerability_records",
        ["tenant_id", "severity", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_pii_findings",
        sa.Column("pii_finding_record_id", sa.UUID(), nullable=False),
        sa.Column("pii_finding_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.String(length=128), nullable=False),
        sa.Column("json_pointer", sa.String(length=1024), nullable=False),
        sa.Column("pii_type", sa.String(length=24), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("original_value_sha256", sa.String(length=64), nullable=False),
        sa.Column("non_waivable", sa.Boolean(), nullable=False),
        sa.Column("finding_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('ALLOW', 'TOKENIZE', 'REDACT', 'BLOCK')",
            name=op.f("ck_topic4_pii_findings_action"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(finding_document) = 'object'",
            name=op.f("ck_topic4_pii_findings_document_object"),
        ),
        sa.CheckConstraint(
            "original_value_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_pii_findings_original_value_sha256_format"),
        ),
        sa.CheckConstraint(
            "pii_type IN ('NAME', 'PHONE', 'EMAIL', 'NATIONAL_ID', 'STUDENT_ID', "
            "'ADDRESS', 'BIOMETRIC', 'CREDENTIAL', 'OTHER')",
            name=op.f("ck_topic4_pii_findings_pii_type"),
        ),
        sa.CheckConstraint(
            "pii_type NOT IN ('NATIONAL_ID', 'BIOMETRIC', 'CREDENTIAL') OR action <> 'ALLOW'",
            name=op.f("ck_topic4_pii_findings_critical_pii_not_allowed"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_pii_findings_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_topic4_pii_findings_severity"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'", name=op.f("ck_topic4_pii_findings_trace_id_format")
        ),
        sa.CheckConstraint(
            "candidate_version >= 1", name=op.f("ck_topic4_pii_findings_positive_candidate_version")
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_topic4_pii_findings_confidence_range")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_pii_findings_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_pii_findings_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_pii_findings_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "candidate_id", "candidate_version"],
            [
                "topic3_generated_candidates.tenant_id",
                "topic3_generated_candidates.candidate_id",
                "topic3_generated_candidates.candidate_version",
            ],
            name=op.f(
                "fk_topic4_pii_findings_tenant_id_candidate_id_candidate_version_topic3_generated_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f("fk_topic4_pii_findings_tenant_id_verification_id_topic4_verifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_pii_findings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("pii_finding_record_id", name=op.f("pk_topic4_pii_findings")),
        sa.UniqueConstraint(
            "tenant_id",
            "pii_finding_id",
            name=op.f("uq_topic4_pii_findings_tenant_id_pii_finding_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "candidate_id",
            "candidate_version",
            "block_id",
            "json_pointer",
            "original_value_sha256",
            name=op.f(
                "uq_topic4_pii_findings_tenant_id_verification_id_candidate_id_candidate_version_block_id_json_pointer_original_value_sha256"
            ),
        ),
    )
    op.create_index(
        "ix_topic4_pii_findings_verification",
        "topic4_pii_findings",
        ["tenant_id", "verification_id", "severity", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_privacy_tenant_results",
        sa.Column("privacy_tenant_result_record_id", sa.UUID(), nullable=False),
        sa.Column("privacy_tenant_result_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("tenant_boundary_valid", sa.Boolean(), nullable=False),
        sa.Column("pii_finding_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokenized_value_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "redacted_candidate_artifact", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("redacted_candidate_sha256", sa.String(length=64), nullable=True),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("result_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_privacy_tenant_results_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(pii_finding_ids) = 'array'",
            name=op.f("ck_topic4_privacy_tenant_results_pii_findings_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(result_document) = 'object'",
            name=op.f("ck_topic4_privacy_tenant_results_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(tokenized_value_ids) = 'array'",
            name=op.f("ck_topic4_privacy_tenant_results_tokens_array"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_privacy_tenant_results_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "redacted_candidate_artifact IS NULL OR "
            "jsonb_typeof(redacted_candidate_artifact) = 'object'",
            name=op.f("ck_topic4_privacy_tenant_results_redacted_artifact_object"),
        ),
        sa.CheckConstraint(
            "redacted_candidate_sha256 IS NULL OR redacted_candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_privacy_tenant_results_redacted_sha256_format"),
        ),
        sa.CheckConstraint(
            "tenant_boundary_valid OR verdict = 'UNSAFE'",
            name=op.f("ck_topic4_privacy_tenant_results_invalid_boundary_unsafe"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_privacy_tenant_results_trace_id_format"),
        ),
        sa.CheckConstraint(
            "verdict IN ('SUPPORTED', 'PARTIALLY_SUPPORTED', 'CONTRADICTED', "
            "'INSUFFICIENT_EVIDENCE', 'UNSAFE', 'NOT_APPLICABLE', 'ERROR')",
            name=op.f("ck_topic4_privacy_tenant_results_verdict"),
        ),
        sa.CheckConstraint(
            "(redacted_candidate_artifact IS NULL) = (redacted_candidate_sha256 IS NULL)",
            name=op.f("ck_topic4_privacy_tenant_results_redacted_artifact_pair"),
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name=op.f("ck_topic4_privacy_tenant_results_positive_candidate_version"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_privacy_tenant_results_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_privacy_tenant_results_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_privacy_tenant_results_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "candidate_id", "candidate_version"],
            [
                "topic3_generated_candidates.tenant_id",
                "topic3_generated_candidates.candidate_id",
                "topic3_generated_candidates.candidate_version",
            ],
            name=op.f(
                "fk_topic4_privacy_tenant_results_tenant_id_candidate_id_candidate_version_topic3_generated_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f(
                "fk_topic4_privacy_tenant_results_tenant_id_verification_id_topic4_verifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_privacy_tenant_results_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "privacy_tenant_result_record_id", name=op.f("pk_topic4_privacy_tenant_results")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "privacy_tenant_result_id",
            name=op.f("uq_topic4_privacy_tenant_results_tenant_id_privacy_tenant_result_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "version_cas",
            name=op.f("uq_topic4_privacy_tenant_results_tenant_id_verification_id_version_cas"),
        ),
    )
    op.create_table(
        "topic4_revision_cycles",
        sa.Column("revision_cycle_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("revision_cycle_id", sa.UUID(), nullable=False),
        sa.Column("cycle_version", sa.BigInteger(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("parent_verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("base_candidate_version", sa.Integer(), nullable=False),
        sa.Column("base_candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("revision_round", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("lock_token", sa.UUID(), nullable=False),
        sa.Column("lock_owner", sa.String(length=128), nullable=False),
        sa.Column("lock_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cycle_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_cycles_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(cycle_document) = 'object'",
            name=op.f("ck_topic4_revision_cycles_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_cycles_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "state IN ('PLANNED', 'LOCKED', 'GENERATING', 'COMPLETED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_topic4_revision_cycles_state"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_revision_cycles_trace_id_format"),
        ),
        sa.CheckConstraint(
            "cycle_version >= 1", name=op.f("ck_topic4_revision_cycles_positive_cycle_version")
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_revision_cycles_immutable_record")),
        sa.CheckConstraint(
            "lock_expires_at > created_at", name=op.f("ck_topic4_revision_cycles_lock_expiry")
        ),
        sa.CheckConstraint(
            "revision_round BETWEEN 1 AND 2", name=op.f("ck_topic4_revision_cycles_revision_round")
        ),
        sa.CheckConstraint(
            "version_cas = cycle_version",
            name=op.f("ck_topic4_revision_cycles_cas_matches_cycle_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_revision_cycles_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_revision_cycles_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "candidate_id", "base_candidate_version"],
            [
                "topic3_generated_candidates.tenant_id",
                "topic3_generated_candidates.candidate_id",
                "topic3_generated_candidates.candidate_version",
            ],
            name=op.f(
                "fk_topic4_revision_cycles_tenant_id_candidate_id_base_candidate_version_topic3_generated_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f("fk_topic4_revision_cycles_tenant_id_verification_id_topic4_verifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_revision_cycles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "revision_cycle_snapshot_id", name=op.f("pk_topic4_revision_cycles")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "revision_cycle_id",
            "cycle_version",
            name=op.f("uq_topic4_revision_cycles_tenant_id_revision_cycle_id_cycle_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "revision_cycle_snapshot_id",
            name=op.f("uq_topic4_revision_cycles_tenant_id_revision_cycle_snapshot_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "revision_round",
            "cycle_version",
            name=op.f(
                "uq_topic4_revision_cycles_tenant_id_verification_id_revision_round_cycle_version"
            ),
        ),
    )
    op.create_index(
        "ix_topic4_revision_cycles_verification",
        "topic4_revision_cycles",
        ["tenant_id", "verification_id", "revision_round", "cycle_version"],
        unique=False,
    )
    op.create_table(
        "topic4_security_findings",
        sa.Column("security_finding_record_id", sa.UUID(), nullable=False),
        sa.Column("security_finding_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.String(length=128), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("disposition", sa.String(length=16), nullable=False),
        sa.Column("detector", sa.String(length=128), nullable=False),
        sa.Column("detector_version", sa.String(length=128), nullable=False),
        sa.Column("evidence_fingerprint_sha256", sa.String(length=64), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("non_waivable", sa.Boolean(), nullable=False),
        sa.Column("finding_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('PROMPT_INJECTION', 'EXPOSED_CREDENTIAL', 'MALWARE', "
            "'UNSAFE_CODE', 'CONTENT_POLICY', 'CROSS_TENANT_REFERENCE', "
            "'DATA_EXFILTRATION')",
            name=op.f("ck_topic4_security_findings_category"),
        ),
        sa.CheckConstraint(
            "category NOT IN ('CROSS_TENANT_REFERENCE', 'DATA_EXFILTRATION', 'MALWARE') "
            "OR (non_waivable AND disposition = 'BLOCK')",
            name=op.f("ck_topic4_security_findings_mandatory_block"),
        ),
        sa.CheckConstraint(
            "disposition IN ('ALLOW', 'REDACT', 'REVIEW', 'BLOCK')",
            name=op.f("ck_topic4_security_findings_disposition"),
        ),
        sa.CheckConstraint(
            "evidence_fingerprint_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_security_findings_evidence_fingerprint_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(finding_document) = 'object'",
            name=op.f("ck_topic4_security_findings_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_security_findings_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_topic4_security_findings_severity"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_security_findings_trace_id_format"),
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name=op.f("ck_topic4_security_findings_positive_candidate_version"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_security_findings_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_security_findings_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_security_findings_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "candidate_id", "candidate_version"],
            [
                "topic3_generated_candidates.tenant_id",
                "topic3_generated_candidates.candidate_id",
                "topic3_generated_candidates.candidate_version",
            ],
            name=op.f(
                "fk_topic4_security_findings_tenant_id_candidate_id_candidate_version_topic3_generated_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f("fk_topic4_security_findings_tenant_id_verification_id_topic4_verifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_security_findings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "security_finding_record_id", name=op.f("pk_topic4_security_findings")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "security_finding_id",
            name=op.f("uq_topic4_security_findings_tenant_id_security_finding_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "verification_id",
            "candidate_id",
            "candidate_version",
            "evidence_fingerprint_sha256",
            name=op.f(
                "uq_topic4_security_findings_tenant_id_verification_id_candidate_id_candidate_version_evidence_fingerprint_sha256"
            ),
        ),
    )
    op.create_index(
        "ix_topic4_security_findings_verification_severity",
        "topic4_security_findings",
        ["tenant_id", "verification_id", "severity", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic4_revision_plans",
        sa.Column("revision_plan_record_id", sa.UUID(), nullable=False),
        sa.Column("revision_plan_id", sa.UUID(), nullable=False),
        sa.Column("revision_cycle_id", sa.UUID(), nullable=False),
        sa.Column("revision_cycle_version", sa.BigInteger(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("base_candidate_version", sa.Integer(), nullable=False),
        sa.Column("base_candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("revision_round", sa.Integer(), nullable=False),
        sa.Column("target_agent", sa.String(length=24), nullable=False),
        sa.Column("plan_sha256", sa.String(length=64), nullable=False),
        sa.Column("plan_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_plans_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(plan_document) = 'object'",
            name=op.f("ck_topic4_revision_plans_document_object"),
        ),
        sa.CheckConstraint(
            "plan_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_plans_plan_sha256_format"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_plans_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_revision_plans_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_revision_plans_immutable_record")),
        sa.CheckConstraint(
            "revision_cycle_version >= 1",
            name=op.f("ck_topic4_revision_plans_positive_cycle_version"),
        ),
        sa.CheckConstraint(
            "revision_round BETWEEN 1 AND 2", name=op.f("ck_topic4_revision_plans_revision_round")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_revision_plans_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_revision_plans_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "revision_cycle_id", "revision_cycle_version"],
            [
                "topic4_revision_cycles.tenant_id",
                "topic4_revision_cycles.revision_cycle_id",
                "topic4_revision_cycles.cycle_version",
            ],
            name=op.f(
                "fk_topic4_revision_plans_tenant_id_revision_cycle_id_revision_cycle_version_topic4_revision_cycles"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_revision_plans_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("revision_plan_record_id", name=op.f("pk_topic4_revision_plans")),
        sa.UniqueConstraint(
            "tenant_id",
            "revision_cycle_id",
            "version_cas",
            name=op.f("uq_topic4_revision_plans_tenant_id_revision_cycle_id_version_cas"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "revision_plan_id",
            name=op.f("uq_topic4_revision_plans_tenant_id_revision_plan_id"),
        ),
    )
    op.create_table(
        "topic4_tokenized_values",
        sa.Column("tokenized_value_record_id", sa.UUID(), nullable=False),
        sa.Column("tokenized_value_id", sa.UUID(), nullable=False),
        sa.Column("pii_finding_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=132), nullable=False),
        sa.Column("original_value_sha256", sa.String(length=64), nullable=False),
        sa.Column("vault_reference", sa.String(length=512), nullable=False),
        sa.Column("key_version", sa.String(length=128), nullable=False),
        sa.Column("reversible", sa.Boolean(), nullable=False),
        sa.Column("token_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(token_document) = 'object'",
            name=op.f("ck_topic4_tokenized_values_document_object"),
        ),
        sa.CheckConstraint(
            "original_value_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_tokenized_values_original_value_sha256_format"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_tokenized_values_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "token ~ '^tok_[A-Za-z0-9_-]{16,128}$'",
            name=op.f("ck_topic4_tokenized_values_token_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_tokenized_values_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_tokenized_values_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_tokenized_values_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_tokenized_values_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "pii_finding_id"],
            ["topic4_pii_findings.tenant_id", "topic4_pii_findings.pii_finding_id"],
            name=op.f("fk_topic4_tokenized_values_tenant_id_pii_finding_id_topic4_pii_findings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_tokenized_values_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "tokenized_value_record_id", name=op.f("pk_topic4_tokenized_values")
        ),
        sa.UniqueConstraint(
            "tenant_id", "token", name=op.f("uq_topic4_tokenized_values_tenant_id_token")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "tokenized_value_id",
            name=op.f("uq_topic4_tokenized_values_tenant_id_tokenized_value_id"),
        ),
    )
    op.create_table(
        "topic4_release_authorizations",
        sa.Column("authorization_record_id", sa.UUID(), nullable=False),
        sa.Column("authorization_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("report_sha256", sa.String(length=64), nullable=False),
        sa.Column("release_mode", sa.String(length=32), nullable=False),
        sa.Column("allowed_block_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("one_time_use", sa.Boolean(), nullable=False),
        sa.Column(
            "authorization_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_release_authorizations_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(allowed_block_ids) = 'array'",
            name=op.f("ck_topic4_release_authorizations_blocks_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(authorization_document) = 'object'",
            name=op.f("ck_topic4_release_authorizations_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_release_authorizations_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "release_mode IN ('FULL', 'FULL_WITH_DISCLOSURE')",
            name=op.f("ck_topic4_release_authorizations_release_mode"),
        ),
        sa.CheckConstraint(
            "report_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_release_authorizations_report_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_release_authorizations_trace_id_format"),
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name=op.f("ck_topic4_release_authorizations_positive_candidate_version"),
        ),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_topic4_release_authorizations_expiry_window")
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_release_authorizations_immutable_record")
        ),
        sa.CheckConstraint(
            "one_time_use", name=op.f("ck_topic4_release_authorizations_one_time_use_required")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_release_authorizations_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_release_authorizations_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "report_id"],
            ["topic4_verification_reports.tenant_id", "topic4_verification_reports.report_id"],
            name=op.f(
                "fk_topic4_release_authorizations_tenant_id_report_id_topic4_verification_reports"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "verification_id"],
            ["topic4_verifications.tenant_id", "topic4_verifications.verification_id"],
            name=op.f(
                "fk_topic4_release_authorizations_tenant_id_verification_id_topic4_verifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_release_authorizations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "authorization_record_id", name=op.f("pk_topic4_release_authorizations")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "authorization_id",
            name=op.f("uq_topic4_release_authorizations_tenant_id_authorization_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "candidate_id",
            "candidate_version",
            "candidate_sha256",
            "report_sha256",
            name=op.f(
                "uq_topic4_release_authorizations_tenant_id_candidate_id_candidate_version_candidate_sha256_report_sha256"
            ),
        ),
    )
    op.create_index(
        "ix_topic4_release_authorizations_expiry",
        "topic4_release_authorizations",
        ["tenant_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "topic4_revision_patches",
        sa.Column("revision_patch_record_id", sa.UUID(), nullable=False),
        sa.Column("revision_patch_id", sa.UUID(), nullable=False),
        sa.Column("revision_plan_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=24), nullable=False),
        sa.Column("base_block_sha256", sa.String(length=64), nullable=False),
        sa.Column("replacement_sha256", sa.String(length=64), nullable=True),
        sa.Column("patch_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(operation = 'REPLACE_BLOCK' AND replacement_sha256 IS NOT NULL) OR "
            "(operation = 'REMOVE_BLOCK' AND replacement_sha256 IS NULL)",
            name=op.f("ck_topic4_revision_patches_replacement_semantics"),
        ),
        sa.CheckConstraint(
            "base_block_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_patches_base_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(patch_document) = 'object'",
            name=op.f("ck_topic4_revision_patches_document_object"),
        ),
        sa.CheckConstraint(
            "operation IN ('REPLACE_BLOCK', 'REMOVE_BLOCK')",
            name=op.f("ck_topic4_revision_patches_operation"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_patches_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "replacement_sha256 IS NULL OR replacement_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_revision_patches_replacement_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_revision_patches_trace_id_format"),
        ),
        sa.CheckConstraint("immutable", name=op.f("ck_topic4_revision_patches_immutable_record")),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_revision_patches_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_revision_patches_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "revision_plan_id"],
            ["topic4_revision_plans.tenant_id", "topic4_revision_plans.revision_plan_id"],
            name=op.f(
                "fk_topic4_revision_patches_tenant_id_revision_plan_id_topic4_revision_plans"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_revision_patches_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "revision_patch_record_id", name=op.f("pk_topic4_revision_patches")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "revision_patch_id",
            name=op.f("uq_topic4_revision_patches_tenant_id_revision_patch_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "revision_plan_id",
            "block_id",
            name=op.f("uq_topic4_revision_patches_tenant_id_revision_plan_id_block_id"),
        ),
    )
    op.create_table(
        "topic4_publication_batches",
        sa.Column("publication_batch_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("publication_batch_id", sa.UUID(), nullable=False),
        sa.Column("batch_version", sa.BigInteger(), nullable=False),
        sa.Column("authorization_id", sa.UUID(), nullable=False),
        sa.Column("verification_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("batch_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_publication_batches_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(batch_document) = 'object'",
            name=op.f("ck_topic4_publication_batches_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_publication_batches_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'COMMITTED', 'FAILED')",
            name=op.f("ck_topic4_publication_batches_state"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_publication_batches_trace_id_format"),
        ),
        sa.CheckConstraint(
            "batch_version >= 1", name=op.f("ck_topic4_publication_batches_positive_batch_version")
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name=op.f("ck_topic4_publication_batches_positive_candidate_version"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_publication_batches_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas = batch_version",
            name=op.f("ck_topic4_publication_batches_cas_matches_batch_version"),
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_publication_batches_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_publication_batches_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "authorization_id"],
            [
                "topic4_release_authorizations.tenant_id",
                "topic4_release_authorizations.authorization_id",
            ],
            name=op.f(
                "fk_topic4_publication_batches_tenant_id_authorization_id_topic4_release_authorizations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_publication_batches_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "publication_batch_snapshot_id", name=op.f("pk_topic4_publication_batches")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "publication_batch_id",
            "batch_version",
            name=op.f("uq_topic4_publication_batches_tenant_id_publication_batch_id_batch_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "publication_batch_snapshot_id",
            name=op.f("uq_topic4_publication_batches_tenant_id_publication_batch_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic4_publication_batches_authorization",
        "topic4_publication_batches",
        ["tenant_id", "authorization_id", "batch_version"],
        unique=False,
    )
    op.create_table(
        "topic4_release_authorization_consumptions",
        sa.Column("consumption_record_id", sa.UUID(), nullable=False),
        sa.Column("consumption_id", sa.UUID(), nullable=False),
        sa.Column("authorization_id", sa.UUID(), nullable=False),
        sa.Column("publication_batch_id", sa.UUID(), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("consumed_by_subject", sa.String(length=256), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumption_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(consumption_document) = 'object'",
            name=op.f("ck_topic4_release_authorization_consumptions_document_object"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_release_authorization_consumptions_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "request_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_release_authorization_consumptions_request_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_release_authorization_consumptions_trace_id_format"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_release_authorization_consumptions_immutable_record")
        ),
        sa.CheckConstraint(
            "version_cas >= 1",
            name=op.f("ck_topic4_release_authorization_consumptions_positive_version_cas"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_release_authorization_consumptions_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "authorization_id"],
            [
                "topic4_release_authorizations.tenant_id",
                "topic4_release_authorizations.authorization_id",
            ],
            name=op.f(
                "fk_topic4_release_authorization_consumptions_tenant_id_authorization_id_topic4_release_authorizations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_release_authorization_consumptions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "consumption_record_id", name=op.f("pk_topic4_release_authorization_consumptions")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "authorization_id",
            name=op.f("uq_topic4_release_authorization_consumptions_tenant_id_authorization_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "consumption_id",
            name=op.f("uq_topic4_release_authorization_consumptions_tenant_id_consumption_id"),
        ),
    )
    op.create_table(
        "topic4_public_stream_events",
        sa.Column("public_event_record_id", sa.UUID(), nullable=False),
        sa.Column("public_event_id", sa.UUID(), nullable=False),
        sa.Column("publication_batch_id", sa.UUID(), nullable=False),
        sa.Column("publication_batch_version", sa.BigInteger(), nullable=False),
        sa.Column("authorization_id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("event_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("emitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("version_cas", sa.BigInteger(), nullable=False),
        sa.Column("record_sha256", sa.String(length=64), nullable=False),
        sa.Column("immutable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(event_document) = 'object'",
            name=op.f("ck_topic4_public_stream_events_document_object"),
        ),
        sa.CheckConstraint(
            "payload_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_public_stream_events_payload_sha256_format"),
        ),
        sa.CheckConstraint(
            "record_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic4_public_stream_events_record_sha256_format"),
        ),
        sa.CheckConstraint(
            "trace_id ~ '^[0-9a-fA-F]{16,64}$'",
            name=op.f("ck_topic4_public_stream_events_trace_id_format"),
        ),
        sa.CheckConstraint(
            "immutable", name=op.f("ck_topic4_public_stream_events_immutable_record")
        ),
        sa.CheckConstraint(
            "publication_batch_version >= 1",
            name=op.f("ck_topic4_public_stream_events_positive_batch_version"),
        ),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_topic4_public_stream_events_nonnegative_sequence")
        ),
        sa.CheckConstraint(
            "version_cas >= 1", name=op.f("ck_topic4_public_stream_events_positive_version_cas")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic4_public_stream_events_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "publication_batch_id", "publication_batch_version"],
            [
                "topic4_publication_batches.tenant_id",
                "topic4_publication_batches.publication_batch_id",
                "topic4_publication_batches.batch_version",
            ],
            name=op.f(
                "fk_topic4_public_stream_events_tenant_id_publication_batch_id_publication_batch_version_topic4_publication_batches"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic4_public_stream_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "public_event_record_id", name=op.f("pk_topic4_public_stream_events")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "public_event_id",
            name=op.f("uq_topic4_public_stream_events_tenant_id_public_event_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "stream_id",
            "sequence",
            name=op.f("uq_topic4_public_stream_events_tenant_id_stream_id_sequence"),
        ),
    )
    op.create_index(
        "ix_topic4_public_stream_emitted",
        "topic4_public_stream_events",
        ["tenant_id", "emitted_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic4_public_stream_order",
        "topic4_public_stream_events",
        ["tenant_id", "stream_id", "sequence"],
        unique=False,
    )
    for table_name in TOPIC4_REVISION_RELEASE_TABLES:
        _install_tenant_policy(table_name)
        _install_append_only_trigger(table_name)
    _grant_runtime_privileges()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in TOPIC4_REVISION_RELEASE_TABLES:
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{table_name}_append_only ON {table_name}"))
    op.drop_index("ix_topic4_public_stream_order", table_name="topic4_public_stream_events")
    op.drop_index("ix_topic4_public_stream_emitted", table_name="topic4_public_stream_events")
    op.drop_table("topic4_public_stream_events")
    op.drop_table("topic4_release_authorization_consumptions")
    op.drop_index(
        "ix_topic4_publication_batches_authorization", table_name="topic4_publication_batches"
    )
    op.drop_table("topic4_publication_batches")
    op.drop_table("topic4_revision_patches")
    op.drop_index(
        "ix_topic4_release_authorizations_expiry", table_name="topic4_release_authorizations"
    )
    op.drop_table("topic4_release_authorizations")
    op.drop_table("topic4_tokenized_values")
    op.drop_table("topic4_revision_plans")
    op.drop_index(
        "ix_topic4_security_findings_verification_severity", table_name="topic4_security_findings"
    )
    op.drop_table("topic4_security_findings")
    op.drop_index("ix_topic4_revision_cycles_verification", table_name="topic4_revision_cycles")
    op.drop_table("topic4_revision_cycles")
    op.drop_table("topic4_privacy_tenant_results")
    op.drop_index("ix_topic4_pii_findings_verification", table_name="topic4_pii_findings")
    op.drop_table("topic4_pii_findings")
    op.drop_index("ix_topic4_vulnerabilities_open", table_name="topic4_vulnerability_records")
    op.drop_table("topic4_vulnerability_records")
    op.drop_table("topic4_sbom_components")
    op.drop_table("topic4_build_provenance")
    op.drop_table("topic4_acceptance_gate_results")
    op.drop_index("ix_topic4_sbom_manifests_code", table_name="topic4_sbom_manifests")
    op.drop_table("topic4_sbom_manifests")
    op.drop_index("ix_topic4_acceptance_reports_build", table_name="topic4_acceptance_reports")
    op.drop_table("topic4_acceptance_reports")
    # ### end Alembic commands ###
