"""create topic 2 adaptive learning runtime

Revision ID: 20260715_0005
Revises: 20260715_0004
Create Date: 2026-07-15 22:41:32.968036
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260715_0005"
down_revision: str | Sequence[str] | None = "20260715_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOPIC2_TENANT_TABLES = (
    "topic2_student_profiles",
    "topic2_profile_features",
    "topic2_learning_behavior_events",
    "topic2_memory_states",
    "topic2_learning_path_snapshots",
    "topic2_path_change_logs",
)


def _install_tenant_policy(table_name: str) -> None:
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')"
    op.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    )


def _install_append_only_trigger(table_name: str) -> None:
    op.execute(
        sa.text(
            f"CREATE TRIGGER trg_{table_name}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION reject_topic2_history_mutation()"
        )
    )


def _grant_runtime_privileges() -> None:
    all_tables = ", ".join(TOPIC2_TENANT_TABLES)
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM PUBLIC';
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liyans_app') THEN
                    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM liyans_app';
                    EXECUTE 'GRANT SELECT, INSERT ON TABLE {all_tables} TO liyans_app';
                END IF;
            END
            $$
            """
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic2_student_profiles",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("learner_ref", sa.String(length=256), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("profile_version", sa.BigInteger(), nullable=False),
        sa.Column("parent_profile_id", sa.UUID(), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_mastery", sa.Float(), nullable=False),
        sa.Column("problem_solving_proficiency", sa.Float(), nullable=False),
        sa.Column("misconception_preference", sa.Float(), nullable=False),
        sa.Column("learning_pace", sa.Float(), nullable=False),
        sa.Column("forgetting_rate", sa.Float(), nullable=False),
        sa.Column("learning_goal_tendency", sa.Float(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("activity_count", sa.BigInteger(), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("profile_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic2_student_profiles_content_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(profile_document) = 'object'",
            name=op.f("ck_topic2_student_profiles_profile_document_object"),
        ),
        sa.CheckConstraint(
            "activity_count >= 0",
            name=op.f("ck_topic2_student_profiles_nonnegative_activity_count"),
        ),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0 AND 1",
            name=op.f("ck_topic2_student_profiles_confidence_score"),
        ),
        sa.CheckConstraint(
            "forgetting_rate BETWEEN 0 AND 1",
            name=op.f("ck_topic2_student_profiles_forgetting_rate"),
        ),
        sa.CheckConstraint(
            "knowledge_mastery BETWEEN 0 AND 1",
            name=op.f("ck_topic2_student_profiles_knowledge_mastery"),
        ),
        sa.CheckConstraint(
            "learning_goal_tendency BETWEEN 0 AND 1",
            name=op.f("ck_topic2_student_profiles_learning_goal_tendency"),
        ),
        sa.CheckConstraint(
            "learning_pace BETWEEN 0 AND 1", name=op.f("ck_topic2_student_profiles_learning_pace")
        ),
        sa.CheckConstraint(
            "misconception_preference BETWEEN 0 AND 1",
            name=op.f("ck_topic2_student_profiles_misconception_preference"),
        ),
        sa.CheckConstraint(
            "problem_solving_proficiency BETWEEN 0 AND 1",
            name=op.f("ck_topic2_student_profiles_problem_solving_proficiency"),
        ),
        sa.CheckConstraint(
            "profile_version >= 1", name=op.f("ck_topic2_student_profiles_positive_profile_version")
        ),
        sa.CheckConstraint(
            "source_window_start IS NULL OR source_window_end IS NULL "
            "OR source_window_end >= source_window_start",
            name=op.f("ck_topic2_student_profiles_source_window_order"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic2_student_profiles_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id"],
            ["topic1_courses.tenant_id", "topic1_courses.course_id"],
            name=op.f("fk_topic2_student_profiles_tenant_id_course_id_topic1_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_profile_id", "learner_ref", "course_id"],
            [
                "topic2_student_profiles.tenant_id",
                "topic2_student_profiles.profile_id",
                "topic2_student_profiles.learner_ref",
                "topic2_student_profiles.course_id",
            ],
            name=op.f(
                "fk_topic2_student_profiles_tenant_id_parent_profile_id_learner_ref_course_id_topic2_student_profiles"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic2_student_profiles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_topic2_student_profiles")),
        sa.UniqueConstraint(
            "tenant_id",
            "learner_ref",
            "course_id",
            "profile_version",
            name=op.f("uq_topic2_student_profiles_tenant_id_learner_ref_course_id_profile_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "profile_id",
            "learner_ref",
            "course_id",
            name=op.f("uq_topic2_student_profiles_tenant_id_profile_id_learner_ref_course_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id", "profile_id", name=op.f("uq_topic2_student_profiles_tenant_id_profile_id")
        ),
    )
    op.create_index(
        "ix_topic2_student_profiles_course_frozen",
        "topic2_student_profiles",
        ["tenant_id", "course_id", "frozen_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic2_student_profiles_learner_version",
        "topic2_student_profiles",
        ["tenant_id", "learner_ref", "course_id", "profile_version"],
        unique=False,
    )
    op.create_table(
        "topic2_learning_behavior_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("source_event_id", sa.String(length=160), nullable=False),
        sa.Column("event_version", sa.BigInteger(), nullable=False),
        sa.Column("learner_ref", sa.String(length=256), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("kp_id", sa.String(length=120), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("response_latency_ms", sa.Integer(), nullable=True),
        sa.Column("correctness", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("interaction_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("attention_ratio", sa.Float(), nullable=True),
        sa.Column(
            "misconception_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "goal_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('ANSWER_SUBMITTED', 'RESOURCE_VIEWED', "
            "'SIMULATION_RUN', 'REVIEW_COMPLETED', 'CODE_EXECUTED', "
            "'SESSION_FOCUSED', 'GOAL_SELECTED')",
            name=op.f("ck_topic2_learning_behavior_events_event_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(goal_tags) = 'array'",
            name=op.f("ck_topic2_learning_behavior_events_goal_tags_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(misconception_ids) = 'array'",
            name=op.f("ck_topic2_learning_behavior_events_misconception_ids_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'",
            name=op.f("ck_topic2_learning_behavior_events_payload_object"),
        ),
        sa.CheckConstraint(
            "payload_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic2_learning_behavior_events_payload_sha256_format"),
        ),
        sa.CheckConstraint(
            "source_type IN ('LEARNER_UI', 'LECTURER', 'MINDMAP', 'TESTER', "
            "'CODE_SANDBOX', 'EXTENSION', 'SYSTEM')",
            name=op.f("ck_topic2_learning_behavior_events_source_type"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name=op.f("ck_topic2_learning_behavior_events_nonnegative_attempt_count"),
        ),
        sa.CheckConstraint(
            "attention_ratio IS NULL OR attention_ratio BETWEEN 0 AND 1",
            name=op.f("ck_topic2_learning_behavior_events_attention_ratio"),
        ),
        sa.CheckConstraint(
            "correctness IS NULL OR correctness BETWEEN 0 AND 1",
            name=op.f("ck_topic2_learning_behavior_events_correctness"),
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds BETWEEN 0 AND 86400",
            name=op.f("ck_topic2_learning_behavior_events_duration_seconds"),
        ),
        sa.CheckConstraint(
            "event_version >= 1",
            name=op.f("ck_topic2_learning_behavior_events_positive_event_version"),
        ),
        sa.CheckConstraint(
            "interaction_count >= 0",
            name=op.f("ck_topic2_learning_behavior_events_nonnegative_interaction_count"),
        ),
        sa.CheckConstraint(
            "response_latency_ms IS NULL OR response_latency_ms BETWEEN 0 AND 86400000",
            name=op.f("ck_topic2_learning_behavior_events_response_latency_ms"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR score BETWEEN 0 AND 1",
            name=op.f("ck_topic2_learning_behavior_events_score"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic2_learning_behavior_events_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id", "kp_id"],
            [
                "topic1_knowledge_points.tenant_id",
                "topic1_knowledge_points.course_id",
                "topic1_knowledge_points.kp_id",
            ],
            name=op.f(
                "fk_topic2_learning_behavior_events_tenant_id_course_id_kp_id_topic1_knowledge_points"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id"],
            ["topic1_courses.tenant_id", "topic1_courses.course_id"],
            name=op.f("fk_topic2_learning_behavior_events_tenant_id_course_id_topic1_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic2_learning_behavior_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_topic2_learning_behavior_events")),
        sa.UniqueConstraint(
            "tenant_id",
            "event_id",
            name=op.f("uq_topic2_learning_behavior_events_tenant_id_event_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "source_event_id",
            name=op.f("uq_topic2_learning_behavior_events_tenant_id_source_event_id"),
        ),
    )
    op.create_index(
        "ix_topic2_behavior_kp_occurred",
        "topic2_learning_behavior_events",
        ["tenant_id", "course_id", "kp_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic2_behavior_learner_occurred",
        "topic2_learning_behavior_events",
        ["tenant_id", "learner_ref", "course_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic2_behavior_learner_received",
        "topic2_learning_behavior_events",
        ["tenant_id", "learner_ref", "course_id", "received_at", "event_id"],
        unique=False,
    )
    op.create_table(
        "topic2_learning_path_snapshots",
        sa.Column("path_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("learner_ref", sa.String(length=256), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("path_version", sa.BigInteger(), nullable=False),
        sa.Column("parent_path_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("topic1_graph_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("topic1_graph_version", sa.BigInteger(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("plan_type", sa.String(length=24), nullable=False),
        sa.Column("trigger_reason", sa.String(length=128), nullable=False),
        sa.Column("target_goal", sa.String(length=512), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("path_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("manual_override", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic2_learning_path_snapshots_content_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(decision_document) = 'object'",
            name=op.f("ck_topic2_learning_path_snapshots_decision_document_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(path_document) = 'object'",
            name=op.f("ck_topic2_learning_path_snapshots_path_document_object"),
        ),
        sa.CheckConstraint(
            "plan_type IN ('INITIAL', 'REPLANNED', 'MANUAL_OVERRIDE', 'RESTORED')",
            name=op.f("ck_topic2_learning_path_snapshots_plan_type"),
        ),
        sa.CheckConstraint(
            "estimated_minutes >= 0",
            name=op.f("ck_topic2_learning_path_snapshots_nonnegative_estimated_minutes"),
        ),
        sa.CheckConstraint(
            "node_count >= 0", name=op.f("ck_topic2_learning_path_snapshots_nonnegative_node_count")
        ),
        sa.CheckConstraint(
            "path_version >= 1",
            name=op.f("ck_topic2_learning_path_snapshots_positive_path_version"),
        ),
        sa.CheckConstraint(
            "topic1_graph_version >= 1",
            name=op.f("ck_topic2_learning_path_snapshots_positive_graph_version"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic2_learning_path_snapshots_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id"],
            ["topic1_courses.tenant_id", "topic1_courses.course_id"],
            name=op.f("fk_topic2_learning_path_snapshots_tenant_id_course_id_topic1_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_path_snapshot_id", "learner_ref", "course_id"],
            [
                "topic2_learning_path_snapshots.tenant_id",
                "topic2_learning_path_snapshots.path_snapshot_id",
                "topic2_learning_path_snapshots.learner_ref",
                "topic2_learning_path_snapshots.course_id",
            ],
            name=op.f(
                "fk_topic2_learning_path_snapshots_tenant_id_parent_path_snapshot_id_learner_ref_course_id_topic2_learning_path_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "profile_id", "learner_ref", "course_id"],
            [
                "topic2_student_profiles.tenant_id",
                "topic2_student_profiles.profile_id",
                "topic2_student_profiles.learner_ref",
                "topic2_student_profiles.course_id",
            ],
            name=op.f(
                "fk_topic2_learning_path_snapshots_tenant_id_profile_id_learner_ref_course_id_topic2_student_profiles"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "topic1_graph_snapshot_id"],
            ["topic1_graph_snapshots.tenant_id", "topic1_graph_snapshots.snapshot_id"],
            name=op.f(
                "fk_topic2_learning_path_snapshots_tenant_id_topic1_graph_snapshot_id_topic1_graph_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic2_learning_path_snapshots_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("path_snapshot_id", name=op.f("pk_topic2_learning_path_snapshots")),
        sa.UniqueConstraint(
            "tenant_id",
            "learner_ref",
            "course_id",
            "path_version",
            name=op.f(
                "uq_topic2_learning_path_snapshots_tenant_id_learner_ref_course_id_path_version"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "path_snapshot_id",
            "learner_ref",
            "course_id",
            name=op.f(
                "uq_topic2_learning_path_snapshots_tenant_id_path_snapshot_id_learner_ref_course_id"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "path_snapshot_id",
            name=op.f("uq_topic2_learning_path_snapshots_tenant_id_path_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic2_paths_graph_snapshot",
        "topic2_learning_path_snapshots",
        ["tenant_id", "topic1_graph_snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_topic2_paths_learner_version",
        "topic2_learning_path_snapshots",
        ["tenant_id", "learner_ref", "course_id", "path_version"],
        unique=False,
    )
    op.create_table(
        "topic2_memory_states",
        sa.Column("memory_state_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("learner_ref", sa.String(length=256), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("kp_id", sa.String(length=120), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("parent_memory_state_id", sa.UUID(), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("stability_days", sa.Float(), nullable=False),
        sa.Column("effective_stability_days", sa.Float(), nullable=False),
        sa.Column("elapsed_days", sa.Float(), nullable=False),
        sa.Column("retrievability", sa.Float(), nullable=False),
        sa.Column("forgetting_rate", sa.Float(), nullable=False),
        sa.Column("difficulty_factor", sa.Float(), nullable=False),
        sa.Column("review_gain", sa.Float(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("lapse_count", sa.Integer(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("model_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic2_memory_states_content_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(model_parameters) = 'object'",
            name=op.f("ck_topic2_memory_states_model_parameters_object"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_topic2_memory_states_risk_level"),
        ),
        sa.CheckConstraint(
            "difficulty_factor BETWEEN 0.25 AND 4",
            name=op.f("ck_topic2_memory_states_difficulty_factor"),
        ),
        sa.CheckConstraint(
            "effective_stability_days > 0 AND effective_stability_days <= 36500",
            name=op.f("ck_topic2_memory_states_effective_stability_days"),
        ),
        sa.CheckConstraint(
            "elapsed_days >= 0", name=op.f("ck_topic2_memory_states_nonnegative_elapsed_days")
        ),
        sa.CheckConstraint(
            "forgetting_rate BETWEEN 0 AND 1", name=op.f("ck_topic2_memory_states_forgetting_rate")
        ),
        sa.CheckConstraint(
            "lapse_count <= review_count",
            name=op.f("ck_topic2_memory_states_lapse_not_above_review"),
        ),
        sa.CheckConstraint(
            "lapse_count >= 0", name=op.f("ck_topic2_memory_states_nonnegative_lapse_count")
        ),
        sa.CheckConstraint(
            "retrievability BETWEEN 0 AND 1", name=op.f("ck_topic2_memory_states_retrievability")
        ),
        sa.CheckConstraint(
            "review_count >= 0", name=op.f("ck_topic2_memory_states_nonnegative_review_count")
        ),
        sa.CheckConstraint(
            "review_gain >= 0 AND review_gain <= 16",
            name=op.f("ck_topic2_memory_states_review_gain"),
        ),
        sa.CheckConstraint(
            "stability_days > 0 AND stability_days <= 36500",
            name=op.f("ck_topic2_memory_states_stability_days"),
        ),
        sa.CheckConstraint(
            "state_version >= 1", name=op.f("ck_topic2_memory_states_positive_state_version")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic2_memory_states_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "course_id", "kp_id"],
            [
                "topic1_knowledge_points.tenant_id",
                "topic1_knowledge_points.course_id",
                "topic1_knowledge_points.kp_id",
            ],
            name=op.f("fk_topic2_memory_states_tenant_id_course_id_kp_id_topic1_knowledge_points"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_memory_state_id", "learner_ref", "course_id", "kp_id"],
            [
                "topic2_memory_states.tenant_id",
                "topic2_memory_states.memory_state_id",
                "topic2_memory_states.learner_ref",
                "topic2_memory_states.course_id",
                "topic2_memory_states.kp_id",
            ],
            name=op.f(
                "fk_topic2_memory_states_tenant_id_parent_memory_state_id_learner_ref_course_id_kp_id_topic2_memory_states"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic2_memory_states_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("memory_state_id", name=op.f("pk_topic2_memory_states")),
        sa.UniqueConstraint(
            "tenant_id",
            "learner_ref",
            "course_id",
            "kp_id",
            "state_version",
            name=op.f(
                "uq_topic2_memory_states_tenant_id_learner_ref_course_id_kp_id_state_version"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "memory_state_id",
            "learner_ref",
            "course_id",
            "kp_id",
            name=op.f(
                "uq_topic2_memory_states_tenant_id_memory_state_id_learner_ref_course_id_kp_id"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "memory_state_id",
            name=op.f("uq_topic2_memory_states_tenant_id_memory_state_id"),
        ),
    )
    op.create_index(
        "ix_topic2_memory_learner_kp_version",
        "topic2_memory_states",
        ["tenant_id", "learner_ref", "course_id", "kp_id", "state_version"],
        unique=False,
    )
    op.create_index(
        "ix_topic2_memory_review_due",
        "topic2_memory_states",
        ["tenant_id", "next_review_at", "risk_level"],
        unique=False,
    )
    op.create_table(
        "topic2_profile_features",
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("dimension", sa.String(length=48), nullable=False),
        sa.Column("feature_key", sa.String(length=160), nullable=False),
        sa.Column("value_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_event_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dimension IN ('KNOWLEDGE_MASTERY', 'PROBLEM_SOLVING_PROFICIENCY', "
            "'MISCONCEPTION_PREFERENCE', 'LEARNING_PACE', 'FORGETTING_RATE', "
            "'LEARNING_GOAL_TENDENCY')",
            name=op.f("ck_topic2_profile_features_dimension"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(source_event_ids) = 'array'",
            name=op.f("ck_topic2_profile_features_source_event_ids_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(value_document) = 'object'",
            name=op.f("ck_topic2_profile_features_value_document_object"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_topic2_profile_features_confidence")
        ),
        sa.CheckConstraint(
            "evidence_count >= 0",
            name=op.f("ck_topic2_profile_features_nonnegative_evidence_count"),
        ),
        sa.CheckConstraint(
            "normalized_score BETWEEN 0 AND 1",
            name=op.f("ck_topic2_profile_features_normalized_score"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic2_profile_features_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "profile_id"],
            ["topic2_student_profiles.tenant_id", "topic2_student_profiles.profile_id"],
            name=op.f("fk_topic2_profile_features_tenant_id_profile_id_topic2_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic2_profile_features_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("feature_id", name=op.f("pk_topic2_profile_features")),
        sa.UniqueConstraint(
            "tenant_id", "feature_id", name=op.f("uq_topic2_profile_features_tenant_id_feature_id")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "profile_id",
            "dimension",
            "feature_key",
            name=op.f("uq_topic2_profile_features_tenant_id_profile_id_dimension_feature_key"),
        ),
    )
    op.create_index(
        "ix_topic2_profile_features_profile_dimension",
        "topic2_profile_features",
        ["tenant_id", "profile_id", "dimension"],
        unique=False,
    )
    op.create_table(
        "topic2_path_change_logs",
        sa.Column("change_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("learner_ref", sa.String(length=256), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("from_path_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("to_path_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("change_type", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("change_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_type IN ('INITIALIZED', 'MEMORY_RISK', 'MASTERY_DEFICIT', "
            "'MISCONCEPTION', 'GOAL_CHANGED', 'MANUAL_OVERRIDE', "
            "'TOPOLOGY_REPAIRED', 'RESTORED')",
            name=op.f("ck_topic2_path_change_logs_change_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(change_document) = 'object'",
            name=op.f("ck_topic2_path_change_logs_change_document_object"),
        ),
        sa.CheckConstraint(
            "from_path_snapshot_id IS NULL OR from_path_snapshot_id <> to_path_snapshot_id",
            name=op.f("ck_topic2_path_change_logs_distinct_path_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic2_path_change_logs_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "from_path_snapshot_id", "learner_ref", "course_id"],
            [
                "topic2_learning_path_snapshots.tenant_id",
                "topic2_learning_path_snapshots.path_snapshot_id",
                "topic2_learning_path_snapshots.learner_ref",
                "topic2_learning_path_snapshots.course_id",
            ],
            name=op.f(
                "fk_topic2_path_change_logs_tenant_id_from_path_snapshot_id_learner_ref_course_id_topic2_learning_path_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "to_path_snapshot_id", "learner_ref", "course_id"],
            [
                "topic2_learning_path_snapshots.tenant_id",
                "topic2_learning_path_snapshots.path_snapshot_id",
                "topic2_learning_path_snapshots.learner_ref",
                "topic2_learning_path_snapshots.course_id",
            ],
            name=op.f(
                "fk_topic2_path_change_logs_tenant_id_to_path_snapshot_id_learner_ref_course_id_topic2_learning_path_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic2_path_change_logs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_topic2_path_change_logs")),
        sa.UniqueConstraint(
            "tenant_id", "change_id", name=op.f("uq_topic2_path_change_logs_tenant_id_change_id")
        ),
    )
    op.create_index(
        "ix_topic2_path_changes_learner_occurred",
        "topic2_path_change_logs",
        ["tenant_id", "learner_ref", "course_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic2_path_changes_to_snapshot",
        "topic2_path_change_logs",
        ["tenant_id", "to_path_snapshot_id"],
        unique=False,
    )
    for table_name in TOPIC2_TENANT_TABLES:
        _install_tenant_policy(table_name)
    op.execute(
        sa.text(
            """
            CREATE FUNCTION reject_topic2_history_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION USING
                    ERRCODE = '55000',
                    MESSAGE = TG_TABLE_NAME || ' is append-only';
            END
            $$
            """
        )
    )
    for table_name in TOPIC2_TENANT_TABLES:
        _install_append_only_trigger(table_name)
    _grant_runtime_privileges()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in reversed(TOPIC2_TENANT_TABLES):
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{table_name}_append_only ON {table_name}"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS reject_topic2_history_mutation()"))
    op.drop_index("ix_topic2_path_changes_to_snapshot", table_name="topic2_path_change_logs")
    op.drop_index("ix_topic2_path_changes_learner_occurred", table_name="topic2_path_change_logs")
    op.drop_table("topic2_path_change_logs")
    op.drop_index(
        "ix_topic2_profile_features_profile_dimension", table_name="topic2_profile_features"
    )
    op.drop_table("topic2_profile_features")
    op.drop_index("ix_topic2_memory_review_due", table_name="topic2_memory_states")
    op.drop_index("ix_topic2_memory_learner_kp_version", table_name="topic2_memory_states")
    op.drop_table("topic2_memory_states")
    op.drop_index("ix_topic2_paths_learner_version", table_name="topic2_learning_path_snapshots")
    op.drop_index("ix_topic2_paths_graph_snapshot", table_name="topic2_learning_path_snapshots")
    op.drop_table("topic2_learning_path_snapshots")
    op.drop_index(
        "ix_topic2_behavior_learner_received", table_name="topic2_learning_behavior_events"
    )
    op.drop_index(
        "ix_topic2_behavior_learner_occurred", table_name="topic2_learning_behavior_events"
    )
    op.drop_index("ix_topic2_behavior_kp_occurred", table_name="topic2_learning_behavior_events")
    op.drop_table("topic2_learning_behavior_events")
    op.drop_index(
        "ix_topic2_student_profiles_learner_version", table_name="topic2_student_profiles"
    )
    op.drop_index("ix_topic2_student_profiles_course_frozen", table_name="topic2_student_profiles")
    op.drop_table("topic2_student_profiles")
    # ### end Alembic commands ###
