"""create topic 3 agent cluster runtime

Revision ID: 20260716_0006
Revises: 20260715_0005
Create Date: 2026-07-16 02:03:55.251144
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260716_0006"
down_revision: str | Sequence[str] | None = "20260715_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOPIC3_TENANT_TABLES = (
    "topic3_generation_sessions",
    "topic3_execution_blueprints",
    "topic3_agent_tasks",
    "topic3_generated_candidates",
    "topic3_model_invocations",
    "topic3_stream_chunks",
)


def _install_tenant_policy(table_name: str) -> None:
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')"
    op.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    )


def _install_append_only_trigger(table_name: str) -> None:
    op.execute(
        sa.text(
            f"CREATE TRIGGER trg_{table_name}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION reject_topic3_history_mutation()"
        )
    )


def _grant_runtime_privileges() -> None:
    all_tables = ", ".join(TOPIC3_TENANT_TABLES)
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM PUBLIC';
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liyans_app') THEN
                    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE {all_tables} FROM liyans_app';
                    EXECUTE 'GRANT SELECT, INSERT ON TABLE {all_tables} TO liyans_app';
                END IF;
            END
            $$
            """
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic3_generation_sessions",
        sa.Column("session_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("generation_session_id", sa.UUID(), nullable=False),
        sa.Column("session_version", sa.BigInteger(), nullable=False),
        sa.Column("parent_session_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("learner_ref", sa.String(length=256), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("topic1_graph_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("topic1_graph_version", sa.BigInteger(), nullable=False),
        sa.Column("topic2_profile_id", sa.UUID(), nullable=False),
        sa.Column("topic2_profile_version", sa.BigInteger(), nullable=False),
        sa.Column("topic2_path_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("topic2_path_version", sa.BigInteger(), nullable=False),
        sa.Column("personalization_policy_digest", sa.String(length=64), nullable=False),
        sa.Column("requested_resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("request_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "result_document",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_generation_sessions_content_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(request_document) = 'object'",
            name=op.f("ck_topic3_generation_sessions_request_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(requested_resources) = 'array'",
            name=op.f("ck_topic3_generation_sessions_resources_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(result_document) = 'object'",
            name=op.f("ck_topic3_generation_sessions_result_object"),
        ),
        sa.CheckConstraint(
            "personalization_policy_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_generation_sessions_personalization_digest_format"),
        ),
        sa.CheckConstraint(
            "state IN ('PLANNED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED')",
            name=op.f("ck_topic3_generation_sessions_state"),
        ),
        sa.CheckConstraint(
            "session_version >= 1",
            name=op.f("ck_topic3_generation_sessions_positive_session_version"),
        ),
        sa.CheckConstraint(
            "topic1_graph_version >= 1",
            name=op.f("ck_topic3_generation_sessions_positive_graph_version"),
        ),
        sa.CheckConstraint(
            "topic2_path_version >= 1",
            name=op.f("ck_topic3_generation_sessions_positive_path_version"),
        ),
        sa.CheckConstraint(
            "topic2_profile_version >= 1",
            name=op.f("ck_topic3_generation_sessions_positive_profile_version"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic3_generation_sessions_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_session_snapshot_id"],
            [
                "topic3_generation_sessions.tenant_id",
                "topic3_generation_sessions.session_snapshot_id",
            ],
            name=op.f(
                "fk_topic3_generation_sessions_tenant_id_parent_session_snapshot_id_topic3_generation_sessions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "topic1_graph_snapshot_id"],
            ["topic1_graph_snapshots.tenant_id", "topic1_graph_snapshots.snapshot_id"],
            name=op.f(
                "fk_topic3_generation_sessions_tenant_id_topic1_graph_snapshot_id_topic1_graph_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "topic2_path_snapshot_id"],
            [
                "topic2_learning_path_snapshots.tenant_id",
                "topic2_learning_path_snapshots.path_snapshot_id",
            ],
            name=op.f(
                "fk_topic3_generation_sessions_tenant_id_topic2_path_snapshot_id_topic2_learning_path_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "topic2_profile_id"],
            ["topic2_student_profiles.tenant_id", "topic2_student_profiles.profile_id"],
            name=op.f(
                "fk_topic3_generation_sessions_tenant_id_topic2_profile_id_topic2_student_profiles"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic3_generation_sessions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("session_snapshot_id", name=op.f("pk_topic3_generation_sessions")),
        sa.UniqueConstraint(
            "tenant_id",
            "generation_session_id",
            "session_version",
            name=op.f(
                "uq_topic3_generation_sessions_tenant_id_generation_session_id_session_version"
            ),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "session_snapshot_id",
            name=op.f("uq_topic3_generation_sessions_tenant_id_session_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic3_sessions_learner_created",
        "topic3_generation_sessions",
        ["tenant_id", "learner_ref", "course_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic3_sessions_logical_version",
        "topic3_generation_sessions",
        ["tenant_id", "generation_session_id", "session_version"],
        unique=False,
    )
    op.create_table(
        "topic3_execution_blueprints",
        sa.Column("blueprint_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("blueprint_id", sa.UUID(), nullable=False),
        sa.Column("blueprint_version", sa.String(length=64), nullable=False),
        sa.Column("generation_session_id", sa.UUID(), nullable=False),
        sa.Column("generation_session_version", sa.BigInteger(), nullable=False),
        sa.Column("personalization_policy_digest", sa.String(length=64), nullable=False),
        sa.Column("max_parallelism", sa.Integer(), nullable=False),
        sa.Column("step_count", sa.Integer(), nullable=False),
        sa.Column("activation_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("steps_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("blueprint_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("blueprint_sha256", sa.String(length=64), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("created_by_subject", sa.String(length=256), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "blueprint_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_execution_blueprints_blueprint_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(activation_document) = 'object'",
            name=op.f("ck_topic3_execution_blueprints_activation_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(blueprint_document) = 'object'",
            name=op.f("ck_topic3_execution_blueprints_blueprint_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(steps_document) = 'array'",
            name=op.f("ck_topic3_execution_blueprints_steps_array"),
        ),
        sa.CheckConstraint(
            "personalization_policy_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_execution_blueprints_personalization_digest_format"),
        ),
        sa.CheckConstraint(
            "generation_session_version >= 1",
            name=op.f("ck_topic3_execution_blueprints_positive_session_version"),
        ),
        sa.CheckConstraint(
            "max_parallelism BETWEEN 1 AND 5",
            name=op.f("ck_topic3_execution_blueprints_parallelism_range"),
        ),
        sa.CheckConstraint(
            "step_count BETWEEN 1 AND 5",
            name=op.f("ck_topic3_execution_blueprints_step_count_range"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic3_execution_blueprints_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "generation_session_id", "generation_session_version"],
            [
                "topic3_generation_sessions.tenant_id",
                "topic3_generation_sessions.generation_session_id",
                "topic3_generation_sessions.session_version",
            ],
            name=op.f(
                "fk_topic3_execution_blueprints_tenant_id_generation_session_id_generation_session_version_topic3_generation_sessions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic3_execution_blueprints_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "blueprint_snapshot_id", name=op.f("pk_topic3_execution_blueprints")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "blueprint_id",
            "blueprint_version",
            name=op.f("uq_topic3_execution_blueprints_tenant_id_blueprint_id_blueprint_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "blueprint_snapshot_id",
            name=op.f("uq_topic3_execution_blueprints_tenant_id_blueprint_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_topic3_blueprints_session_version",
        "topic3_execution_blueprints",
        ["tenant_id", "generation_session_id", "generation_session_version"],
        unique=False,
    )
    op.create_table(
        "topic3_agent_tasks",
        sa.Column("task_record_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("task_version", sa.BigInteger(), nullable=False),
        sa.Column("blueprint_id", sa.UUID(), nullable=False),
        sa.Column("blueprint_version", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=24), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("dependency_task_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("request_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "result_document",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "error_document",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("result_sha256", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "agent IN ('Lecturer', 'MindMap', 'Tester', 'CodeSandbox', 'Extension')",
            name=op.f("ck_topic3_agent_tasks_agent"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(dependency_task_ids) = 'array'",
            name=op.f("ck_topic3_agent_tasks_dependencies_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(error_document) = 'object'",
            name=op.f("ck_topic3_agent_tasks_error_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(request_document) = 'object'",
            name=op.f("ck_topic3_agent_tasks_request_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(result_document) = 'object'",
            name=op.f("ck_topic3_agent_tasks_result_object"),
        ),
        sa.CheckConstraint(
            "request_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_agent_tasks_request_sha256_format"),
        ),
        sa.CheckConstraint(
            "resource_type IN ('Lecturer_Doc', 'MindMap', 'Gradient_Quiz', "
            "'Simulation_Code', 'Extension_Material')",
            name=op.f("ck_topic3_agent_tasks_resource_type"),
        ),
        sa.CheckConstraint(
            "result_sha256 IS NULL OR result_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_agent_tasks_result_sha256_format"),
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', 'CANCELLED')",
            name=op.f("ck_topic3_agent_tasks_state"),
        ),
        sa.CheckConstraint(
            "attempt BETWEEN 0 AND max_attempts", name=op.f("ck_topic3_agent_tasks_attempt_budget")
        ),
        sa.CheckConstraint(
            "max_attempts BETWEEN 1 AND 8", name=op.f("ck_topic3_agent_tasks_max_attempts")
        ),
        sa.CheckConstraint(
            "task_version >= 1", name=op.f("ck_topic3_agent_tasks_positive_task_version")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic3_agent_tasks_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "blueprint_id", "blueprint_version"],
            [
                "topic3_execution_blueprints.tenant_id",
                "topic3_execution_blueprints.blueprint_id",
                "topic3_execution_blueprints.blueprint_version",
            ],
            name=op.f(
                "fk_topic3_agent_tasks_tenant_id_blueprint_id_blueprint_version_topic3_execution_blueprints"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic3_agent_tasks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("task_record_id", name=op.f("pk_topic3_agent_tasks")),
        sa.UniqueConstraint(
            "tenant_id",
            "task_id",
            "task_version",
            name=op.f("uq_topic3_agent_tasks_tenant_id_task_id_task_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "task_record_id",
            name=op.f("uq_topic3_agent_tasks_tenant_id_task_record_id"),
        ),
    )
    op.create_index(
        "ix_topic3_tasks_blueprint_state",
        "topic3_agent_tasks",
        ["tenant_id", "blueprint_id", "blueprint_version", "state"],
        unique=False,
    )
    op.create_index(
        "ix_topic3_tasks_logical_version",
        "topic3_agent_tasks",
        ["tenant_id", "task_id", "task_version"],
        unique=False,
    )
    op.create_table(
        "topic3_generated_candidates",
        sa.Column("candidate_record_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("blueprint_id", sa.UUID(), nullable=False),
        sa.Column("blueprint_version", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=24), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("candidate_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidate_sha256", sa.String(length=64), nullable=False),
        sa.Column("personalization_policy_digest", sa.String(length=64), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "agent IN ('Lecturer', 'MindMap', 'Tester', 'CodeSandbox', 'Extension')",
            name=op.f("ck_topic3_generated_candidates_agent"),
        ),
        sa.CheckConstraint(
            "candidate_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_generated_candidates_candidate_sha256_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(candidate_document) = 'object'",
            name=op.f("ck_topic3_generated_candidates_candidate_object"),
        ),
        sa.CheckConstraint(
            "personalization_policy_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_generated_candidates_personalization_digest_format"),
        ),
        sa.CheckConstraint(
            "resource_type IN ('Lecturer_Doc', 'MindMap', 'Gradient_Quiz', "
            "'Simulation_Code', 'Extension_Material')",
            name=op.f("ck_topic3_generated_candidates_resource_type"),
        ),
        sa.CheckConstraint(
            "state IN ('GENERATING', 'COMPLETE', 'FAILED', 'SUPERSEDED')",
            name=op.f("ck_topic3_generated_candidates_state"),
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name=op.f("ck_topic3_generated_candidates_positive_candidate_version"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic3_generated_candidates_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "blueprint_id", "blueprint_version"],
            [
                "topic3_execution_blueprints.tenant_id",
                "topic3_execution_blueprints.blueprint_id",
                "topic3_execution_blueprints.blueprint_version",
            ],
            name=op.f(
                "fk_topic3_generated_candidates_tenant_id_blueprint_id_blueprint_version_topic3_execution_blueprints"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic3_generated_candidates_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("candidate_record_id", name=op.f("pk_topic3_generated_candidates")),
        sa.UniqueConstraint(
            "tenant_id",
            "candidate_id",
            "candidate_version",
            name=op.f("uq_topic3_generated_candidates_tenant_id_candidate_id_candidate_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "candidate_record_id",
            name=op.f("uq_topic3_generated_candidates_tenant_id_candidate_record_id"),
        ),
    )
    op.create_index(
        "ix_topic3_candidates_blueprint_created",
        "topic3_generated_candidates",
        ["tenant_id", "blueprint_id", "blueprint_version", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic3_candidates_resource_created",
        "topic3_generated_candidates",
        ["tenant_id", "resource_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "topic3_model_invocations",
        sa.Column("invocation_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("task_version", sa.BigInteger(), nullable=False),
        sa.Column("provider_alias", sa.String(length=32), nullable=False),
        sa.Column("model_alias", sa.String(length=128), nullable=False),
        sa.Column("provider_request_id", sa.String(length=256), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("response_sha256", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "error_document",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(error_document) = 'object'",
            name=op.f("ck_topic3_model_invocations_error_object"),
        ),
        sa.CheckConstraint(
            "provider_alias IN ('spark_text', 'xfyun_code', 'seedance', 'local')",
            name=op.f("ck_topic3_model_invocations_provider_alias"),
        ),
        sa.CheckConstraint(
            "request_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_model_invocations_request_sha256_format"),
        ),
        sa.CheckConstraint(
            "response_sha256 IS NULL OR response_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_model_invocations_response_sha256_format"),
        ),
        sa.CheckConstraint(
            "state IN ('SUCCEEDED', 'FAILED', 'TIMEOUT')",
            name=op.f("ck_topic3_model_invocations_state"),
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_topic3_model_invocations_input_tokens"),
        ),
        sa.CheckConstraint(
            "latency_ms >= 0", name=op.f("ck_topic3_model_invocations_nonnegative_latency")
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_topic3_model_invocations_output_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic3_model_invocations_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "task_id", "task_version"],
            [
                "topic3_agent_tasks.tenant_id",
                "topic3_agent_tasks.task_id",
                "topic3_agent_tasks.task_version",
            ],
            name=op.f(
                "fk_topic3_model_invocations_tenant_id_task_id_task_version_topic3_agent_tasks"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic3_model_invocations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("invocation_id", name=op.f("pk_topic3_model_invocations")),
        sa.UniqueConstraint(
            "tenant_id",
            "invocation_id",
            name=op.f("uq_topic3_model_invocations_tenant_id_invocation_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "provider_alias",
            "provider_request_id",
            name=op.f("uq_topic3_model_invocations_tenant_id_provider_alias_provider_request_id"),
        ),
    )
    op.create_index(
        "ix_topic3_invocations_task_started",
        "topic3_model_invocations",
        ["tenant_id", "task_id", "task_version", "started_at"],
        unique=False,
    )
    op.create_table(
        "topic3_stream_chunks",
        sa.Column("stream_chunk_record_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("fragment_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.String(length=128), nullable=True),
        sa.Column("block_partition", sa.String(length=128), nullable=False),
        sa.Column("fragment_type", sa.String(length=16), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("data_encoding", sa.String(length=16), nullable=False),
        sa.Column("data", sa.String(length=65536), nullable=False),
        sa.Column("data_sha256", sa.String(length=64), nullable=False),
        sa.Column("emitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audit_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(fragment_type = 'END' AND is_final) OR fragment_type <> 'END'",
            name=op.f("ck_topic3_stream_chunks_end_is_final"),
        ),
        sa.CheckConstraint(
            "data_encoding IN ('utf-8-json', 'utf-8-text')",
            name=op.f("ck_topic3_stream_chunks_data_encoding"),
        ),
        sa.CheckConstraint(
            "data_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_topic3_stream_chunks_data_sha256_format"),
        ),
        sa.CheckConstraint(
            "fragment_type IN ('START', 'DELTA', 'END', 'SNAPSHOT')",
            name=op.f("ck_topic3_stream_chunks_fragment_type"),
        ),
        sa.CheckConstraint(
            "candidate_version >= 1",
            name=op.f("ck_topic3_stream_chunks_positive_candidate_version"),
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_topic3_stream_chunks_nonnegative_chunk_index")
        ),
        sa.CheckConstraint(
            "octet_length(data) <= 65536", name=op.f("ck_topic3_stream_chunks_data_size")
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.event_id"],
            name=op.f("fk_topic3_stream_chunks_audit_event_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "candidate_id", "candidate_version"],
            [
                "topic3_generated_candidates.tenant_id",
                "topic3_generated_candidates.candidate_id",
                "topic3_generated_candidates.candidate_version",
            ],
            name=op.f(
                "fk_topic3_stream_chunks_tenant_id_candidate_id_candidate_version_topic3_generated_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_topic3_stream_chunks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("stream_chunk_record_id", name=op.f("pk_topic3_stream_chunks")),
        sa.UniqueConstraint(
            "tenant_id", "fragment_id", name=op.f("uq_topic3_stream_chunks_tenant_id_fragment_id")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "stream_chunk_record_id",
            name=op.f("uq_topic3_stream_chunks_tenant_id_stream_chunk_record_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "stream_id",
            "candidate_id",
            "candidate_version",
            "block_partition",
            "chunk_index",
            name=op.f(
                "uq_topic3_stream_chunks_tenant_id_stream_id_candidate_id_candidate_version_block_partition_chunk_index"
            ),
        ),
    )
    op.create_index(
        "ix_topic3_stream_chunks_emitted",
        "topic3_stream_chunks",
        ["tenant_id", "emitted_at"],
        unique=False,
    )
    op.create_index(
        "ix_topic3_stream_chunks_stream_order",
        "topic3_stream_chunks",
        [
            "tenant_id",
            "stream_id",
            "candidate_id",
            "candidate_version",
            "block_partition",
            "chunk_index",
        ],
        unique=False,
    )
    op.execute(
        sa.text(
            """
            CREATE FUNCTION reject_topic3_history_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION 'Topic 3 immutable history cannot be updated or deleted'
                    USING ERRCODE = '55000';
            END;
            $$
            """
        )
    )
    for table_name in TOPIC3_TENANT_TABLES:
        _install_tenant_policy(table_name)
        _install_append_only_trigger(table_name)
    _grant_runtime_privileges()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in TOPIC3_TENANT_TABLES:
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{table_name}_append_only ON {table_name}"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS reject_topic3_history_mutation"))
    op.drop_index("ix_topic3_stream_chunks_stream_order", table_name="topic3_stream_chunks")
    op.drop_index("ix_topic3_stream_chunks_emitted", table_name="topic3_stream_chunks")
    op.drop_table("topic3_stream_chunks")
    op.drop_index("ix_topic3_invocations_task_started", table_name="topic3_model_invocations")
    op.drop_table("topic3_model_invocations")
    op.drop_index("ix_topic3_candidates_resource_created", table_name="topic3_generated_candidates")
    op.drop_index(
        "ix_topic3_candidates_blueprint_created", table_name="topic3_generated_candidates"
    )
    op.drop_table("topic3_generated_candidates")
    op.drop_index("ix_topic3_tasks_logical_version", table_name="topic3_agent_tasks")
    op.drop_index("ix_topic3_tasks_blueprint_state", table_name="topic3_agent_tasks")
    op.drop_table("topic3_agent_tasks")
    op.drop_index("ix_topic3_blueprints_session_version", table_name="topic3_execution_blueprints")
    op.drop_table("topic3_execution_blueprints")
    op.drop_index("ix_topic3_sessions_logical_version", table_name="topic3_generation_sessions")
    op.drop_index("ix_topic3_sessions_learner_created", table_name="topic3_generation_sessions")
    op.drop_table("topic3_generation_sessions")
    # ### end Alembic commands ###
